2019-03-29 10:11:57.702 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._instance_usage_audit run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:11:58.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._heal_instance_info_cache run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:11:58.700 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Starting heal instance info cache _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5884
2019-03-29 10:11:58.701 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Rebuilding the list of instances to heal _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5888
2019-03-29 10:11:58.702 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 78a25a9ddb164d298571d02b0fe9c441 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:11:58.728 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 78a25a9ddb164d298571d02b0fe9c441 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:11:58.729 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Didn't find any instances for network info cache update. _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5960
2019-03-29 10:11:59.730 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_unconfirmed_resizes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:00.701 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rebooting_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:03.267 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 27e86cff12c3474ea2724cbd3e7fc2bd exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:03.308 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 27e86cff12c3474ea2724cbd3e7fc2bd __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:10.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_volume_usage run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:11.667 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 2af70e8357a04c1cabf4bf80cc8c2063 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:11.673 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 6330b36224bd426f9da11b6466c54ca2 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:11.705 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 6330b36224bd426f9da11b6466c54ca2 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:11.707 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: a913e2d177be48d9bebbe23119a5a7da exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:11.714 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a913e2d177be48d9bebbe23119a5a7da __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:11.714 18469 WARNING nova.image.glance [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:12:11.716 18469 WARNING nova.image.glance [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:12:11.717 18469 DEBUG nova.compute.manager [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Stashing vm_state: active _prep_resize /usr/lib/python2.7/site-packages/nova/compute/manager.py:3738
2019-03-29 10:12:11.721 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 5fe102f47f904888abd24a95f9de2c02 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:11.877 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5fe102f47f904888abd24a95f9de2c02 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:11.879 18469 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.resize_claim" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:11.884 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 4b47fc81056943638057f8f0f77c1a8a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:11.937 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4b47fc81056943638057f8f0f77c1a8a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:11.941 18469 DEBUG nova.compute.resource_tracker [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Memory overhead for 512 MB instance; 0 MB _move_claim /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:237
2019-03-29 10:12:11.942 18469 DEBUG nova.compute.resource_tracker [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Disk overhead for 1 GB instance; 0 GB _move_claim /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:240
2019-03-29 10:12:11.945 18469 INFO nova.compute.claims [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Attempting claim: memory 512 MB, disk 1 GB, vcpus 1 CPU
2019-03-29 10:12:11.946 18469 INFO nova.compute.claims [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Total memory: 8191 MB, used: 512.00 MB
2019-03-29 10:12:11.946 18469 INFO nova.compute.claims [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] memory limit: 12286.50 MB, free: 11774.50 MB
2019-03-29 10:12:11.947 18469 INFO nova.compute.claims [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Total disk: 47 GB, used: 0.00 GB
2019-03-29 10:12:11.947 18469 INFO nova.compute.claims [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] disk limit: 47.00 GB, free: 47.00 GB
2019-03-29 10:12:11.948 18469 INFO nova.compute.claims [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Total vcpu: 2 VCPU, used: 0.00 VCPU
2019-03-29 10:12:11.948 18469 INFO nova.compute.claims [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] vcpu limit: 32.00 VCPU, free: 32.00 VCPU
2019-03-29 10:12:11.949 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Require both a host and instance NUMA topology to fit instance on host. numa_fit_instance_to_host /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1328
2019-03-29 10:12:11.949 18469 INFO nova.compute.claims [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Claim successful
2019-03-29 10:12:11.950 18469 DEBUG nova.objects.instance [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'pci_devices' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:12:11.951 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 5e133b120c77469fb60f825ffc843d73 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:11.966 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5e133b120c77469fb60f825ffc843d73 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:11.973 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: dc6be298a0964e59b6145647d08144b5 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:12.019 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: dc6be298a0964e59b6145647d08144b5 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:12.021 18469 INFO nova.compute.resource_tracker [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Updating from migration f5a19c94-1a45-4ea0-9386-77c10705c825
2019-03-29 10:12:12.026 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: f33ee346ff0748c0bf7a5f4a8d3fc085 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:12.057 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f33ee346ff0748c0bf7a5f4a8d3fc085 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:12.058 18469 DEBUG nova.scheduler.client.report [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:12:12.085 18469 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.resize_claim" :: held 0.205s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:12.085 18469 INFO nova.compute.manager [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Migrating
2019-03-29 10:12:12.087 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: c6f46fd59d044a30a2ffdd916d30bb1c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:12.101 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c6f46fd59d044a30a2ffdd916d30bb1c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:12.107 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: d2e32501a5b94173b1f39326f0ba994b exchange 'nova' topic 'compute.com57' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:12.113 18469 WARNING nova.image.glance [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:12:12.114 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 969436fb5e7840bd837f2f25e7e85ad5 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:12.140 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 969436fb5e7840bd837f2f25e7e85ad5 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:13.273 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 6ec6921cc8204465b240f815cc3372c1 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:13.314 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 6ec6921cc8204465b240f815cc3372c1 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:14.697 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._check_instance_build_time run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:14.701 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager.update_available_resource run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:14.703 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 87e706e2156e47e8bb81880d31c9c3ff exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:14.720 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 87e706e2156e47e8bb81880d31c9c3ff __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:14.724 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Auditing locally available compute resources for com58 (node: com58) update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:534
2019-03-29 10:12:14.834 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Hypervisor: free VCPUs: 2 _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:655
2019-03-29 10:12:14.834 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Hypervisor/Node resource view: name=com58 free_ram=7112MB free_disk=45GB free_vcpus=2 pci_devices=[{"dev_id": "pci_0000_00_00_0", "product_id": "7190", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7190", "address": "0000:00:00.0"}, {"dev_id": "pci_0000_00_01_0", "product_id": "7191", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7191", "address": "0000:00:01.0"}, {"dev_id": "pci_0000_00_07_0", "product_id": "7110", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7110", "address": "0000:00:07.0"}, {"dev_id": "pci_0000_00_07_1", "product_id": "7111", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7111", "address": "0000:00:07.1"}, {"dev_id": "pci_0000_00_07_3", "product_id": "7113", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7113", "address": "0000:00:07.3"}, {"dev_id": "pci_0000_00_07_7", "product_id": "0740", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0740", "address": "0000:00:07.7"}, {"dev_id": "pci_0000_00_0f_0", "product_id": "0405", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0405", "address": "0000:00:0f.0"}, {"dev_id": "pci_0000_00_11_0", "product_id": "0790", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0790", "address": "0000:00:11.0"}, {"dev_id": "pci_0000_00_15_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.0"}, {"dev_id": "pci_0000_03_00_0", "product_id": "07c0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07c0", "address": "0000:03:00.0"}, {"dev_id": "pci_0000_00_15_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.1"}, {"dev_id": "pci_0000_00_15_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.2"}, {"dev_id": "pci_0000_00_15_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.3"}, {"dev_id": "pci_0000_00_15_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.4"}, {"dev_id": "pci_0000_00_15_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.5"}, {"dev_id": "pci_0000_00_15_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.6"}, {"dev_id": "pci_0000_00_15_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.7"}, {"dev_id": "pci_0000_00_16_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.0"}, {"dev_id": "pci_0000_0b_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:0b:00.0"}, {"dev_id": "pci_0000_00_16_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.1"}, {"dev_id": "pci_0000_00_16_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.2"}, {"dev_id": "pci_0000_00_16_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.3"}, {"dev_id": "pci_0000_00_16_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.4"}, {"dev_id": "pci_0000_00_16_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.5"}, {"dev_id": "pci_0000_00_16_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.6"}, {"dev_id": "pci_0000_00_16_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.7"}, {"dev_id": "pci_0000_00_17_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.0"}, {"dev_id": "pci_0000_13_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:13:00.0"}, {"dev_id": "pci_0000_00_17_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.1"}, {"dev_id": "pci_0000_00_17_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.2"}, {"dev_id": "pci_0000_00_17_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.3"}, {"dev_id": "pci_0000_00_17_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.4"}, {"dev_id": "pci_0000_00_17_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.5"}, {"dev_id": "pci_0000_00_17_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.6"}, {"dev_id": "pci_0000_00_17_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.7"}, {"dev_id": "pci_0000_00_18_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.0"}, {"dev_id": "pci_0000_00_18_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.1"}, {"dev_id": "pci_0000_00_18_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.2"}, {"dev_id": "pci_0000_00_18_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.3"}, {"dev_id": "pci_0000_00_18_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.4"}, {"dev_id": "pci_0000_00_18_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.5"}, {"dev_id": "pci_0000_00_18_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.6"}, {"dev_id": "pci_0000_00_18_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.7"}] _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:672
2019-03-29 10:12:14.835 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker._update_available_resource" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:14.837 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 2f74b1992d214b338ccaeedb226f4269 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:14.871 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 2f74b1992d214b338ccaeedb226f4269 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:14.873 18469 DEBUG nova.scheduler.client.report [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:12:14.908 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: c26bd30b6b3640c2ba89bb61377a10b6 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:14.927 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c26bd30b6b3640c2ba89bb61377a10b6 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:14.942 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 9f57792f36e044dd9bb5e7097ce9ae06 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:14.977 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 9f57792f36e044dd9bb5e7097ce9ae06 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:14.979 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Migration for instance f5a19c94-1a45-4ea0-9386-77c10705c825 refers to another host's instance! _pair_instances_to_migrations /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:568
2019-03-29 10:12:14.981 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: e44505759a8844eb97a9cf4510887002 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:15.023 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e44505759a8844eb97a9cf4510887002 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:15.027 18469 INFO nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Updating from migration f5a19c94-1a45-4ea0-9386-77c10705c825
2019-03-29 10:12:15.027 18469 DEBUG nova.objects.instance [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lazy-loading 'flavor' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:12:15.029 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 2f1e2679d56d4ed0b9cfcd1f609cd6f1 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:15.081 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 2f1e2679d56d4ed0b9cfcd1f609cd6f1 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:15.083 18469 DEBUG nova.objects.instance [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lazy-loading 'migration_context' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:12:15.084 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: e8c01ec2c0564b5c94ae511b780c4a05 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:15.093 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e8c01ec2c0564b5c94ae511b780c4a05 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:15.096 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Total usable vcpus: 2, total allocated vcpus: 1 _report_final_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:688
2019-03-29 10:12:15.097 18469 INFO nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Final resource view: name=com58 phys_ram=8191MB used_ram=1024MB phys_disk=47GB used_disk=1GB total_vcpus=2 used_vcpus=1 pci_stats=[]
2019-03-29 10:12:15.099 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Compute_service record updated for com58:com58 _update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:626
2019-03-29 10:12:15.100 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lock "compute_resources" released by "nova.compute.resource_tracker._update_available_resource" :: held 0.265s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:21.195 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: e4ce1b49c11445a485fe8fe66ee3174e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:21.201 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 4888c0be7b984550b25efca4a9deb0d1 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:21.250 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4888c0be7b984550b25efca4a9deb0d1 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:21.318 18469 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-771b9291-5139-421d-896f-ea24b48d6693 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:21.319 18469 INFO nova.network.neutronv2.api [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating port b3249515-3aab-439f-ba9c-bc498756871a with attributes {'binding:host_id': u'com58'}
2019-03-29 10:12:21.757 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 401d69b4a5f442868d7ac28e051d196a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:21.760 18469 DEBUG nova.compute.manager [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:12:21.761 18469 DEBUG oslo_concurrency.lockutils [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:21.761 18469 DEBUG nova.compute.manager [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:12:21.762 18469 DEBUG oslo_concurrency.lockutils [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:21.762 18469 DEBUG nova.compute.manager [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] No waiting events found dispatching network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:12:21.762 18469 WARNING nova.compute.manager [req-01c403e5-ae70-4a58-8833-81151e286efa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received unexpected event network-vif-unplugged-b3249515-3aab-439f-ba9c-bc498756871a for instance
2019-03-29 10:12:22.299 18469 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] PUT call to neutron for http://172.30.126.56:9696/v2.0/ports/b3249515-3aab-439f-ba9c-bc498756871a.json used request id req-449d94ab-9d1e-466d-b783-5de986e84d7b _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:22.300 18469 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:12:22.301 18469 DEBUG nova.network.neutronv2.api [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:12:22.303 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 032c21be68b8473c8de89d9cb4e44cba exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:22.314 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 032c21be68b8473c8de89d9cb4e44cba __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:22.382 18469 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-7177276d-d6b7-4c54-9bc3-29dbe95d510d _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:22.497 18469 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-c427bf44-57f9-4272-886b-24be59250c33 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:22.520 18469 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-153850df-caeb-451c-b622-551c1a64c8a0 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:22.590 18469 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-d9a2c0ae-c0e5-4679-b40d-d5ce5ade04a7 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:22.634 18469 DEBUG neutronclient.v2_0.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-635bca04-f61f-49bf-a710-1bb14396019a _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:22.635 18469 DEBUG nova.network.base_api [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:12:22.637 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: acc102e7dc164b098a28e9d7dc617bb8 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:22.699 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rescued_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:22.748 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: acc102e7dc164b098a28e9d7dc617bb8 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:22.750 18469 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:12:22.756 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: f30854f1ec4c49acbddbf47b8eb0727f exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:22.898 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f30854f1ec4c49acbddbf47b8eb0727f __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:22.903 18469 WARNING nova.image.glance [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:12:22.907 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 180d0e10376a48c48318b20f337a2184 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:22.924 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 180d0e10376a48c48318b20f337a2184 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:22.927 18469 DEBUG os_brick.utils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> get_connector_properties: call u"{'execute': None, 'my_ip': '172.30.126.58', 'enforce_multipath': True, 'host': 'com58', 'root_helper': 'sudo nova-rootwrap /etc/nova/rootwrap.conf', 'multipath': False}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:12:22.929 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('cat', '/etc/iscsi/initiatorname.iscsi'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:22.929 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): cat /etc/iscsi/initiatorname.iscsi out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:22.938 18469 DEBUG oslo.privsep.daemon [-] CMD "cat /etc/iscsi/initiatorname.iscsi" returned: 0 in 0.009s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:22.938 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('InitiatorName=iqn.1994-05.com.redhat:9affbb458449\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:22.939 18469 DEBUG os_brick.initiator.linuxfc [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:12:22.939 18469 DEBUG os_brick.initiator.linuxfc [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:12:22.940 18469 DEBUG os_brick.utils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== get_connector_properties: return (12ms) {'initiator': u'iqn.1994-05.com.redhat:9affbb458449', 'ip': u'172.30.126.58', 'platform': u'x86_64', 'host': u'com58', 'do_local_attach': False, 'os_type': u'linux2', 'multipath': False} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:12:22.942 18469 DEBUG cinderclient.v2.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X POST http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}8909f64cb46a118d57e7cdb53d3762c4971c4edf" -d '{"os-initialize_connection": {"connector": {"platform": "x86_64", "host": "com58", "do_local_attach": false, "ip": "172.30.126.58", "os_type": "linux2", "multipath": false, "initiator": "iqn.1994-05.com.redhat:9affbb458449"}}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:12:23.278 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: d7ca9835aa0d4a859a4a9e25f629866e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:23.337 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: d7ca9835aa0d4a859a4a9e25f629866e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:23.952 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 7c05535ece9b4abebfa29d00c909c7d1 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:23.955 18469 DEBUG nova.compute.manager [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-changed external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:12:23.955 18469 DEBUG oslo_concurrency.lockutils [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:12:23.956 18469 DEBUG nova.network.neutronv2.api [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:12:23.957 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: 60931f58b84d44e7840009fd7c131461 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:23.974 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 60931f58b84d44e7840009fd7c131461 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:24.358 18469 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-6914024b-f3e5-438c-9f59-297e3878dbd8 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:24.400 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 912de25ed4d64bf2aa92948612a9df86 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:24.404 18469 DEBUG nova.compute.manager [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:12:24.405 18469 DEBUG oslo_concurrency.lockutils [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:24.405 18469 DEBUG nova.compute.manager [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:12:24.406 18469 DEBUG oslo_concurrency.lockutils [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:24.406 18469 DEBUG nova.compute.manager [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] No waiting events found dispatching network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:12:24.407 18469 WARNING nova.compute.manager [req-abc98abf-3493-4433-adce-1a48d1d8bd01 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received unexpected event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a for instance
2019-03-29 10:12:24.864 18469 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-e8986ed8-7757-4aaa-bcaf-8d66a680224d _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:24.885 18469 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-6c80e86a-851f-4898-a347-b2d46fbfb59d _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:24.945 18469 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-9939bf7b-6ed9-4a3a-97bd-ee0b2cb8c523 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:24.990 18469 DEBUG neutronclient.v2_0.client [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-f98ade85-0abf-4004-9066-c18127a5f1ce _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:24.991 18469 DEBUG nova.network.base_api [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:12:24.993 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: 07425a03ceb94826a751d70c8a428a08 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:25.011 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 07425a03ceb94826a751d70c8a428a08 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:25.012 18469 DEBUG oslo_concurrency.lockutils [req-52e5b5a6-cc8c-4858-87a2-ac98884f1a9c 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:12:27.044 18469 DEBUG cinderclient.v2.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [200] X-Compute-Request-Id: req-da32818a-f3e3-4b87-b144-8b15c2b16b71 Content-Type: application/json Content-Length: 447 X-Openstack-Request-Id: req-da32818a-f3e3-4b87-b144-8b15c2b16b71 Date: Fri, 29 Mar 2019 02:12:27 GMT Connection: keep-alive 
RESP BODY: {"connection_info": {"driver_volume_type": "iscsi", "data": {"auth_password": "TPnqk7LML2MKpPv4", "target_discovered": false, "encrypted": false, "qos_specs": null, "target_iqn": "iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e", "target_portal": "172.30.126.56:3260", "volume_id": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "target_lun": 0, "access_mode": "rw", "auth_username": "PutS9jPtTsLadXTr42qr", "auth_method": "CHAP"}}}
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:12:27.045 18469 DEBUG cinderclient.v2.client [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action used request id req-da32818a-f3e3-4b87-b144-8b15c2b16b71 request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:12:27.047 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: a696c024587949d09bb0f65194e9c5b3 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:27.082 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a696c024587949d09bb0f65194e9c5b3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:27.083 18469 DEBUG nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Starting finish_migration finish_migration /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:7428
2019-03-29 10:12:27.084 18469 INFO nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Creating image
2019-03-29 10:12:27.085 18469 DEBUG nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Ensure instance console log exists: /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/console.log _ensure_console_log_for_instance /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:3019
2019-03-29 10:12:27.087 18469 DEBUG nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Start _get_guest_xml network_info=[{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"version": 4, "vif_mac": "fa:16:3e:29:72:d6", "floating_ips": [], "label": "net10", "meta": {}, "address": "10.10.10.11", "type": "fixed"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] disk_info={'disk_bus': 'virtio', 'cdrom_bus': 'ide', 'mapping': {u'/dev/vda': {'bus': u'virtio', 'boot_index': '1', 'type': u'disk', 'dev': u'vda'}, 'root': {'bus': u'virtio', 'boot_index': '1', 'type': u'disk', 'dev': u'vda'}, 'disk.config': {'bus': 'ide', 'type': 'cdrom', 'dev': 'hda'}}} image_meta=ImageMeta(checksum=<?>,container_format=<?>,created_at=<?>,direct_url=<?>,disk_format=<?>,id=<?>,min_disk=0,min_ram=0,name=<?>,owner=<?>,properties=ImageMetaProps,protected=<?>,size=1073741824,status='active',tags=<?>,updated_at=<?>,virtual_size=<?>,visibility=<?>) rescue=None block_device_info={'swap': None, 'root_device_name': u'/dev/vda', 'ephemerals': [], 'block_device_mapping': [{'guest_format': None, 'boot_index': 0, 'mount_device': u'/dev/vda', 'connection_info': {u'driver_volume_type': u'iscsi', 'connector': {'platform': 'x86_64', 'host': 'com58', 'do_local_attach': False, 'ip': '172.30.126.58', 'os_type': 'linux2', 'multipath': False, 'initiator': u'iqn.1994-05.com.redhat:9affbb458449'}, 'serial': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'data': {u'access_mode': u'rw', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_portal': u'172.30.126.56:3260', u'volume_id': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_lun': 0, u'auth_password': u'***', u'auth_username': u'PutS9jPtTsLadXTr42qr', u'auth_method': u'CHAP'}}, 'disk_bus': u'virtio', 'device_type': u'disk', 'delete_on_termination': False}]} _get_guest_xml /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:4971
2019-03-29 10:12:27.106 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Getting desirable topologies for flavor Flavor(created_at=2019-03-25T11:43:43Z,deleted=False,deleted_at=None,disabled=False,ephemeral_gb=0,extra_specs={},flavorid='1',id=1,is_public=True,memory_mb=512,name='m1.tiny',projects=<?>,root_gb=1,rxtx_factor=1.0,swap=0,updated_at=None,vcpu_weight=0,vcpus=1) and image_meta ImageMeta(checksum=<?>,container_format=<?>,created_at=<?>,direct_url=<?>,disk_format=<?>,id=<?>,min_disk=0,min_ram=0,name=<?>,owner=<?>,properties=ImageMetaProps,protected=<?>,size=1073741824,status='active',tags=<?>,updated_at=<?>,virtual_size=<?>,visibility=<?>), allow threads: True _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:560
2019-03-29 10:12:27.107 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flavor limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:306
2019-03-29 10:12:27.107 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Image limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:317
2019-03-29 10:12:27.107 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flavor pref -1:-1:-1 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:340
2019-03-29 10:12:27.108 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Image pref -1:-1:-1 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:359
2019-03-29 10:12:27.108 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Chosen -1:-1:-1 limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:388
2019-03-29 10:12:27.109 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Topology preferred VirtCPUTopology(cores=-1,sockets=-1,threads=-1), maximum VirtCPUTopology(cores=65536,sockets=65536,threads=65536) _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:564
2019-03-29 10:12:27.109 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Build topologies for 1 vcpu(s) 1:1:1 _get_possible_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:427
2019-03-29 10:12:27.110 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Got 1 possible topologies _get_possible_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:454
2019-03-29 10:12:27.110 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Possible topologies [VirtCPUTopology(cores=1,sockets=1,threads=1)] _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:569
2019-03-29 10:12:27.110 18469 DEBUG nova.virt.hardware [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Sorted desired topologies [VirtCPUTopology(cores=1,sockets=1,threads=1)] _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:594
2019-03-29 10:12:27.111 18469 DEBUG nova.objects.instance [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'vcpu_model' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:12:27.112 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 7ed087fd302442b5932fce01796b7fa2 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:27.124 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 7ed087fd302442b5932fce01796b7fa2 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:27.129 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Calling os-brick to attach iSCSI Volume connect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:63
2019-03-29 10:12:27.130 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> connect_volume: call u"{'args': (<os_brick.initiator.connectors.iscsi.ISCSIConnector object at 0x5ae9b50>, {u'access_mode': u'rw', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_portal': u'172.30.126.56:3260', u'volume_id': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_lun': 0, u'auth_password': u'***', u'auth_username': u'PutS9jPtTsLadXTr42qr', u'auth_method': u'CHAP'}), 'kwargs': {}}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:12:27.131 18469 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" acquired by "os_brick.initiator.connectors.iscsi.connect_volume" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:27.131 18469 INFO os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Multipath discovery for iSCSI not enabled.
2019-03-29 10:12:27.132 18469 INFO os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Trying to connect to iSCSI portal 172.30.126.56:3260
2019-03-29 10:12:27.133 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.133 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.143 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260" returned: 21 in 0.010s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.143 18469 DEBUG oslo.privsep.daemon [-] u'iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260' failed. Not Retrying. out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.144 18469 DEBUG oslo.privsep.daemon [-] privsep: Exception during request[102505040]: Unexpected error while running command.
Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260
Exit code: 21
Stdout: u''
Stderr: u'iscsiadm: No records found\n' out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.144 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (5, 'oslo_concurrency.processutils.ProcessExecutionError', (u'', u'iscsiadm: No records found\n', 21, u'iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260', None)) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.145 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--interface', 'default', '--op', 'new'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.145 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --interface default --op new out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.151 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --interface default --op new" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.151 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 172.30.126.56,3260,-1 iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e] added\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.151 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--interface', 'default', '--op', 'new'): stdout=New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 172.30.126.56,3260,-1 iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e] added
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:27.152 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.session.auth.authmethod', '-v', u'CHAP'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.152 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.authmethod -v CHAP out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.157 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.authmethod -v CHAP" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.158 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.158 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.session.auth.authmethod', '-v', u'CHAP'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:27.159 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.session.auth.username', '-v', u'PutS9jPtTsLadXTr42qr'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.159 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.username -v PutS9jPtTsLadXTr42qr out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.164 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.username -v PutS9jPtTsLadXTr42qr" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.164 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.165 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.session.auth.username', '-v', u'PutS9jPtTsLadXTr42qr'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:27.165 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.session.auth.password', '-v', u'TPnqk7LML2MKpPv4'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.165 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.password -v *** out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.170 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.password -v ***" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.170 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.170 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.session.auth.password', '-v', u'***'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:27.171 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'session'), {'check_exit_code': (0, 1, 21)}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.171 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m session out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.175 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m session" returned: 21 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.175 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('', 'iscsiadm: No active sessions.\n')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.175 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ['-m', 'session']: stdout= stderr=iscsiadm: No active sessions.
 _run_iscsiadm_bare /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:824
2019-03-29 10:12:27.176 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--login'), {'attempts': 1, 'check_exit_code': (0, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.176 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --login out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.216 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --login" returned: 0 in 0.039s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.217 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('Logging in to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] (multiple)\nLogin to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.217 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--login',): stdout=Logging in to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] (multiple)
Login to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:27.219 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.startup', '-v', 'automatic'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.219 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v automatic out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.224 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v automatic" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.224 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.225 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.startup', '-v', 'automatic'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:27.225 18469 INFO os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ISCSI volume not yet found at: [u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0']. Will rescan & retry.  Try number: 0.
2019-03-29 10:12:27.226 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--rescan'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.226 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --rescan out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.251 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --rescan" returned: 0 in 0.025s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.252 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('Rescanning session [sid: 9, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.252 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--rescan',): stdout=Rescanning session [sid: 9, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:12:27.252 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Found iSCSI node [u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0'] (after 1 rescans) connect_volume /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:437
2019-03-29 10:12:27.254 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'os_brick.privileged.rootwrap.execute_root', ('/lib/udev/scsi_id', '--page', '0x83', '--whitelisted', u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.255 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): /lib/udev/scsi_id --page 0x83 --whitelisted /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.261 18469 DEBUG oslo.privsep.daemon [-] CMD "/lib/udev/scsi_id --page 0x83 --whitelisted /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0" returned: 0 in 0.007s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.261 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, ('36001405fb81b00707464d729f24ff6c3\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.262 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Device WWN = '36001405fb81b00707464d729f24ff6c3' connect_volume /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:444
2019-03-29 10:12:27.262 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] connect_volume returning {'path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', 'scsi_wwn': u'36001405fb81b00707464d729f24ff6c3', 'type': 'block'} connect_volume /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:456
2019-03-29 10:12:27.263 18469 DEBUG oslo_concurrency.lockutils [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" released by "os_brick.initiator.connectors.iscsi.connect_volume" :: held 0.132s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:27.263 18469 DEBUG os_brick.initiator.connectors.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== connect_volume: return (132ms) {'path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', 'scsi_wwn': u'36001405fb81b00707464d729f24ff6c3', 'type': u'block'} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:12:27.264 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Attached iSCSI volume {'path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', 'scsi_wwn': u'36001405fb81b00707464d729f24ff6c3', 'type': 'block'} connect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:65
2019-03-29 10:12:27.269 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: b3c9561dea2f4b8b98442c756b2d7885 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:27.299 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b3c9561dea2f4b8b98442c756b2d7885 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:27.302 18469 DEBUG nova.virt.libvirt.vif [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=True,config_drive='True',created_at=2019-03-29T02:02:33Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=<?>,disable_terminate=False,display_description='vm001',display_name='vm001',ec2_ids=<?>,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm001',id=24,image_ref='',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=<?>,launch_index=0,launched_at=2019-03-29T02:02:45Z,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=MigrationContext,new_flavor=Flavor(1),node='com58',numa_topology=None,old_flavor=Flavor(1),os_type=None,pci_devices=PciDeviceList,pci_requests=InstancePCIRequests,power_state=1,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-x56iqcqr',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',clean_attempts='1',image_architecture='x86_64',image_base_image_ref='',image_min_disk='1',image_min_ram='0',old_vm_state='active'},tags=<?>,task_state='resize_finish',terminated_at=None,updated_at=2019-03-29T02:12:21Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,vcpu_model=VirtCPUModel,vcpus=1,vm_mode=None,vm_state='active') vif={"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"version": 4, "vif_mac": "fa:16:3e:29:72:d6", "floating_ips": [], "label": "net10", "meta": {}, "address": "10.10.10.11", "type": "fixed"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} virt_type=qemu get_config /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:529
2019-03-29 10:12:27.303 18469 DEBUG nova.network.os_vif_util [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"version": 4, "vif_mac": "fa:16:3e:29:72:d6", "floating_ips": [], "label": "net10", "meta": {}, "address": "10.10.10.11", "type": "fixed"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:12:27.304 18469 DEBUG nova.network.os_vif_util [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:12:27.311 18469 DEBUG nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] End _get_guest_xml xml=<domain type="qemu">
  <uuid>f5a19c94-1a45-4ea0-9386-77c10705c825</uuid>
  <name>instance-00000018</name>
  <memory>524288</memory>
  <vcpu>1</vcpu>
  <metadata>
    <nova:instance xmlns:nova="http://openstack.org/xmlns/libvirt/nova/1.0">
      <nova:package version="0.0.0-1.el7.ceos"/>
      <nova:name>vm001</nova:name>
      <nova:creationTime>2019-03-29 02:12:27</nova:creationTime>
      <nova:flavor name="m1.tiny">
        <nova:memory>512</nova:memory>
        <nova:disk>1</nova:disk>
        <nova:swap>0</nova:swap>
        <nova:ephemeral>0</nova:ephemeral>
        <nova:vcpus>1</nova:vcpus>
      </nova:flavor>
      <nova:owner>
        <nova:user uuid="9e9e53917dda421083fa6af425c6bfbf">admin</nova:user>
        <nova:project uuid="d4bbd972ca1b463ba028ccd1df983917">admin</nova:project>
      </nova:owner>
    </nova:instance>
  </metadata>
  <sysinfo type="smbios">
    <system>
      <entry name="manufacturer">RDO</entry>
      <entry name="product">OpenStack Compute</entry>
      <entry name="version">0.0.0-1.el7.ceos</entry>
      <entry name="serial">b72f0c91-de47-47b5-9c10-43dfb0050cac</entry>
      <entry name="uuid">f5a19c94-1a45-4ea0-9386-77c10705c825</entry>
      <entry name="family">Virtual Machine</entry>
    </system>
  </sysinfo>
  <os>
    <type>hvm</type>
    <boot dev="hd"/>
    <smbios mode="sysinfo"/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cputune>
    <shares>1024</shares>
  </cputune>
  <clock offset="utc"/>
  <cpu match="exact">
    <topology sockets="1" cores="1" threads="1"/>
  </cpu>
  <devices>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw" cache="none"/>
      <source file="/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config"/>
      <target bus="ide" dev="hda"/>
    </disk>
    <disk type="block" device="disk">
      <driver name="qemu" type="raw" cache="none" io="native"/>
      <source dev="/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0"/>
      <target bus="virtio" dev="vda"/>
      <serial>78a56ddc-ee21-4278-991e-17b30d68fa6e</serial>
    </disk>
    <interface type="bridge">
      <mac address="fa:16:3e:29:72:d6"/>
      <model type="virtio"/>
      <driver name="qemu"/>
      <source bridge="qbrb3249515-3a"/>
      <target dev="tapb3249515-3a"/>
    </interface>
    <serial type="pty">
      <log file="/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/console.log" append="off"/>
    </serial>
    <input type="tablet" bus="usb"/>
    <graphics type="vnc" autoport="yes" keymap="en-us" listen="0.0.0.0"/>
    <video>
      <model type="cirrus"/>
    </video>
    <memballoon model="virtio">
      <stats period="10"/>
    </memballoon>
  </devices>
</domain>
 _get_guest_xml /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:4978
2019-03-29 10:12:27.312 18469 DEBUG nova.virt.libvirt.vif [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=True,config_drive='True',created_at=2019-03-29T02:02:33Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=<?>,disable_terminate=False,display_description='vm001',display_name='vm001',ec2_ids=<?>,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm001',id=24,image_ref='',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=<?>,launch_index=0,launched_at=2019-03-29T02:02:45Z,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=MigrationContext,new_flavor=Flavor(1),node='com58',numa_topology=None,old_flavor=Flavor(1),os_type=None,pci_devices=PciDeviceList,pci_requests=InstancePCIRequests,power_state=1,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-x56iqcqr',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',clean_attempts='1',image_architecture='x86_64',image_base_image_ref='',image_min_disk='1',image_min_ram='0',old_vm_state='active'},tags=<?>,task_state='resize_finish',terminated_at=None,updated_at=2019-03-29T02:12:21Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,vcpu_model=VirtCPUModel,vcpus=1,vm_mode=None,vm_state='active') vif={"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"version": 4, "vif_mac": "fa:16:3e:29:72:d6", "floating_ips": [], "label": "net10", "meta": {}, "address": "10.10.10.11", "type": "fixed"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} plug /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:776
2019-03-29 10:12:27.313 18469 DEBUG nova.network.os_vif_util [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"version": 4, "vif_mac": "fa:16:3e:29:72:d6", "floating_ips": [], "label": "net10", "meta": {}, "address": "10.10.10.11", "type": "fixed"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:12:27.313 18469 DEBUG nova.network.os_vif_util [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:12:27.314 18469 DEBUG os_vif [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Plugging vif VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') plug /usr/lib/python2.7/site-packages/os_vif/__init__.py:79
2019-03-29 10:12:27.317 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'vif_plug_ovs.linux_net.ensure_bridge', (u'qbrb3249515-3a',), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.317 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl addbr qbrb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.323 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl addbr qbrb3249515-3a" returned: 0 in 0.007s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.323 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl setfd qbrb3249515-3a 0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.328 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl setfd qbrb3249515-3a 0" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.328 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl stp qbrb3249515-3a off out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.332 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl stp qbrb3249515-3a off" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.332 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee /sys/class/net/qbrb3249515-3a/bridge/multicast_snooping out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.335 18469 DEBUG oslo.privsep.daemon [-] CMD "tee /sys/class/net/qbrb3249515-3a/bridge/multicast_snooping" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.336 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee /proc/sys/net/ipv6/conf/qbrb3249515-3a/disable_ipv6 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.339 18469 DEBUG oslo.privsep.daemon [-] CMD "tee /proc/sys/net/ipv6/conf/qbrb3249515-3a/disable_ipv6" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.339 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.341 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'vif_plug_ovs.linux_net.create_veth_pair', ('qvbb3249515-3a', 'qvob3249515-3a', 1500), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.341 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link add qvbb3249515-3a type veth peer name qvob3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.354 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link add qvbb3249515-3a type veth peer name qvob3249515-3a" returned: 0 in 0.013s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.354 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvbb3249515-3a up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.360 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvbb3249515-3a up" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.361 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvbb3249515-3a promisc on out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.365 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvbb3249515-3a promisc on" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.365 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvbb3249515-3a mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.369 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvbb3249515-3a mtu 1500" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.369 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.374 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a up" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.374 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a promisc on out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.378 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a promisc on" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.378 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.380 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a mtu 1500" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.380 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.382 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'vif_plug_ovs.linux_net.add_bridge_port', (u'qbrb3249515-3a', 'qvbb3249515-3a'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.382 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qbrb3249515-3a up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.385 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qbrb3249515-3a up" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.385 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl addif qbrb3249515-3a qvbb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.393 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl addif qbrb3249515-3a qvbb3249515-3a" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.393 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.394 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'vif_plug_ovs.linux_net.ensure_ovs_bridge', (u'br-int', 'system'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.394 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl -- --may-exist add-br br-int -- set Bridge br-int datapath_type=system out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.404 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl -- --may-exist add-br br-int -- set Bridge br-int datapath_type=system" returned: 0 in 0.009s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.404 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.405 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505040]: (3, 'vif_plug_ovs.linux_net.create_ovs_vif_port', (u'br-int', 'qvob3249515-3a', 'b3249515-3aab-439f-ba9c-bc498756871a', u'fa:16:3e:29:72:d6', 'f5a19c94-1a45-4ea0-9386-77c10705c825', 1500), {'timeout': 120}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.405 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl --timeout=120 -- --if-exists del-port qvob3249515-3a -- add-port br-int qvob3249515-3a -- set Interface qvob3249515-3a external-ids:iface-id=b3249515-3aab-439f-ba9c-bc498756871a external-ids:iface-status=active external-ids:attached-mac=fa:16:3e:29:72:d6 external-ids:vm-uuid=f5a19c94-1a45-4ea0-9386-77c10705c825 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.438 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl --timeout=120 -- --if-exists del-port qvob3249515-3a -- add-port br-int qvob3249515-3a -- set Interface qvob3249515-3a external-ids:iface-id=b3249515-3aab-439f-ba9c-bc498756871a external-ids:iface-status=active external-ids:attached-mac=fa:16:3e:29:72:d6 external-ids:vm-uuid=f5a19c94-1a45-4ea0-9386-77c10705c825" returned: 0 in 0.032s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.439 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.446 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a mtu 1500" returned: 0 in 0.008s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.446 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505040]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:12:27.447 18469 INFO os_vif [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Successfully plugged vif VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a')
2019-03-29 10:12:27.498 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 64e96e1d425846d88d7106ae236fda2c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:27.558 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 64e96e1d425846d88d7106ae236fda2c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:27.559 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 80e32b6a24df4d57b41c8046ae39a736 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:27.570 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 80e32b6a24df4d57b41c8046ae39a736 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:27.575 18469 INFO nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Using config drive
2019-03-29 10:12:27.879 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553825547.88, f5a19c94-1a45-4ea0-9386-77c10705c825 => Resumed> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:12:27.879 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Resumed (Lifecycle Event)
2019-03-29 10:12:27.881 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 5aea36c9e189405d90dedaca7ff06b0e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:27.892 18469 INFO nova.virt.libvirt.driver [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance running successfully.
2019-03-29 10:12:27.897 18469 DEBUG nova.virt.libvirt.guest [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Failed to set time: agent not configured sync_guest_time /usr/lib/python2.7/site-packages/nova/virt/libvirt/guest.py:177
2019-03-29 10:12:27.897 18469 DEBUG nova.virt.libvirt.driver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] finish_migration finished successfully. finish_migration /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:7520
2019-03-29 10:12:27.899 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 5b1505d7bb8147aa976e282b7b88e737 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:27.936 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5aea36c9e189405d90dedaca7ff06b0e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:27.937 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:12:27.943 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Synchronizing instance power state after lifecycle event "Resumed"; current vm_state: active, current task_state: resize_finish, current DB power_state: 1, VM power_state: 1 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:12:27.944 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 3ceb3bfce67d42cc9543bee701da8704 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:27.946 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5b1505d7bb8147aa976e282b7b88e737 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:27.952 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 91275b1c66024db6aec64c9be74895bc exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:28.029 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 3ceb3bfce67d42cc9543bee701da8704 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:28.030 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] During sync_power_state the instance has a pending task (resize_finish). Skip.
2019-03-29 10:12:28.030 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553825547.88, f5a19c94-1a45-4ea0-9386-77c10705c825 => Started> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:12:28.031 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Started (Lifecycle Event)
2019-03-29 10:12:28.033 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: eb4b87008c7446348bc3a78bd4dd980a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:28.153 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: eb4b87008c7446348bc3a78bd4dd980a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:28.155 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:12:28.178 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 91275b1c66024db6aec64c9be74895bc __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:28.187 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: 9d3c4151e09847c38cfb319e7ea08c77 FANOUT topic 'scheduler' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:539
2019-03-29 10:12:28.188 18469 WARNING nova.image.glance [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:12:28.192 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: f0f1f7d227be4b5e9024296d02796712 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:28.194 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Synchronizing instance power state after lifecycle event "Started"; current vm_state: active, current task_state: resize_finish, current DB power_state: 1, VM power_state: 1 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:12:28.196 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 41b33c6d42bc4ca0802119e801d0681c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:28.199 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f0f1f7d227be4b5e9024296d02796712 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:28.200 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-980e90fd-fee6-47b2-887e-f4046cfb3906 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 66f9873a7bd846e783c94f9450a01e75 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:28.250 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 41b33c6d42bc4ca0802119e801d0681c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:28.263 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 66f9873a7bd846e783c94f9450a01e75 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:28.880 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: ed04951ee0f04af4aa5c6cc331fd6243 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:12:28.883 18469 DEBUG nova.compute.manager [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:12:28.883 18469 DEBUG oslo_concurrency.lockutils [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:12:28.884 18469 DEBUG nova.compute.manager [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:12:28.884 18469 DEBUG oslo_concurrency.lockutils [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:12:28.884 18469 DEBUG nova.compute.manager [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] No waiting events found dispatching network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:12:28.885 18469 WARNING nova.compute.manager [req-32fce7e9-0eb7-4ac7-b7f9-58e6d5aac0da 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received unexpected event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a for instance
2019-03-29 10:12:33.280 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: b08a1af0d85d4184bfedf758981197ce exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:33.336 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b08a1af0d85d4184bfedf758981197ce __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:38.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._run_pending_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:38.701 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Cleaning up deleted instances _run_pending_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6911
2019-03-29 10:12:38.703 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 74b4efd75b2a4adabc216629023ac508 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:38.718 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 74b4efd75b2a4adabc216629023ac508 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:38.719 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] There are 0 instances to clean _run_pending_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6920











2019-03-29 10:12:43.279 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 755cf6c6c19d4c4d9c89c45241ed36d6 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:43.314 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 755cf6c6c19d4c4d9c89c45241ed36d6 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:49.721 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._reclaim_queued_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:49.722 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CONF.reclaim_instance_interval <= 0, skipping... _reclaim_queued_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6556
2019-03-29 10:12:53.277 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 5efe211348d24ea2822b2c8b4625b2a6 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:53.316 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5efe211348d24ea2822b2c8b4625b2a6 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:58.699 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._heal_instance_info_cache run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:12:58.700 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Starting heal instance info cache _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5884
2019-03-29 10:12:58.700 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Rebuilding the list of instances to heal _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5888
2019-03-29 10:12:58.702 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: cf56c7d09fb94b02b6a66555f07471d4 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:58.726 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: cf56c7d09fb94b02b6a66555f07471d4 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:58.727 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:12:58.728 18469 DEBUG nova.network.neutronv2.api [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:12:58.728 18469 DEBUG nova.objects.instance [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lazy-loading 'info_cache' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:12:58.729 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 04ad27182ba647088778b12cdbafffa9 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:58.770 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 04ad27182ba647088778b12cdbafffa9 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:58.772 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 5c536fc9c1764319a668d1dac09aa53e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:58.781 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5c536fc9c1764319a668d1dac09aa53e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:59.033 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-40ca1df1-471b-4731-83f2-0d41e669e96f _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:59.147 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-2c5cb284-b57e-4b73-857b-d3a4f4fe55f5 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:59.175 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-533c6d92-984d-4bc8-b314-b38dbd966327 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:59.242 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-8cb9451d-1212-4b34-864f-acc81ed42ffe _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:59.292 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-b7d2f524-2cd7-4912-81e5-fb9e4a34a294 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:12:59.293 18469 DEBUG nova.network.base_api [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:12:59.294 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: c587a03538314ff6b56156efd9dd7ff8 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:12:59.309 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c587a03538314ff6b56156efd9dd7ff8 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:12:59.310 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:12:59.311 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updated the network info_cache for instance _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5946
2019-03-29 10:13:00.312 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._instance_usage_audit run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:13:00.699 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rebooting_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:13:00.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_unconfirmed_resizes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:13:03.278 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 99faedf5b5f242db9749d068443a43e7 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:03.323 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 99faedf5b5f242db9749d068443a43e7 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:11.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_volume_usage run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:13:13.276 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: b7e72c9eec7c485fb48e5266fb350256 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:13.310 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b7e72c9eec7c485fb48e5266fb350256 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:14.697 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._check_instance_build_time run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:13:16.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager.update_available_resource run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:13:16.702 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: ab31f9f15c9243dc946201c5723eeeae exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:16.720 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ab31f9f15c9243dc946201c5723eeeae __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:16.723 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Auditing locally available compute resources for com58 (node: com58) update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:534
2019-03-29 10:13:16.739 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 75ac2d552b1f4060932fdad2aee2d75e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:16.774 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 75ac2d552b1f4060932fdad2aee2d75e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:16.776 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: ae4d375168f442308000d461e0e919a2 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:16.786 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ae4d375168f442308000d461e0e919a2 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:16.789 18469 DEBUG nova.virt.libvirt.driver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] skipping disk /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 (vda) as it is a volume _get_instance_disk_info /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:7082
2019-03-29 10:13:16.883 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Hypervisor: free VCPUs: 1 _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:655
2019-03-29 10:13:16.883 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Hypervisor/Node resource view: name=com58 free_ram=6869MB free_disk=45GB free_vcpus=1 pci_devices=[{"dev_id": "pci_0000_00_00_0", "product_id": "7190", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7190", "address": "0000:00:00.0"}, {"dev_id": "pci_0000_00_01_0", "product_id": "7191", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7191", "address": "0000:00:01.0"}, {"dev_id": "pci_0000_00_07_0", "product_id": "7110", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7110", "address": "0000:00:07.0"}, {"dev_id": "pci_0000_00_07_1", "product_id": "7111", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7111", "address": "0000:00:07.1"}, {"dev_id": "pci_0000_00_07_3", "product_id": "7113", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7113", "address": "0000:00:07.3"}, {"dev_id": "pci_0000_00_07_7", "product_id": "0740", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0740", "address": "0000:00:07.7"}, {"dev_id": "pci_0000_00_0f_0", "product_id": "0405", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0405", "address": "0000:00:0f.0"}, {"dev_id": "pci_0000_00_11_0", "product_id": "0790", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0790", "address": "0000:00:11.0"}, {"dev_id": "pci_0000_00_15_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.0"}, {"dev_id": "pci_0000_03_00_0", "product_id": "07c0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07c0", "address": "0000:03:00.0"}, {"dev_id": "pci_0000_00_15_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.1"}, {"dev_id": "pci_0000_00_15_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.2"}, {"dev_id": "pci_0000_00_15_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.3"}, {"dev_id": "pci_0000_00_15_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.4"}, {"dev_id": "pci_0000_00_15_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.5"}, {"dev_id": "pci_0000_00_15_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.6"}, {"dev_id": "pci_0000_00_15_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.7"}, {"dev_id": "pci_0000_00_16_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.0"}, {"dev_id": "pci_0000_0b_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:0b:00.0"}, {"dev_id": "pci_0000_00_16_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.1"}, {"dev_id": "pci_0000_00_16_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.2"}, {"dev_id": "pci_0000_00_16_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.3"}, {"dev_id": "pci_0000_00_16_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.4"}, {"dev_id": "pci_0000_00_16_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.5"}, {"dev_id": "pci_0000_00_16_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.6"}, {"dev_id": "pci_0000_00_16_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.7"}, {"dev_id": "pci_0000_00_17_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.0"}, {"dev_id": "pci_0000_13_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:13:00.0"}, {"dev_id": "pci_0000_00_17_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.1"}, {"dev_id": "pci_0000_00_17_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.2"}, {"dev_id": "pci_0000_00_17_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.3"}, {"dev_id": "pci_0000_00_17_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.4"}, {"dev_id": "pci_0000_00_17_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.5"}, {"dev_id": "pci_0000_00_17_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.6"}, {"dev_id": "pci_0000_00_17_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.7"}, {"dev_id": "pci_0000_00_18_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.0"}, {"dev_id": "pci_0000_00_18_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.1"}, {"dev_id": "pci_0000_00_18_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.2"}, {"dev_id": "pci_0000_00_18_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.3"}, {"dev_id": "pci_0000_00_18_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.4"}, {"dev_id": "pci_0000_00_18_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.5"}, {"dev_id": "pci_0000_00_18_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.6"}, {"dev_id": "pci_0000_00_18_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.7"}] _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:672
2019-03-29 10:13:16.884 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker._update_available_resource" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:13:16.889 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 4a3555a9093d4f0e96941f3c049f595b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:16.924 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4a3555a9093d4f0e96941f3c049f595b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:16.925 18469 DEBUG nova.scheduler.client.report [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:13:16.960 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: b1b688480725425782ed3be9aa2209e4 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:16.991 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b1b688480725425782ed3be9aa2209e4 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:16.998 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 4a570f8a78a248e78e8ea857a2496730 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:17.009 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4a570f8a78a248e78e8ea857a2496730 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:17.020 18469 DEBUG nova.scheduler.client.report [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Sending allocation for instance {'MEMORY_MB': 512, 'VCPU': 1} _allocate_for_instance /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:664
2019-03-29 10:13:17.068 18469 INFO nova.scheduler.client.report [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Submitted allocation for instance
2019-03-29 10:13:17.087 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: a1417ce621df4fea858bace6dc75b218 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:17.116 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a1417ce621df4fea858bace6dc75b218 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:17.117 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Total usable vcpus: 2, total allocated vcpus: 1 _report_final_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:688
2019-03-29 10:13:17.117 18469 INFO nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Final resource view: name=com58 phys_ram=8191MB used_ram=1024MB phys_disk=47GB used_disk=1GB total_vcpus=2 used_vcpus=1 pci_stats=[]
2019-03-29 10:13:17.120 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 187c9813a8064025aadf19746e591886 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:13:17.144 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 187c9813a8064025aadf19746e591886 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:13:17.146 18469 DEBUG nova.scheduler.client.report [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:13:17.173 18469 DEBUG nova.scheduler.client.report [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Updating our resource provider generation from 29 to 30 _get_inventory_and_update_provider_generation /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:445
2019-03-29 10:13:17.174 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Compute_service record updated for com58:com58 _update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:626
2019-03-29 10:13:17.174 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lock "compute_resources" released by "nova.compute.resource_tracker._update_available_resource" :: held 0.291s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282

