2019-03-29 10:48:07.434 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._poll_rescued_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:48:13.435 10556 DEBUG oslo_service.periodic_task [req-8886df63-1d00-4f26-87b4-d90c18c712a7 - - - - -] Running periodic task ComputeManager._poll_unconfirmed_resizes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:48:13.883 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: b3ef54524a0d40e5801ed5d151beed5b exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:13.910 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b3ef54524a0d40e5801ed5d151beed5b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:16.181 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: c21f3d5602c14ea9aab68112dd14bf9b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:48:16.187 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 54857b27bdb44ffb9041ae5580f7aa61 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:16.244 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 54857b27bdb44ffb9041ae5580f7aa61 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:16.246 10556 DEBUG oslo_concurrency.lockutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Acquired semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:48:16.246 10556 DEBUG nova.network.neutronv2.api [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:48:16.248 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: da69a697dbcd4bedbbcd03019fdebbf8 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:16.264 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: da69a697dbcd4bedbbcd03019fdebbf8 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:16.337 10556 DEBUG neutronclient.v2_0.client [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=bf4db636-f759-49ce-9cfd-f0702173b4b0 used request id req-ff288484-fa2c-4e94-bdad-e39700e9ff01 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:16.601 10556 DEBUG neutronclient.v2_0.client [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-d2607265-b4b7-4be3-87db-70c6fdb738b6 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:16.638 10556 DEBUG neutronclient.v2_0.client [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.8&port_id=9b4da570-b0d3-4a70-9634-379f880fe8ad used request id req-323ab868-ff26-46ac-b171-49edd2a6d537 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:16.725 10556 DEBUG neutronclient.v2_0.client [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-5a269f03-ed78-4597-9054-4a61e5d9cfbd _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:16.795 10556 DEBUG neutronclient.v2_0.client [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-62e13885-2ffd-4bf5-aaf4-fa9bf9c4050e _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:16.796 10556 DEBUG nova.network.base_api [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": true, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:48:16.797 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 809b783f13d3437286e861f092eef9f9 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:16.817 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 809b783f13d3437286e861f092eef9f9 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:16.818 10556 DEBUG oslo_concurrency.lockutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Releasing semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:48:16.819 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 350699fc28fc42e3a29c23b18a713cf8 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:16.851 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 350699fc28fc42e3a29c23b18a713cf8 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:16.856 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 02e9cf7a7220494e9d4ca985059517a3 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:16.997 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 02e9cf7a7220494e9d4ca985059517a3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:16.999 10556 WARNING nova.image.glance [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:48:17.002 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 79a01d4811ea4d93aa893988870f69e0 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:17.018 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 79a01d4811ea4d93aa893988870f69e0 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:17.019 10556 DEBUG nova.virt.libvirt.driver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Starting migrate_disk_and_power_off migrate_disk_and_power_off /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:7292
2019-03-29 10:48:17.022 10556 DEBUG nova.virt.libvirt.volume.remotefs [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Creating file /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/5b7975deafa74cc5bc292d8da28b5a80.tmp on remote host 172.30.126.58 create_file /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/remotefs.py:88
2019-03-29 10:48:17.023 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): ssh -o BatchMode=yes 172.30.126.58 touch /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/5b7975deafa74cc5bc292d8da28b5a80.tmp execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:48:17.352 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "ssh -o BatchMode=yes 172.30.126.58 touch /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/5b7975deafa74cc5bc292d8da28b5a80.tmp" returned: 1 in 0.330s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:48:17.353 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] u'ssh -o BatchMode=yes 172.30.126.58 touch /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/5b7975deafa74cc5bc292d8da28b5a80.tmp' failed. Not Retrying. execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:433
2019-03-29 10:48:17.353 10556 DEBUG nova.virt.libvirt.volume.remotefs [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Creating directory /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0 on remote host 172.30.126.58 create_dir /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/remotefs.py:100
2019-03-29 10:48:17.354 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): ssh -o BatchMode=yes 172.30.126.58 mkdir -p /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:48:17.678 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "ssh -o BatchMode=yes 172.30.126.58 mkdir -p /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0" returned: 0 in 0.324s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:48:17.682 10556 DEBUG nova.virt.libvirt.driver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Shutting down instance from state 1 _clean_shutdown /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:2520
2019-03-29 10:48:20.695 10556 INFO nova.virt.libvirt.driver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Instance shutdown successfully after 3 seconds.
2019-03-29 10:48:20.703 10556 INFO nova.virt.libvirt.driver [-] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Instance destroyed successfully.
2019-03-29 10:48:20.707 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:48:20.778 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk" returned: 0 in 0.071s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:48:20.779 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:48:20.846 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk" returned: 0 in 0.067s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:48:20.848 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): mv /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0 /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:48:20.864 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "mv /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0 /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize" returned: 0 in 0.017s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:48:20.865 10556 DEBUG nova.virt.libvirt.volume.remotefs [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Copying file /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize/disk to 172.30.126.58:/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk copy_file /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/remotefs.py:112
2019-03-29 10:48:20.866 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): scp -r /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize/disk 172.30.126.58:/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:48:21.265 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "scp -r /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize/disk 172.30.126.58:/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk" returned: 0 in 0.399s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:48:21.266 10556 DEBUG nova.virt.libvirt.volume.remotefs [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Copying file /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize/disk.config to 172.30.126.58:/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.config copy_file /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/remotefs.py:112
2019-03-29 10:48:21.266 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): scp -r /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize/disk.config 172.30.126.58:/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.config execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:48:21.629 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "scp -r /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize/disk.config 172.30.126.58:/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.config" returned: 0 in 0.363s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:48:21.630 10556 DEBUG nova.virt.libvirt.volume.remotefs [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Copying file /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize/disk.info to 172.30.126.58:/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.info copy_file /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/remotefs.py:112
2019-03-29 10:48:21.630 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): scp -r /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize/disk.info 172.30.126.58:/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.info execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:48:21.959 10556 DEBUG oslo_concurrency.processutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "scp -r /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize/disk.info 172.30.126.58:/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.info" returned: 0 in 0.329s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:48:21.960 10556 DEBUG os_brick.utils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> get_connector_properties: call u"{'execute': None, 'my_ip': '172.30.126.57', 'enforce_multipath': True, 'host': 'com57', 'root_helper': 'sudo nova-rootwrap /etc/nova/rootwrap.conf', 'multipath': False}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:48:21.963 10556 DEBUG oslo.privsep.daemon [-] privsep: request[99874768]: (3, 'os_brick.privileged.rootwrap.execute_root', ('cat', '/etc/iscsi/initiatorname.iscsi'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:21.963 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): cat /etc/iscsi/initiatorname.iscsi out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:21.966 10556 DEBUG oslo.privsep.daemon [-] CMD "cat /etc/iscsi/initiatorname.iscsi" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:21.966 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[99874768]: (4, ('InitiatorName=iqn.1994-05.com.redhat:4d12e79a68be\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:21.966 10556 DEBUG os_brick.initiator.linuxfc [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:48:21.967 10556 DEBUG os_brick.initiator.linuxfc [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:48:21.967 10556 DEBUG os_brick.utils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== get_connector_properties: return (6ms) {'initiator': u'iqn.1994-05.com.redhat:4d12e79a68be', 'ip': u'172.30.126.57', 'platform': u'x86_64', 'host': u'com57', 'do_local_attach': False, 'os_type': u'linux2', 'multipath': False} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:48:21.969 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 4b2f5c0a055342e2bfa5e2c9084d4624 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:22.000 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4b2f5c0a055342e2bfa5e2c9084d4624 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:22.004 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: f690ae82051c4091825e687452d963ed exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:22.121 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f690ae82051c4091825e687452d963ed __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:22.124 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 26798ae2caca45d79b0adc1da7aaeed5 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:22.135 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 26798ae2caca45d79b0adc1da7aaeed5 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:22.140 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: ad0a1d9ab1b04c05bd5fa9b138196512 exchange 'nova' topic 'compute.com58' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:22.141 10556 WARNING nova.image.glance [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:48:22.144 10556 DEBUG oslo_concurrency.lockutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" acquired by "nova.compute.manager._clear_events" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:48:22.144 10556 DEBUG oslo_concurrency.lockutils [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" released by "nova.compute.manager._clear_events" :: held 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:48:22.145 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-a9a625fa-0619-419f-9d54-eb87572575ea 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 271cae37957b4ee9aabc20f7c73688fc exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:22.170 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 271cae37957b4ee9aabc20f7c73688fc __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:22.980 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: f46093e0de114221976b788b77802470 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:48:22.982 10556 DEBUG nova.compute.manager [req-2e6be592-f4ad-4654-b466-d78a4d62384f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Received event network-vif-unplugged-9b4da570-b0d3-4a70-9634-379f880fe8ad external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:48:22.983 10556 DEBUG oslo_concurrency.lockutils [req-2e6be592-f4ad-4654-b466-d78a4d62384f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:48:22.983 10556 DEBUG nova.compute.manager [req-2e6be592-f4ad-4654-b466-d78a4d62384f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:48:22.983 10556 DEBUG oslo_concurrency.lockutils [req-2e6be592-f4ad-4654-b466-d78a4d62384f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:48:22.984 10556 DEBUG nova.compute.manager [req-2e6be592-f4ad-4654-b466-d78a4d62384f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] No waiting events found dispatching network-vif-unplugged-9b4da570-b0d3-4a70-9634-379f880fe8ad pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:48:22.984 10556 WARNING nova.compute.manager [req-2e6be592-f4ad-4654-b466-d78a4d62384f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Received unexpected event network-vif-unplugged-9b4da570-b0d3-4a70-9634-379f880fe8ad for instance
2019-03-29 10:48:23.883 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 0d4f152b7de949c7808a4033e50dbe05 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:23.970 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0d4f152b7de949c7808a4033e50dbe05 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:25.059 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 38d2a92b7cfb48769e10e94ee025d353 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:48:25.061 10556 DEBUG nova.compute.manager [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Received event network-changed external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:48:25.062 10556 DEBUG oslo_concurrency.lockutils [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Acquired semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:48:25.062 10556 DEBUG nova.network.neutronv2.api [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:48:25.063 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: 0aa3afb0e3f144348c0288eec86eaeef exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:25.074 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0aa3afb0e3f144348c0288eec86eaeef __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:25.173 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: ee773de0039948a985f001ed615fb232 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:48:25.175 10556 DEBUG nova.compute.manager [req-9a439bc0-54b2-4926-98ea-cdcde33e6fb4 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Received event network-vif-plugged-9b4da570-b0d3-4a70-9634-379f880fe8ad external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:48:25.175 10556 DEBUG oslo_concurrency.lockutils [req-9a439bc0-54b2-4926-98ea-cdcde33e6fb4 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:48:25.176 10556 DEBUG nova.compute.manager [req-9a439bc0-54b2-4926-98ea-cdcde33e6fb4 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:48:25.176 10556 DEBUG oslo_concurrency.lockutils [req-9a439bc0-54b2-4926-98ea-cdcde33e6fb4 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:48:25.176 10556 DEBUG nova.compute.manager [req-9a439bc0-54b2-4926-98ea-cdcde33e6fb4 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] No waiting events found dispatching network-vif-plugged-9b4da570-b0d3-4a70-9634-379f880fe8ad pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:48:25.177 10556 WARNING nova.compute.manager [req-9a439bc0-54b2-4926-98ea-cdcde33e6fb4 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Received unexpected event network-vif-plugged-9b4da570-b0d3-4a70-9634-379f880fe8ad for instance
2019-03-29 10:48:25.187 10556 DEBUG neutronclient.v2_0.client [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=bf4db636-f759-49ce-9cfd-f0702173b4b0 used request id req-fa58cdb2-7372-4b14-9402-69f216164f6b _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:25.405 10556 DEBUG neutronclient.v2_0.client [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-3e8c1f49-9f59-4989-9ee1-8623691ae25f _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:25.446 10556 DEBUG neutronclient.v2_0.client [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.8&port_id=9b4da570-b0d3-4a70-9634-379f880fe8ad used request id req-f6e3f5e4-3701-4ebd-aba2-d1123dfe1a73 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:25.547 10556 DEBUG neutronclient.v2_0.client [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-b0e5caff-146c-46bb-b920-753623e8e640 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:25.590 10556 DEBUG neutronclient.v2_0.client [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-80ec3cd2-2af6-499d-9031-95a5cf416305 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:25.590 10556 DEBUG nova.network.base_api [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": false, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:48:25.591 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: 60bb4fa13c0e454db52ed18c06916d99 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:25.603 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 60bb4fa13c0e454db52ed18c06916d99 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:25.604 10556 DEBUG oslo_concurrency.lockutils [req-6d2714aa-9ac1-46a2-b65f-e0b56d3df6aa 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Releasing semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:48:27.260 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 9316206fd9d44456b32fad78f13f3d7f __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:48:27.265 10556 DEBUG nova.compute.manager [req-51dd9a2c-88d3-4d67-8a17-95d1e34f7b19 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Received event network-vif-plugged-9b4da570-b0d3-4a70-9634-379f880fe8ad external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:48:27.266 10556 DEBUG oslo_concurrency.lockutils [req-51dd9a2c-88d3-4d67-8a17-95d1e34f7b19 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:48:27.266 10556 DEBUG nova.compute.manager [req-51dd9a2c-88d3-4d67-8a17-95d1e34f7b19 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:350
2019-03-29 10:48:27.266 10556 DEBUG oslo_concurrency.lockutils [req-51dd9a2c-88d3-4d67-8a17-95d1e34f7b19 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:48:27.267 10556 DEBUG nova.compute.manager [req-51dd9a2c-88d3-4d67-8a17-95d1e34f7b19 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] No waiting events found dispatching network-vif-plugged-9b4da570-b0d3-4a70-9634-379f880fe8ad pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:366
2019-03-29 10:48:27.267 10556 WARNING nova.compute.manager [req-51dd9a2c-88d3-4d67-8a17-95d1e34f7b19 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Received unexpected event network-vif-plugged-9b4da570-b0d3-4a70-9634-379f880fe8ad for instance










2019-03-29 10:48:33.884 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: b9e8ba841d044c36897a576234eb69bc exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:33.909 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b9e8ba841d044c36897a576234eb69bc __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:35.582 10556 DEBUG nova.virt.driver [-] Emitting event <LifecycleEvent: 1553827700.58, bf4db636-f759-49ce-9cfd-f0702173b4b0 => Stopped> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:48:35.583 10556 INFO nova.compute.manager [-] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] VM Stopped (Lifecycle Event)
2019-03-29 10:48:35.584 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-5ccd0917-8c29-468b-ad25-011c29e77d95 - - - - -] CALL msg_id: 29ce3bef2bb9403a9a7bdc357e618aee exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:35.627 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 29ce3bef2bb9403a9a7bdc357e618aee __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:35.629 10556 DEBUG nova.compute.manager [req-5ccd0917-8c29-468b-ad25-011c29e77d95 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:48:35.632 10556 DEBUG nova.compute.manager [req-5ccd0917-8c29-468b-ad25-011c29e77d95 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Synchronizing instance power state after lifecycle event "Stopped"; current vm_state: resized, current task_state: None, current DB power_state: 1, VM power_state: 4 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:48:35.633 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-5ccd0917-8c29-468b-ad25-011c29e77d95 - - - - -] CALL msg_id: e69ffe69bc3944de93e72f65775fe785 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:35.670 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e69ffe69bc3944de93e72f65775fe785 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:35.671 10556 INFO nova.compute.manager [req-5ccd0917-8c29-468b-ad25-011c29e77d95 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] During the sync_power process the instance has moved from host com58 to host com57
2019-03-29 10:48:35.980 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: bf7bbcc65cd84d8a873a8f453b0092c5 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:48:35.986 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 541e038dca9641ee8187cb52ab8f59c4 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:36.018 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 541e038dca9641ee8187cb52ab8f59c4 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:36.020 10556 DEBUG oslo_concurrency.lockutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0" acquired by "nova.compute.manager.do_confirm_resize" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:48:36.020 10556 DEBUG nova.compute.manager [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Going to confirm migration 56 do_confirm_resize /usr/lib/python2.7/site-packages/nova/compute/manager.py:3460
2019-03-29 10:48:36.022 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: df4266ebb1864a00a6eae81847b3a016 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:36.031 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: df4266ebb1864a00a6eae81847b3a016 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:36.033 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 1a798f66092a4526a41f0df12deb82f8 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:36.086 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 1a798f66092a4526a41f0df12deb82f8 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:36.088 10556 WARNING nova.image.glance [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:48:36.091 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: b46b26b4e52c4d539b5143b6a81221a9 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:36.190 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b46b26b4e52c4d539b5143b6a81221a9 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:36.255 10556 DEBUG neutronclient.v2_0.client [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&binding%3Ahost_id=com58&device_id=bf4db636-f759-49ce-9cfd-f0702173b4b0 used request id req-d968d9a9-6f54-4dbc-85d7-e4d52686d577 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:36.256 10556 DEBUG oslo_concurrency.lockutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Acquired semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:48:36.256 10556 DEBUG nova.network.neutronv2.api [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:48:36.256 10556 DEBUG nova.objects.instance [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'info_cache' on Instance uuid bf4db636-f759-49ce-9cfd-f0702173b4b0 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:48:36.258 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 2a65fef1332c458aadd3f472c64678bc exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:36.310 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 2a65fef1332c458aadd3f472c64678bc __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:36.312 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: a824b6516f5a4ee0b37180735964cd69 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:36.344 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a824b6516f5a4ee0b37180735964cd69 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:36.487 10556 DEBUG neutronclient.v2_0.client [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=bf4db636-f759-49ce-9cfd-f0702173b4b0 used request id req-e62d1eb4-40a6-4e37-b963-3ebff336864e _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:36.747 10556 DEBUG neutronclient.v2_0.client [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-ca9b29f5-5ea5-4f68-82d3-0724c9215600 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:36.771 10556 DEBUG neutronclient.v2_0.client [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.8&port_id=9b4da570-b0d3-4a70-9634-379f880fe8ad used request id req-fa4c5157-6989-497d-8542-b3c56bae34e4 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:36.910 10556 DEBUG neutronclient.v2_0.client [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-0a9f0ace-04a3-499f-89b8-75ca9c3c8600 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:36.958 10556 DEBUG neutronclient.v2_0.client [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-e5ed1acb-9234-4e50-a5b6-82a6af43afc2 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:48:36.959 10556 DEBUG nova.network.base_api [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": true, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:48:36.960 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 3de61d34add04440bd8146e8a342d2d2 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:36.977 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 3de61d34add04440bd8146e8a342d2d2 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:36.978 10556 DEBUG oslo_concurrency.lockutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Releasing semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:48:36.978 10556 DEBUG oslo_concurrency.processutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): rm -rf /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:48:36.994 10556 DEBUG oslo_concurrency.processutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "rm -rf /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0_resize" returned: 0 in 0.016s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:48:36.996 10556 DEBUG oslo_concurrency.lockutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.info" acquired by "nova.virt.libvirt.imagebackend.write_to_disk_info_file" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:48:36.997 10556 DEBUG oslo_concurrency.lockutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.info" released by "nova.virt.libvirt.imagebackend.write_to_disk_info_file" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:48:36.999 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 3a926772f6bc48ccabe1c51faada63ba exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:37.015 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 3a926772f6bc48ccabe1c51faada63ba __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:37.021 10556 DEBUG nova.virt.libvirt.vif [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=True,config_drive='True',created_at=2019-03-29T02:42:13Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=<?>,disable_terminate=False,display_description='vm002',display_name='vm002',ec2_ids=<?>,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm002',id=25,image_ref='40f27f13-d552-4f7e-ae5d-2b85b126c85e',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=<?>,launch_index=0,launched_at=2019-03-29T02:48:24Z,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=<?>,old_flavor=None,os_type=None,pci_devices=<?>,pci_requests=<?>,power_state=1,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-efd35roq',root_device_name='/dev/vda',root_gb=1,security_groups=<?>,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',clean_attempts='1',image_architecture='x86_64',image_base_image_ref='40f27f13-d552-4f7e-ae5d-2b85b126c85e',image_container_format='bare',image_disk_format='qcow2',image_min_disk='1',image_min_ram='0'},tags=<?>,task_state=None,terminated_at=None,updated_at=2019-03-29T02:48:24Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=bf4db636-f759-49ce-9cfd-f0702173b4b0,vcpu_model=<?>,vcpus=1,vm_mode=None,vm_state='resized') vif={"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": true, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null} unplug /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:966
2019-03-29 10:48:37.021 10556 DEBUG nova.network.os_vif_util [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": true, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:48:37.022 10556 DEBUG nova.network.os_vif_util [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=True,address=fa:16:3e:82:63:d2,bridge_name='qbr9b4da570-b0',has_traffic_filtering=True,id=9b4da570-b0d3-4a70-9634-379f880fe8ad,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tap9b4da570-b0') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:48:37.023 10556 DEBUG os_vif [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Unplugging vif VIFBridge(active=True,address=fa:16:3e:82:63:d2,bridge_name='qbr9b4da570-b0',has_traffic_filtering=True,id=9b4da570-b0d3-4a70-9634-379f880fe8ad,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tap9b4da570-b0') unplug /usr/lib/python2.7/site-packages/os_vif/__init__.py:112
2019-03-29 10:48:37.024 10556 DEBUG oslo.privsep.daemon [-] privsep: request[99873168]: (3, 'vif_plug_ovs.linux_net.delete_bridge', (u'qbr9b4da570-b0', 'qvb9b4da570-b0'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.025 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl delif qbr9b4da570-b0 qvb9b4da570-b0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.037 10556 DEBUG oslo.privsep.daemon [-] CMD "brctl delif qbr9b4da570-b0 qvb9b4da570-b0" returned: 0 in 0.011s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.037 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qbr9b4da570-b0 down out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.043 10556 DEBUG oslo.privsep.daemon [-] CMD "ip link set qbr9b4da570-b0 down" returned: 0 in 0.007s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.044 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl delbr qbr9b4da570-b0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.058 10556 DEBUG oslo.privsep.daemon [-] CMD "brctl delbr qbr9b4da570-b0" returned: 0 in 0.014s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.058 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[99873168]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.060 10556 DEBUG oslo.privsep.daemon [-] privsep: request[99873168]: (3, 'vif_plug_ovs.linux_net.delete_ovs_vif_port', (u'br-int', 'qvo9b4da570-b0'), {'timeout': 120}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.060 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl --timeout=120 -- --if-exists del-port br-int qvo9b4da570-b0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.073 10556 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl --timeout=120 -- --if-exists del-port br-int qvo9b4da570-b0" returned: 0 in 0.013s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.074 10556 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link delete qvo9b4da570-b0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.092 10556 DEBUG oslo.privsep.daemon [-] CMD "ip link delete qvo9b4da570-b0" returned: 0 in 0.019s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.093 10556 DEBUG oslo.privsep.daemon [-] Net device removed: 'qvo9b4da570-b0' out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.093 10556 DEBUG oslo.privsep.daemon [-] privsep: reply[99873168]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:48:37.093 10556 INFO os_vif [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Successfully unplugged vif VIFBridge(active=True,address=fa:16:3e:82:63:d2,bridge_name='qbr9b4da570-b0',has_traffic_filtering=True,id=9b4da570-b0d3-4a70-9634-379f880fe8ad,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tap9b4da570-b0')
2019-03-29 10:48:37.095 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 6d7fb562de334f4db3ac966cacb3f579 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:37.144 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 6d7fb562de334f4db3ac966cacb3f579 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:37.146 10556 DEBUG oslo_concurrency.lockutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.drop_move_claim" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:48:37.147 10556 DEBUG oslo_concurrency.lockutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.drop_move_claim" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:48:37.150 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 855d8e56e38c467d864285c7cc4d33f9 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:37.194 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 855d8e56e38c467d864285c7cc4d33f9 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:37.198 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 9b44093ef6ab4aeeb07f394c0cfff11c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:37.313 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 9b44093ef6ab4aeeb07f394c0cfff11c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:37.315 10556 WARNING nova.image.glance [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:48:37.317 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: ad06edc9a4714110824278780c9254bf exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:37.324 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ad06edc9a4714110824278780c9254bf __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:37.324 10556 DEBUG oslo_concurrency.lockutils [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0" released by "nova.compute.manager.do_confirm_resize" :: held 1.305s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:48:37.325 10556 DEBUG oslo_messaging._drivers.amqpdriver [req-2fff1452-c8cb-49bc-96c3-8d4d2594985a 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 2e0e7d96437e472e905c34a991552245 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:37.385 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 2e0e7d96437e472e905c34a991552245 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:48:43.883 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 96f488f0a45344ccb305e62614357fd8 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:48:43.912 10556 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 96f488f0a45344ccb305e62614357fd8 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407

