
2019-03-29 10:41:56.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rescued_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:42:03.349 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: f81c6605a37247a08428df03884cd73d exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:03.384 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f81c6605a37247a08428df03884cd73d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:13.347 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 4a83b32170554467aa42a1c834412e27 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:13.395 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4a83b32170554467aa42a1c834412e27 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:13.572 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: d5eab68b3eed456ea07b67b397ccb930 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:42:13.579 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0" acquired by "nova.compute.manager._locked_do_build_and_run_instance" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:42:13.580 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: e4ab53ecfef645c39bd26056350d3b7e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:13.617 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e4ab53ecfef645c39bd26056350d3b7e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:13.618 18469 DEBUG nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Starting instance... _do_build_and_run_instance /usr/lib/python2.7/site-packages/nova/compute/manager.py:1759
2019-03-29 10:42:13.621 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 4f3642e9106446dfb590d50b64a68c20 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:13.783 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4f3642e9106446dfb590d50b64a68c20 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:13.784 18469 WARNING nova.image.glance [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:42:13.787 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.instance_claim" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:42:13.789 18469 DEBUG nova.compute.resource_tracker [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Memory overhead for 512 MB instance; 0 MB instance_claim /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:147
2019-03-29 10:42:13.789 18469 DEBUG nova.compute.resource_tracker [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Disk overhead for 1 GB instance; 0 GB instance_claim /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:150
2019-03-29 10:42:13.790 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: eaaaf4b88731474cafbfbfb514721d94 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:13.806 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: eaaaf4b88731474cafbfbfb514721d94 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:13.809 18469 INFO nova.compute.claims [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Attempting claim: memory 512 MB, disk 1 GB, vcpus 1 CPU
2019-03-29 10:42:13.810 18469 INFO nova.compute.claims [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Total memory: 8191 MB, used: 512.00 MB
2019-03-29 10:42:13.810 18469 INFO nova.compute.claims [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] memory limit: 12286.50 MB, free: 11774.50 MB
2019-03-29 10:42:13.810 18469 INFO nova.compute.claims [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Total disk: 47 GB, used: 0.00 GB
2019-03-29 10:42:13.811 18469 INFO nova.compute.claims [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] disk limit: 47.00 GB, free: 47.00 GB
2019-03-29 10:42:13.811 18469 INFO nova.compute.claims [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Total vcpu: 2 VCPU, used: 0.00 VCPU
2019-03-29 10:42:13.811 18469 INFO nova.compute.claims [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] vcpu limit: 32.00 VCPU, free: 32.00 VCPU
2019-03-29 10:42:13.812 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Require both a host and instance NUMA topology to fit instance on host. numa_fit_instance_to_host /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1328
2019-03-29 10:42:13.812 18469 INFO nova.compute.claims [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Claim successful
2019-03-29 10:42:13.815 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 287203809f204bbf96a41e502019953f exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:13.948 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 287203809f204bbf96a41e502019953f __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:13.952 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 72899ed3ce00401c939c8c436b5ce699 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:13.973 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 72899ed3ce00401c939c8c436b5ce699 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:13.984 18469 DEBUG nova.scheduler.client.report [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Sending allocation for instance {'MEMORY_MB': 512, 'VCPU': 1, 'DISK_GB': 1} _allocate_for_instance /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:664
2019-03-29 10:42:14.062 18469 INFO nova.scheduler.client.report [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Submitted allocation for instance
2019-03-29 10:42:14.068 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 77d3c8191f8e440ba7bc503476557c0d exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:14.114 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 77d3c8191f8e440ba7bc503476557c0d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:14.116 18469 DEBUG nova.scheduler.client.report [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:42:14.151 18469 DEBUG nova.scheduler.client.report [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Updating our resource provider generation from 31 to 32 _get_inventory_and_update_provider_generation /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:445
2019-03-29 10:42:14.152 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.instance_claim" :: held 0.365s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:42:14.153 18469 DEBUG nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Start building networks asynchronously for instance. _build_resources /usr/lib/python2.7/site-packages/nova/compute/manager.py:2074
2019-03-29 10:42:14.159 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 3ef49408401e439eb2d07ac1a7a705cd exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:14.310 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 3ef49408401e439eb2d07ac1a7a705cd __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:14.311 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.update_usage" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:42:14.317 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 19a67437bb3740dd949dc4e732b21d6d exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:14.363 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 19a67437bb3740dd949dc4e732b21d6d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:14.364 18469 DEBUG nova.scheduler.client.report [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:42:14.392 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.update_usage" :: held 0.081s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:42:14.395 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 756200247432449a88deb9cd60410cf5 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:14.397 18469 DEBUG nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Allocating IP information in the background. _allocate_network_async /usr/lib/python2.7/site-packages/nova/compute/manager.py:1390
2019-03-29 10:42:14.398 18469 DEBUG nova.network.neutronv2.api [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] allocate_for_instance() allocate_for_instance /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:840
2019-03-29 10:42:14.462 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 756200247432449a88deb9cd60410cf5 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:14.464 18469 DEBUG nova.block_device [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] block_device_list [] volume_in_mapping /usr/lib/python2.7/site-packages/nova/block_device.py:591
2019-03-29 10:42:14.464 18469 DEBUG nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Start building block device mappings for instance. _build_resources /usr/lib/python2.7/site-packages/nova/compute/manager.py:2100
2019-03-29 10:42:14.468 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: ce4e052eded44e15b4dd038c0c034323 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:14.512 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-f8f98642-d612-4a49-96e7-5b3de75f8a9f _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:14.587 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/security-groups.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917 used request id req-ae02881e-9bb1-465c-8580-25c7370ffc05 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:14.597 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ce4e052eded44e15b4dd038c0c034323 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:14.601 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 9926968a105d410db61f7444cdf987a7 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:14.746 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 9926968a105d410db61f7444cdf987a7 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:14.749 18469 DEBUG nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Start spawning the instance on the hypervisor. _build_and_run_instance /usr/lib/python2.7/site-packages/nova/compute/manager.py:1933
2019-03-29 10:42:14.750 18469 DEBUG nova.block_device [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] block_device_list [] volume_in_mapping /usr/lib/python2.7/site-packages/nova/block_device.py:591
2019-03-29 10:42:14.751 18469 INFO nova.virt.libvirt.driver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Creating image
2019-03-29 10:42:14.753 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.info" acquired by "nova.virt.libvirt.imagebackend.write_to_disk_info_file" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:42:14.754 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.info" released by "nova.virt.libvirt.imagebackend.write_to_disk_info_file" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:42:14.754 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): sudo nova-rootwrap /etc/nova/rootwrap.conf touch -c /var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:42:15.023 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "sudo nova-rootwrap /etc/nova/rootwrap.conf touch -c /var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa" returned: 0 in 0.268s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:42:15.024 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:42:15.074 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa" returned: 0 in 0.050s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:42:15.075 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "a46e846ccb196999d39deb2e7f0969149a3ca0fa" acquired by "nova.virt.libvirt.imagebackend.copy_qcow2_image" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:42:15.075 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:42:15.125 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa" returned: 0 in 0.050s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:42:15.127 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): qemu-img create -f qcow2 -o backing_file=/var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:42:15.213 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "qemu-img create -f qcow2 -o backing_file=/var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk" returned: 0 in 0.085s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:42:15.213 18469 DEBUG nova.virt.disk.api [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Checking if we can resize image /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk. size=1073741824 can_resize_image /usr/lib/python2.7/site-packages/nova/virt/disk/api.py:214
2019-03-29 10:42:15.214 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:42:15.266 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk" returned: 0 in 0.052s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:42:15.268 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): qemu-img resize /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk 1073741824 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:42:15.338 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "qemu-img resize /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk 1073741824" returned: 0 in 0.070s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:42:15.339 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "a46e846ccb196999d39deb2e7f0969149a3ca0fa" released by "nova.virt.libvirt.imagebackend.copy_qcow2_image" :: held 0.264s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:42:15.339 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:42:15.390 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/_base/a46e846ccb196999d39deb2e7f0969149a3ca0fa" returned: 0 in 0.051s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:42:15.392 18469 DEBUG nova.virt.disk.api [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Checking if we can resize image /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk. size=1073741824 can_resize_image /usr/lib/python2.7/site-packages/nova/virt/disk/api.py:214
2019-03-29 10:42:15.393 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:42:15.445 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "/usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=8 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk" returned: 0 in 0.051s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:42:15.446 18469 DEBUG nova.virt.disk.api [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Cannot resize image /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk to a smaller size. can_resize_image /usr/lib/python2.7/site-packages/nova/virt/disk/api.py:220
2019-03-29 10:42:15.447 18469 DEBUG nova.virt.libvirt.driver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Ensure instance console log exists: /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/console.log _ensure_console_log_for_instance /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:3019
2019-03-29 10:42:15.666 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to neutron for http://172.30.126.56:9696/v2.0/ports.json used request id req-83a0be9c-69e2-4609-a531-d8ad9bf47319 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:15.667 18469 DEBUG nova.network.neutronv2.api [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Successfully created port: 9b4da570-b0d3-4a70-9634-379f880fe8ad _create_port_minimal /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:407
2019-03-29 10:42:15.698 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._sync_scheduler_instance_info run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:42:15.701 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: ac8ea543136c4a248bf1310e63219eaa exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:15.739 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ac8ea543136c4a248bf1310e63219eaa __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:15.742 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CAST unique_id: b9658b8cb58946e097e7ec5402bbf175 FANOUT topic 'scheduler' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:539
2019-03-29 10:42:16.868 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] PUT call to neutron for http://172.30.126.56:9696/v2.0/ports/9b4da570-b0d3-4a70-9634-379f880fe8ad.json used request id req-5e3e71a8-5a60-4ee4-aa5c-fd43381ca499 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:16.868 18469 DEBUG nova.network.neutronv2.api [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Successfully updated port: 9b4da570-b0d3-4a70-9634-379f880fe8ad _update_port /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:444
2019-03-29 10:42:16.870 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: d381a0e322bb4788b55f64294c1c638c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:16.919 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: d381a0e322bb4788b55f64294c1c638c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:16.921 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Acquired semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:42:16.921 18469 DEBUG nova.network.neutronv2.api [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:42:16.923 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 4e6427924e834518a8b10d05cea18838 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:16.931 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 43a5445763ec46699e8425ea565a52ef __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:42:16.933 18469 DEBUG nova.compute.manager [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Received event network-changed external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:42:16.934 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4e6427924e834518a8b10d05cea18838 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:17.001 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=bf4db636-f759-49ce-9cfd-f0702173b4b0 used request id req-43f51bf5-c949-4bad-ade1-7a874265ef66 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.002 18469 DEBUG nova.network.neutronv2.api [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Instance cache missing network info. _get_preexisting_port_ids /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:2194
2019-03-29 10:42:17.028 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.8&port_id=9b4da570-b0d3-4a70-9634-379f880fe8ad used request id req-c42f7214-14cb-469b-bf6a-d5d808d9ed66 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.096 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-b7e06018-7fd4-4cc6-b65c-27641c69ed3b _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.154 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-475d89df-fda1-4094-9511-c031068bf19b _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.155 18469 DEBUG nova.network.base_api [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": false, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:42:17.157 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 432d6c5e043443cc956b896d4014193c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:17.195 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 432d6c5e043443cc956b896d4014193c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:17.196 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Releasing semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:42:17.197 18469 DEBUG nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Instance network_info: |[{"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": false, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null}]| _allocate_network_async /usr/lib/python2.7/site-packages/nova/compute/manager.py:1405
2019-03-29 10:42:17.198 18469 DEBUG oslo_concurrency.lockutils [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Acquired semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:42:17.199 18469 DEBUG nova.network.neutronv2.api [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:42:17.201 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: f32ba187c8b24cb1b61a10ff9379d873 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:17.203 18469 DEBUG nova.virt.libvirt.driver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Start _get_guest_xml network_info=[{"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": false, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null}] disk_info={'disk_bus': 'virtio', 'cdrom_bus': 'ide', 'mapping': {'disk.config': {'bus': 'ide', 'type': 'cdrom', 'dev': 'hda'}, 'disk': {'bus': 'virtio', 'boot_index': '1', 'type': 'disk', 'dev': u'vda'}, 'root': {'bus': 'virtio', 'boot_index': '1', 'type': 'disk', 'dev': u'vda'}}} image_meta=ImageMeta(checksum='ee1eca47dc88f4879d8a229cc70a07c6',container_format='bare',created_at=2019-03-26T03:02:28Z,direct_url=<?>,disk_format='qcow2',id=40f27f13-d552-4f7e-ae5d-2b85b126c85e,min_disk=0,min_ram=0,name='cirros',owner='d4bbd972ca1b463ba028ccd1df983917',properties=ImageMetaProps,protected=<?>,size=13287936,status='active',tags=<?>,updated_at=2019-03-26T03:02:28Z,virtual_size=<?>,visibility=<?>) rescue=None block_device_info={'swap': None, 'root_device_name': u'/dev/vda', 'ephemerals': [], 'block_device_mapping': []} _get_guest_xml /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:4971
2019-03-29 10:42:17.214 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Getting desirable topologies for flavor Flavor(created_at=2019-03-25T11:43:43Z,deleted=False,deleted_at=None,disabled=False,ephemeral_gb=0,extra_specs={},flavorid='1',id=1,is_public=True,memory_mb=512,name='m1.tiny',projects=<?>,root_gb=1,rxtx_factor=1.0,swap=0,updated_at=None,vcpu_weight=0,vcpus=1) and image_meta ImageMeta(checksum='ee1eca47dc88f4879d8a229cc70a07c6',container_format='bare',created_at=2019-03-26T03:02:28Z,direct_url=<?>,disk_format='qcow2',id=40f27f13-d552-4f7e-ae5d-2b85b126c85e,min_disk=0,min_ram=0,name='cirros',owner='d4bbd972ca1b463ba028ccd1df983917',properties=ImageMetaProps,protected=<?>,size=13287936,status='active',tags=<?>,updated_at=2019-03-26T03:02:28Z,virtual_size=<?>,visibility=<?>), allow threads: True _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:560
2019-03-29 10:42:17.215 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flavor limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:306
2019-03-29 10:42:17.215 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Image limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:317
2019-03-29 10:42:17.216 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flavor pref -1:-1:-1 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:340
2019-03-29 10:42:17.216 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Image pref -1:-1:-1 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:359
2019-03-29 10:42:17.216 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Chosen -1:-1:-1 limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:388
2019-03-29 10:42:17.217 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Topology preferred VirtCPUTopology(cores=-1,sockets=-1,threads=-1), maximum VirtCPUTopology(cores=65536,sockets=65536,threads=65536) _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:564
2019-03-29 10:42:17.217 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Build topologies for 1 vcpu(s) 1:1:1 _get_possible_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:427
2019-03-29 10:42:17.217 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Got 1 possible topologies _get_possible_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:454
2019-03-29 10:42:17.218 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Possible topologies [VirtCPUTopology(cores=1,sockets=1,threads=1)] _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:569
2019-03-29 10:42:17.218 18469 DEBUG nova.virt.hardware [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Sorted desired topologies [VirtCPUTopology(cores=1,sockets=1,threads=1)] _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:594
2019-03-29 10:42:17.220 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f32ba187c8b24cb1b61a10ff9379d873 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:17.229 18469 DEBUG nova.virt.libvirt.vif [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=False,config_drive='True',created_at=2019-03-29T02:42:13Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=None,disable_terminate=False,display_description='vm002',display_name='vm002',ec2_ids=EC2Ids,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm002',id=25,image_ref='40f27f13-d552-4f7e-ae5d-2b85b126c85e',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=KeyPairList,launch_index=0,launched_at=None,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=None,old_flavor=None,os_type=None,pci_devices=<?>,pci_requests=InstancePCIRequests,power_state=0,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-efd35roq',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',image_architecture='x86_64',image_base_image_ref='40f27f13-d552-4f7e-ae5d-2b85b126c85e',image_container_format='bare',image_disk_format='qcow2',image_min_disk='1',image_min_ram='0',network_allocated='True'},tags=<?>,task_state='spawning',terminated_at=None,updated_at=2019-03-29T02:42:15Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=bf4db636-f759-49ce-9cfd-f0702173b4b0,vcpu_model=VirtCPUModel,vcpus=1,vm_mode=None,vm_state='building') vif={"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": false, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null} virt_type=qemu get_config /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:529
2019-03-29 10:42:17.230 18469 DEBUG nova.network.os_vif_util [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": false, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:42:17.231 18469 DEBUG nova.network.os_vif_util [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=False,address=fa:16:3e:82:63:d2,bridge_name='qbr9b4da570-b0',has_traffic_filtering=True,id=9b4da570-b0d3-4a70-9634-379f880fe8ad,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tap9b4da570-b0') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:42:17.237 18469 DEBUG nova.objects.instance [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'pci_devices' on Instance uuid bf4db636-f759-49ce-9cfd-f0702173b4b0 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:42:17.238 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: e974619e39604027b468d1492048b3d6 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:17.249 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: e974619e39604027b468d1492048b3d6 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:17.251 18469 DEBUG nova.virt.libvirt.driver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] End _get_guest_xml xml=<domain type="qemu">
  <uuid>bf4db636-f759-49ce-9cfd-f0702173b4b0</uuid>
  <name>instance-00000019</name>
  <memory>524288</memory>
  <vcpu>1</vcpu>
  <metadata>
    <nova:instance xmlns:nova="http://openstack.org/xmlns/libvirt/nova/1.0">
      <nova:package version="0.0.0-1.el7.ceos"/>
      <nova:name>vm002</nova:name>
      <nova:creationTime>2019-03-29 02:42:17</nova:creationTime>
      <nova:flavor name="m1.tiny">
        <nova:memory>512</nova:memory>
        <nova:disk>1</nova:disk>
        <nova:swap>0</nova:swap>
        <nova:ephemeral>0</nova:ephemeral>
        <nova:vcpus>1</nova:vcpus>
      </nova:flavor>
      <nova:owner>
        <nova:user uuid="9e9e53917dda421083fa6af425c6bfbf">admin</nova:user>
        <nova:project uuid="d4bbd972ca1b463ba028ccd1df983917">admin</nova:project>
      </nova:owner>
      <nova:root type="image" uuid="40f27f13-d552-4f7e-ae5d-2b85b126c85e"/>
    </nova:instance>
  </metadata>
  <sysinfo type="smbios">
    <system>
      <entry name="manufacturer">RDO</entry>
      <entry name="product">OpenStack Compute</entry>
      <entry name="version">0.0.0-1.el7.ceos</entry>
      <entry name="serial">b72f0c91-de47-47b5-9c10-43dfb0050cac</entry>
      <entry name="uuid">bf4db636-f759-49ce-9cfd-f0702173b4b0</entry>
      <entry name="family">Virtual Machine</entry>
    </system>
  </sysinfo>
  <os>
    <type>hvm</type>
    <boot dev="hd"/>
    <smbios mode="sysinfo"/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cputune>
    <shares>1024</shares>
  </cputune>
  <clock offset="utc"/>
  <cpu match="exact">
    <topology sockets="1" cores="1" threads="1"/>
  </cpu>
  <devices>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2" cache="none"/>
      <source file="/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk"/>
      <target bus="virtio" dev="vda"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw" cache="none"/>
      <source file="/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.config"/>
      <target bus="ide" dev="hda"/>
    </disk>
    <interface type="bridge">
      <mac address="fa:16:3e:82:63:d2"/>
      <model type="virtio"/>
      <driver name="qemu"/>
      <source bridge="qbr9b4da570-b0"/>
      <target dev="tap9b4da570-b0"/>
    </interface>
    <serial type="pty">
      <log file="/var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/console.log" append="off"/>
    </serial>
    <input type="tablet" bus="usb"/>
    <graphics type="vnc" autoport="yes" keymap="en-us" listen="0.0.0.0"/>
    <video>
      <model type="cirrus"/>
    </video>
    <memballoon model="virtio">
      <stats period="10"/>
    </memballoon>
  </devices>
</domain>
 _get_guest_xml /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:4978
2019-03-29 10:42:17.251 18469 DEBUG nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Preparing to wait for external event network-vif-plugged-9b4da570-b0d3-4a70-9634-379f880fe8ad prepare_for_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:328
2019-03-29 10:42:17.252 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" acquired by "nova.compute.manager._create_or_get_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:42:17.252 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" released by "nova.compute.manager._create_or_get_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:42:17.254 18469 DEBUG nova.virt.libvirt.vif [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=False,config_drive='True',created_at=2019-03-29T02:42:13Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=None,disable_terminate=False,display_description='vm002',display_name='vm002',ec2_ids=EC2Ids,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm002',id=25,image_ref='40f27f13-d552-4f7e-ae5d-2b85b126c85e',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=KeyPairList,launch_index=0,launched_at=None,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=None,old_flavor=None,os_type=None,pci_devices=PciDeviceList,pci_requests=InstancePCIRequests,power_state=0,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-efd35roq',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',image_architecture='x86_64',image_base_image_ref='40f27f13-d552-4f7e-ae5d-2b85b126c85e',image_container_format='bare',image_disk_format='qcow2',image_min_disk='1',image_min_ram='0',network_allocated='True'},tags=<?>,task_state='spawning',terminated_at=None,updated_at=2019-03-29T02:42:15Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=bf4db636-f759-49ce-9cfd-f0702173b4b0,vcpu_model=VirtCPUModel,vcpus=1,vm_mode=None,vm_state='building') vif={"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": false, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null} plug /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:776
2019-03-29 10:42:17.255 18469 DEBUG nova.network.os_vif_util [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": false, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:42:17.256 18469 DEBUG nova.network.os_vif_util [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=False,address=fa:16:3e:82:63:d2,bridge_name='qbr9b4da570-b0',has_traffic_filtering=True,id=9b4da570-b0d3-4a70-9634-379f880fe8ad,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tap9b4da570-b0') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:42:17.257 18469 DEBUG os_vif [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Plugging vif VIFBridge(active=False,address=fa:16:3e:82:63:d2,bridge_name='qbr9b4da570-b0',has_traffic_filtering=True,id=9b4da570-b0d3-4a70-9634-379f880fe8ad,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tap9b4da570-b0') plug /usr/lib/python2.7/site-packages/os_vif/__init__.py:79
2019-03-29 10:42:17.261 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'vif_plug_ovs.linux_net.ensure_bridge', (u'qbr9b4da570-b0',), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.261 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl addbr qbr9b4da570-b0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.268 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl addbr qbr9b4da570-b0" returned: 0 in 0.009s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.269 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl setfd qbr9b4da570-b0 0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.275 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl setfd qbr9b4da570-b0 0" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.275 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl stp qbr9b4da570-b0 off out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.278 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl stp qbr9b4da570-b0 off" returned: 0 in 0.002s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.278 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee /sys/class/net/qbr9b4da570-b0/bridge/multicast_snooping out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.281 18469 DEBUG oslo.privsep.daemon [-] CMD "tee /sys/class/net/qbr9b4da570-b0/bridge/multicast_snooping" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.281 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee /proc/sys/net/ipv6/conf/qbr9b4da570-b0/disable_ipv6 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.283 18469 DEBUG oslo.privsep.daemon [-] CMD "tee /proc/sys/net/ipv6/conf/qbr9b4da570-b0/disable_ipv6" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.283 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.285 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'vif_plug_ovs.linux_net.create_veth_pair', ('qvb9b4da570-b0', 'qvo9b4da570-b0', 1500), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.285 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link add qvb9b4da570-b0 type veth peer name qvo9b4da570-b0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.287 18469 DEBUG neutronclient.v2_0.client [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=bf4db636-f759-49ce-9cfd-f0702173b4b0 used request id req-816f448f-c053-42b0-a9bb-f1decdfd2fa6 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.295 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link add qvb9b4da570-b0 type veth peer name qvo9b4da570-b0" returned: 0 in 0.010s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.295 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvb9b4da570-b0 up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.302 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvb9b4da570-b0 up" returned: 0 in 0.007s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.303 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvb9b4da570-b0 promisc on out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.307 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvb9b4da570-b0 promisc on" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.307 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvb9b4da570-b0 mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.310 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvb9b4da570-b0 mtu 1500" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.311 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvo9b4da570-b0 up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.316 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvo9b4da570-b0 up" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.316 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvo9b4da570-b0 promisc on out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.320 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvo9b4da570-b0 promisc on" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.320 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvo9b4da570-b0 mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.322 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvo9b4da570-b0 mtu 1500" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.322 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.323 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'vif_plug_ovs.linux_net.add_bridge_port', (u'qbr9b4da570-b0', 'qvb9b4da570-b0'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.324 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qbr9b4da570-b0 up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.326 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qbr9b4da570-b0 up" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.326 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl addif qbr9b4da570-b0 qvb9b4da570-b0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.335 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl addif qbr9b4da570-b0 qvb9b4da570-b0" returned: 0 in 0.010s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.335 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.336 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'vif_plug_ovs.linux_net.ensure_ovs_bridge', (u'br-int', 'system'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.336 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl -- --may-exist add-br br-int -- set Bridge br-int datapath_type=system out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.345 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl -- --may-exist add-br br-int -- set Bridge br-int datapath_type=system" returned: 0 in 0.008s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.345 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.345 18469 DEBUG oslo.privsep.daemon [-] privsep: request[102505360]: (3, 'vif_plug_ovs.linux_net.create_ovs_vif_port', (u'br-int', 'qvo9b4da570-b0', '9b4da570-b0d3-4a70-9634-379f880fe8ad', u'fa:16:3e:82:63:d2', 'bf4db636-f759-49ce-9cfd-f0702173b4b0', 1500), {'timeout': 120}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.346 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl --timeout=120 -- --if-exists del-port qvo9b4da570-b0 -- add-port br-int qvo9b4da570-b0 -- set Interface qvo9b4da570-b0 external-ids:iface-id=9b4da570-b0d3-4a70-9634-379f880fe8ad external-ids:iface-status=active external-ids:attached-mac=fa:16:3e:82:63:d2 external-ids:vm-uuid=bf4db636-f759-49ce-9cfd-f0702173b4b0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.368 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl --timeout=120 -- --if-exists del-port qvo9b4da570-b0 -- add-port br-int qvo9b4da570-b0 -- set Interface qvo9b4da570-b0 external-ids:iface-id=9b4da570-b0d3-4a70-9634-379f880fe8ad external-ids:iface-status=active external-ids:attached-mac=fa:16:3e:82:63:d2 external-ids:vm-uuid=bf4db636-f759-49ce-9cfd-f0702173b4b0" returned: 0 in 0.021s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.368 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvo9b4da570-b0 mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.386 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvo9b4da570-b0 mtu 1500" returned: 0 in 0.017s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.386 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[102505360]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:42:17.386 18469 INFO os_vif [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Successfully plugged vif VIFBridge(active=False,address=fa:16:3e:82:63:d2,bridge_name='qbr9b4da570-b0',has_traffic_filtering=True,id=9b4da570-b0d3-4a70-9634-379f880fe8ad,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tap9b4da570-b0')
2019-03-29 10:42:17.400 18469 DEBUG neutronclient.v2_0.client [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-1d472925-4938-4ac7-b033-1a51f4722102 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.419 18469 DEBUG neutronclient.v2_0.client [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.8&port_id=9b4da570-b0d3-4a70-9634-379f880fe8ad used request id req-82977a89-61ef-4851-8fbb-87efdd77d350 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.485 18469 DEBUG neutronclient.v2_0.client [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-bee826d7-1836-419c-85bf-b47dd353deef _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.524 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 7f0a96f05c7648019168aaf1217cd87a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:17.535 18469 DEBUG neutronclient.v2_0.client [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-98234151-a03a-4dc7-88da-64d34cce3185 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.536 18469 DEBUG nova.network.base_api [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": false, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:42:17.537 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: ffbd22ec5f934d8d904d87c7b3cbca4d exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:17.583 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 7f0a96f05c7648019168aaf1217cd87a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:17.584 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ffbd22ec5f934d8d904d87c7b3cbca4d __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:17.586 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: ef2ed16516524527bd8df8213b448574 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:17.587 18469 DEBUG oslo_concurrency.lockutils [req-52afb62f-fed3-4d8b-aa95-2cbc37932265 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Releasing semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:42:17.594 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ef2ed16516524527bd8df8213b448574 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:17.598 18469 INFO nova.virt.libvirt.driver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Using config drive
2019-03-29 10:42:17.666 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?device_id=bf4db636-f759-49ce-9cfd-f0702173b4b0 used request id req-41cb0b40-f948-4f69-82e2-5bac46b6ddd6 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.726 18469 DEBUG neutronclient.v2_0.client [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/security-groups.json?id=4ee28088-03e4-414f-88d4-3c593382000b used request id req-6248b3b8-dfc5-4937-9097-d0f122d5113f _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:17.729 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 567cf128bb60421ba94dd99a4c72f09a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:17.738 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 567cf128bb60421ba94dd99a4c72f09a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:17.740 18469 INFO nova.virt.libvirt.driver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Creating config drive at /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.config
2019-03-29 10:42:17.743 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): genisoimage -o /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.config -ldots -allow-lowercase -allow-multidot -l -publisher OpenStack Compute 0.0.0-1.el7.ceos -quiet -J -r -V config-2 /tmp/tmpyKAeTA execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:42:17.760 18469 DEBUG oslo_concurrency.processutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "genisoimage -o /var/lib/nova/instances/bf4db636-f759-49ce-9cfd-f0702173b4b0/disk.config -ldots -allow-lowercase -allow-multidot -l -publisher OpenStack Compute 0.0.0-1.el7.ceos -quiet -J -r -V config-2 /tmp/tmpyKAeTA" returned: 0 in 0.017s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:42:18.002 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553827338.0, bf4db636-f759-49ce-9cfd-f0702173b4b0 => Started> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:42:18.002 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] VM Started (Lifecycle Event)
2019-03-29 10:42:18.004 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 36e0bc694a664ef6922878e5e0bc543e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:18.048 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 36e0bc694a664ef6922878e5e0bc543e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:18.050 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:42:18.053 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553827338.0, bf4db636-f759-49ce-9cfd-f0702173b4b0 => Paused> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:42:18.054 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] VM Paused (Lifecycle Event)
2019-03-29 10:42:18.055 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 46a0eff57c2f4eedb2b6e5296a5da1b9 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:18.206 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 46a0eff57c2f4eedb2b6e5296a5da1b9 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:18.207 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:42:18.209 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Synchronizing instance power state after lifecycle event "Paused"; current vm_state: building, current task_state: spawning, current DB power_state: 0, VM power_state: 3 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:42:18.211 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 10fce051757540d4ba8151c66b50c83c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:18.256 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 10fce051757540d4ba8151c66b50c83c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:18.257 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] During sync_power_state the instance has a pending task (spawning). Skip.
2019-03-29 10:42:18.745 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._reclaim_queued_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:42:18.746 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CONF.reclaim_instance_interval <= 0, skipping... _reclaim_queued_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6556
2019-03-29 10:42:19.658 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: deafaa7ce2504c53bc54e6909b1c11bf __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:42:19.661 18469 DEBUG nova.compute.manager [req-bed12d8a-44d1-41ca-ab40-bb9e72bb24d5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Received event network-vif-plugged-9b4da570-b0d3-4a70-9634-379f880fe8ad external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:42:19.661 18469 DEBUG oslo_concurrency.lockutils [req-bed12d8a-44d1-41ca-ab40-bb9e72bb24d5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:42:19.662 18469 DEBUG oslo_concurrency.lockutils [req-bed12d8a-44d1-41ca-ab40-bb9e72bb24d5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0-events" released by "nova.compute.manager._pop_event" :: held 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:42:19.662 18469 DEBUG nova.compute.manager [req-bed12d8a-44d1-41ca-ab40-bb9e72bb24d5 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Processing event network-vif-plugged-9b4da570-b0d3-4a70-9634-379f880fe8ad _process_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6816
2019-03-29 10:42:19.665 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553827339.66, bf4db636-f759-49ce-9cfd-f0702173b4b0 => Resumed> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:42:19.665 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] VM Resumed (Lifecycle Event)
2019-03-29 10:42:19.667 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 1d855f2fea4749e1b785d222400f3922 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:19.668 18469 DEBUG nova.virt.libvirt.driver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Instance is running spawn /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:2757
2019-03-29 10:42:19.670 18469 INFO nova.virt.libvirt.driver [-] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Instance spawned successfully.
2019-03-29 10:42:19.670 18469 INFO nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Took 4.92 seconds to spawn the instance on the hypervisor.
2019-03-29 10:42:19.671 18469 DEBUG nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:42:19.676 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: ef735434c025418789ee0d34a19409e8 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:19.729 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 1d855f2fea4749e1b785d222400f3922 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:19.730 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:42:19.754 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Synchronizing instance power state after lifecycle event "Resumed"; current vm_state: building, current task_state: spawning, current DB power_state: 0, VM power_state: 1 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:42:19.756 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: aaaf4ed543994d0496db2929510646a1 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:19.816 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: aaaf4ed543994d0496db2929510646a1 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:19.817 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553827339.67, bf4db636-f759-49ce-9cfd-f0702173b4b0 => Resumed> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:42:19.818 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] VM Resumed (Lifecycle Event)
2019-03-29 10:42:19.819 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 294acf6ada9a4bb9989822d74e371050 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:19.829 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ef735434c025418789ee0d34a19409e8 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:19.834 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: 7bc593c2cd1c404287bf40f0ca0f22dc FANOUT topic 'scheduler' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:539
2019-03-29 10:42:19.838 18469 WARNING nova.image.glance [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:42:19.841 18469 INFO nova.compute.manager [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Took 6.06 seconds to build instance.
2019-03-29 10:42:19.842 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 836014f5045b4357b7f305e98fb5c12f exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:19.871 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 294acf6ada9a4bb9989822d74e371050 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:19.872 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:42:19.874 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Synchronizing instance power state after lifecycle event "Resumed"; current vm_state: active, current task_state: None, current DB power_state: 1, VM power_state: 1 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:42:19.876 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 250279495f604c0c9b10ba23c26b1413 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:19.909 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 836014f5045b4357b7f305e98fb5c12f __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:19.910 18469 DEBUG oslo_concurrency.lockutils [req-d67051c8-7b38-4d41-a8f3-4e413370bed8 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "bf4db636-f759-49ce-9cfd-f0702173b4b0" released by "nova.compute.manager._locked_do_build_and_run_instance" :: held 6.331s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:42:19.927 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 250279495f604c0c9b10ba23c26b1413 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:23.350 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: c9338b9f10d0478e8649f3f1a6ddd464 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:23.401 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c9338b9f10d0478e8649f3f1a6ddd464 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:25.702 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rebooting_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:42:26.699 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._heal_instance_info_cache run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:42:26.700 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Starting heal instance info cache _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5884
2019-03-29 10:42:26.700 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Rebuilding the list of instances to heal _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5888
2019-03-29 10:42:26.701 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 834993a88478454cb0a630227f12cc58 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:26.732 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 834993a88478454cb0a630227f12cc58 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:26.733 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Acquired semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:42:26.733 18469 DEBUG nova.network.neutronv2.api [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:42:26.734 18469 DEBUG nova.objects.instance [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lazy-loading 'info_cache' on Instance uuid bf4db636-f759-49ce-9cfd-f0702173b4b0 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:42:26.735 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: bd9291448bad40c78988aa374ee79ce5 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:26.777 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: bd9291448bad40c78988aa374ee79ce5 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:26.779 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 1df463c1c6644d268a0d3f4329fbaf1a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:26.787 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 1df463c1c6644d268a0d3f4329fbaf1a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:26.853 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=bf4db636-f759-49ce-9cfd-f0702173b4b0 used request id req-f5e2f4f6-1a34-47b6-95a5-da3b87913382 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:26.966 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-22612a72-f491-4e65-9ec7-42a99522dfde _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:26.986 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.8&port_id=9b4da570-b0d3-4a70-9634-379f880fe8ad used request id req-8106e240-0727-4ed4-baeb-34f5e491e89d _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:27.040 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-0d31ea35-59e0-4571-9a82-8a543b58c45f _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:27.087 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-2ce274e5-922f-4333-8ea8-1f45ffcbd3a4 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:42:27.087 18469 DEBUG nova.network.base_api [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.8"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tap9b4da570-b0", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:82:63:d2", "active": true, "type": "ovs", "id": "9b4da570-b0d3-4a70-9634-379f880fe8ad", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:42:27.088 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 51793a87b0784ddbb0753d9200f9943c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:27.118 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 51793a87b0784ddbb0753d9200f9943c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:27.118 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Releasing semaphore "refresh_cache-bf4db636-f759-49ce-9cfd-f0702173b4b0" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:42:27.119 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: bf4db636-f759-49ce-9cfd-f0702173b4b0] Updated the network info_cache for instance _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5946
2019-03-29 10:42:33.353 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: a9af25af76244b69862b832df3754e45 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:42:33.397 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a9af25af76244b69862b832df3754e45 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:42:35.116 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_unconfirmed_resizes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:42:35.117 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._check_instance_build_time run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:42:36.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._instance_usage_audit run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:42:37.701 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_volume_usage run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
