2019-03-29 10:01:55.499 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: b25bd9a7bff14313be23a5223b3a3903 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:01:55.533 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b25bd9a7bff14313be23a5223b3a3903 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:01.704 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_volume_usage run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:04.698 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._check_instance_build_time run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:05.496 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 1fc7110e13ee434081d194de14587433 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:05.530 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 1fc7110e13ee434081d194de14587433 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:07.701 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager.update_available_resource run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:07.703 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 5d8a3f4a17034ec28e59cab4de2df142 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:07.729 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5d8a3f4a17034ec28e59cab4de2df142 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:07.734 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Auditing locally available compute resources for com58 (node: com58) update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:534
2019-03-29 10:02:07.839 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Hypervisor: free VCPUs: 2 _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:655
2019-03-29 10:02:07.839 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Hypervisor/Node resource view: name=com58 free_ram=7129MB free_disk=45GB free_vcpus=2 pci_devices=[{"dev_id": "pci_0000_00_00_0", "product_id": "7190", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7190", "address": "0000:00:00.0"}, {"dev_id": "pci_0000_00_01_0", "product_id": "7191", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7191", "address": "0000:00:01.0"}, {"dev_id": "pci_0000_00_07_0", "product_id": "7110", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7110", "address": "0000:00:07.0"}, {"dev_id": "pci_0000_00_07_1", "product_id": "7111", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7111", "address": "0000:00:07.1"}, {"dev_id": "pci_0000_00_07_3", "product_id": "7113", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_7113", "address": "0000:00:07.3"}, {"dev_id": "pci_0000_00_07_7", "product_id": "0740", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0740", "address": "0000:00:07.7"}, {"dev_id": "pci_0000_00_0f_0", "product_id": "0405", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0405", "address": "0000:00:0f.0"}, {"dev_id": "pci_0000_00_11_0", "product_id": "0790", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_0790", "address": "0000:00:11.0"}, {"dev_id": "pci_0000_00_15_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.0"}, {"dev_id": "pci_0000_03_00_0", "product_id": "07c0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07c0", "address": "0000:03:00.0"}, {"dev_id": "pci_0000_00_15_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.1"}, {"dev_id": "pci_0000_00_15_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.2"}, {"dev_id": "pci_0000_00_15_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.3"}, {"dev_id": "pci_0000_00_15_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.4"}, {"dev_id": "pci_0000_00_15_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.5"}, {"dev_id": "pci_0000_00_15_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.6"}, {"dev_id": "pci_0000_00_15_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:15.7"}, {"dev_id": "pci_0000_00_16_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.0"}, {"dev_id": "pci_0000_0b_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:0b:00.0"}, {"dev_id": "pci_0000_00_16_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.1"}, {"dev_id": "pci_0000_00_16_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.2"}, {"dev_id": "pci_0000_00_16_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.3"}, {"dev_id": "pci_0000_00_16_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.4"}, {"dev_id": "pci_0000_00_16_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.5"}, {"dev_id": "pci_0000_00_16_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.6"}, {"dev_id": "pci_0000_00_16_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:16.7"}, {"dev_id": "pci_0000_00_17_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.0"}, {"dev_id": "pci_0000_13_00_0", "product_id": "07b0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07b0", "address": "0000:13:00.0"}, {"dev_id": "pci_0000_00_17_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.1"}, {"dev_id": "pci_0000_00_17_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.2"}, {"dev_id": "pci_0000_00_17_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.3"}, {"dev_id": "pci_0000_00_17_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.4"}, {"dev_id": "pci_0000_00_17_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.5"}, {"dev_id": "pci_0000_00_17_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.6"}, {"dev_id": "pci_0000_00_17_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:17.7"}, {"dev_id": "pci_0000_00_18_0", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.0"}, {"dev_id": "pci_0000_00_18_1", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.1"}, {"dev_id": "pci_0000_00_18_2", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.2"}, {"dev_id": "pci_0000_00_18_3", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.3"}, {"dev_id": "pci_0000_00_18_4", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.4"}, {"dev_id": "pci_0000_00_18_5", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.5"}, {"dev_id": "pci_0000_00_18_6", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.6"}, {"dev_id": "pci_0000_00_18_7", "product_id": "07a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "15ad", "label": "label_15ad_07a0", "address": "0000:00:18.7"}] _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:672
2019-03-29 10:02:07.840 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker._update_available_resource" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:02:07.842 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 58720728f9fb42adbb4b9c6bacfe54e0 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:07.876 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 58720728f9fb42adbb4b9c6bacfe54e0 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:07.878 18469 DEBUG nova.scheduler.client.report [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:02:07.917 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: edf347eec9374f00bb18a528a036ba32 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:07.934 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: edf347eec9374f00bb18a528a036ba32 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:07.951 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 52c8bb1399bc41d09832921e94b07138 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:07.983 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 52c8bb1399bc41d09832921e94b07138 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:07.984 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Total usable vcpus: 2, total allocated vcpus: 0 _report_final_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:688
2019-03-29 10:02:07.985 18469 INFO nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Final resource view: name=com58 phys_ram=8191MB used_ram=512MB phys_disk=47GB used_disk=0GB total_vcpus=2 used_vcpus=0 pci_stats=[]
2019-03-29 10:02:07.988 18469 DEBUG nova.compute.resource_tracker [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Compute_service record updated for com58:com58 _update_available_resource /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:626
2019-03-29 10:02:07.989 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lock "compute_resources" released by "nova.compute.resource_tracker._update_available_resource" :: held 0.149s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:02:08.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rescued_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:15.494 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: c84c3dbb8a5a48a69caaebd5637eb35a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:15.527 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: c84c3dbb8a5a48a69caaebd5637eb35a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:19.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._run_pending_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:19.701 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Cleaning up deleted instances _run_pending_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6911
2019-03-29 10:02:19.703 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 0cbf2a53e41149dc8191119999d75f78 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:19.719 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0cbf2a53e41149dc8191119999d75f78 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:19.720 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] There are 0 instances to clean _run_pending_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6920
2019-03-29 10:02:25.492 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: d4643e74e4a548e6b2990699ce3efc08 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:25.520 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: d4643e74e4a548e6b2990699ce3efc08 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.095 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 6578cf7a4b804eaab393b70493e0683b __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:02:34.105 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" acquired by "nova.compute.manager._locked_do_build_and_run_instance" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:02:34.106 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 4643c15b89ec41cd89680561e9193259 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.145 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4643c15b89ec41cd89680561e9193259 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.145 18469 DEBUG nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Starting instance... _do_build_and_run_instance /usr/lib/python2.7/site-packages/nova/compute/manager.py:1759
2019-03-29 10:02:34.148 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: efec5ea30cc94063a26c68b511582eb6 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.247 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: efec5ea30cc94063a26c68b511582eb6 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.250 18469 WARNING nova.image.glance [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:02:34.254 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.instance_claim" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:02:34.256 18469 DEBUG nova.compute.resource_tracker [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Memory overhead for 512 MB instance; 0 MB instance_claim /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:147
2019-03-29 10:02:34.257 18469 DEBUG nova.compute.resource_tracker [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Disk overhead for 1 GB instance; 0 GB instance_claim /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:150
2019-03-29 10:02:34.258 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 299c903a41104d4ba9070756c04ba3b5 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.270 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 299c903a41104d4ba9070756c04ba3b5 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.273 18469 INFO nova.compute.claims [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Attempting claim: memory 512 MB, disk 1 GB, vcpus 1 CPU
2019-03-29 10:02:34.273 18469 INFO nova.compute.claims [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Total memory: 8191 MB, used: 512.00 MB
2019-03-29 10:02:34.274 18469 INFO nova.compute.claims [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] memory limit: 12286.50 MB, free: 11774.50 MB
2019-03-29 10:02:34.275 18469 INFO nova.compute.claims [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Total disk: 47 GB, used: 0.00 GB
2019-03-29 10:02:34.275 18469 INFO nova.compute.claims [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] disk limit: 47.00 GB, free: 47.00 GB
2019-03-29 10:02:34.276 18469 INFO nova.compute.claims [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Total vcpu: 2 VCPU, used: 0.00 VCPU
2019-03-29 10:02:34.276 18469 INFO nova.compute.claims [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] vcpu limit: 32.00 VCPU, free: 32.00 VCPU
2019-03-29 10:02:34.277 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Require both a host and instance NUMA topology to fit instance on host. numa_fit_instance_to_host /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1328
2019-03-29 10:02:34.278 18469 INFO nova.compute.claims [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Claim successful
2019-03-29 10:02:34.281 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 1a4d89d43358445e8186dc44c32287e6 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.433 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 1a4d89d43358445e8186dc44c32287e6 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.438 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 1d53aee8bed8447da417576d1ccc92ee exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.449 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 1d53aee8bed8447da417576d1ccc92ee __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.462 18469 DEBUG nova.scheduler.client.report [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Sending allocation for instance {'MEMORY_MB': 512, 'VCPU': 1} _allocate_for_instance /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:664
2019-03-29 10:02:34.535 18469 INFO nova.scheduler.client.report [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Submitted allocation for instance
2019-03-29 10:02:34.544 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 6d6cf8c34e47461d9f9123aca3e0471a exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.593 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 6d6cf8c34e47461d9f9123aca3e0471a __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.595 18469 DEBUG nova.scheduler.client.report [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:02:34.622 18469 DEBUG nova.scheduler.client.report [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Updating our resource provider generation from 28 to 29 _get_inventory_and_update_provider_generation /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:445
2019-03-29 10:02:34.622 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.instance_claim" :: held 0.369s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:02:34.623 18469 DEBUG nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Start building networks asynchronously for instance. _build_resources /usr/lib/python2.7/site-packages/nova/compute/manager.py:2074
2019-03-29 10:02:34.626 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 7df8e27c61c54af881931016440b532c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.747 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 7df8e27c61c54af881931016440b532c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.748 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" acquired by "nova.compute.resource_tracker.update_usage" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:02:34.754 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 987d29b3e0564a4784a35d09e536c63c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.801 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 987d29b3e0564a4784a35d09e536c63c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.802 18469 DEBUG nova.scheduler.client.report [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Refreshing aggregate associations for resource provider d3edbe3c-4889-4f14-ab35-ef1bb940aec8 _ensure_resource_provider /usr/lib/python2.7/site-packages/nova/scheduler/client/report.py:402
2019-03-29 10:02:34.828 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "compute_resources" released by "nova.compute.resource_tracker.update_usage" :: held 0.080s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:02:34.829 18469 WARNING nova.virt.libvirt.driver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Ignoring supplied device name: /dev/vda. Libvirt can't honour user-supplied dev names
2019-03-29 10:02:34.832 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 00ad9610221d49fa885497f3af73c960 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.833 18469 DEBUG nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Allocating IP information in the background. _allocate_network_async /usr/lib/python2.7/site-packages/nova/compute/manager.py:1390
2019-03-29 10:02:34.833 18469 DEBUG nova.network.neutronv2.api [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] allocate_for_instance() allocate_for_instance /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:840
2019-03-29 10:02:34.911 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 00ad9610221d49fa885497f3af73c960 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:34.912 18469 DEBUG nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Start building block device mappings for instance. _build_resources /usr/lib/python2.7/site-packages/nova/compute/manager.py:2100
2019-03-29 10:02:34.915 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 8789271c5df548d6ab89daa753c2b842 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:34.964 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-19ef38b9-e337-436d-9d8b-6219b93d0e53 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:35.123 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 8789271c5df548d6ab89daa753c2b842 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:35.126 18469 INFO nova.virt.block_device [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Booting with blank volume at /dev/vda
2019-03-29 10:02:35.137 18469 DEBUG cinderclient.v2.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X GET http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e -H "User-Agent: python-cinderclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}565b95e1b59c00569eacc9f28a9f5472a35f8add" _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:02:35.139 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/security-groups.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917 used request id req-284ec355-56e0-4239-b0c6-276a2b9d8c3f _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:35.249 18469 DEBUG cinderclient.v2.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [200] X-Compute-Request-Id: req-a69adbd7-9ada-412e-8207-69759dc24cbb Content-Type: application/json Content-Length: 1324 X-Openstack-Request-Id: req-a69adbd7-9ada-412e-8207-69759dc24cbb Date: Fri, 29 Mar 2019 02:02:35 GMT Connection: keep-alive 
RESP BODY: {"volume": {"migration_status": null, "attachments": [], "links": [{"href": "http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e", "rel": "self"}, {"href": "http://172.30.126.56:8776/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e", "rel": "bookmark"}], "availability_zone": "nova", "os-vol-host-attr:host": "ctl01@lvm#lvm", "encrypted": false, "updated_at": "2019-03-28T10:51:05.000000", "replication_status": null, "snapshot_id": null, "id": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "size": 1, "user_id": "9e9e53917dda421083fa6af425c6bfbf", "os-vol-tenant-attr:tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "os-vol-mig-status-attr:migstat": null, "metadata": {}, "status": "available", "volume_image_metadata": {"checksum": "ee1eca47dc88f4879d8a229cc70a07c6", "min_ram": "0", "disk_format": "qcow2", "image_name": "cirros", "image_id": "40f27f13-d552-4f7e-ae5d-2b85b126c85e", "architecture": "x86_64", "container_format": "bare", "min_disk": "0", "size": "13287936"}, "description": "", "multiattach": false, "source_volid": "d04e7667-4380-44f9-afb6-9a7327703c56", "consistencygroup_id": null, "os-vol-mig-status-attr:name_id": null, "name": "v2", "bootable": "true", "created_at": "2019-03-28T06:31:41.000000", "volume_type": "iscsi"}}
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:02:35.249 18469 DEBUG cinderclient.v2.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e used request id req-a69adbd7-9ada-412e-8207-69759dc24cbb request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:02:35.250 18469 DEBUG os_brick.utils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> get_connector_properties: call u"{'execute': None, 'my_ip': '172.30.126.58', 'enforce_multipath': True, 'host': 'com58', 'root_helper': 'sudo nova-rootwrap /etc/nova/rootwrap.conf', 'multipath': False}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:02:35.252 18469 INFO oslo.privsep.daemon [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running privsep helper: ['sudo', 'nova-rootwrap', '/etc/nova/rootwrap.conf', 'privsep-helper', '--config-file', '/usr/share/nova/nova-dist.conf', '--config-file', '/etc/nova/nova.conf', '--privsep_context', 'os_brick.privileged.default', '--privsep_sock_path', '/tmp/tmpXlrAOx/privsep.sock']
2019-03-29 10:02:35.884 18469 INFO oslo.privsep.daemon [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Spawned new privsep daemon via rootwrap
2019-03-29 10:02:35.885 18469 DEBUG oslo.privsep.daemon [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Accepted privsep connection to /tmp/tmpXlrAOx/privsep.sock __init__ /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:313
2019-03-29 10:02:35.887 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 53ddcf22ff9540eb844779371d741aa8 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:35.889 18469 INFO oslo.privsep.daemon [-] privsep daemon starting
2019-03-29 10:02:35.889 18469 INFO oslo.privsep.daemon [-] privsep process running with uid/gid: 0/0
2019-03-29 10:02:35.889 18469 INFO oslo.privsep.daemon [-] privsep process running with capabilities (eff/prm/inh): CAP_SYS_ADMIN/CAP_SYS_ADMIN/none
2019-03-29 10:02:35.889 18469 INFO oslo.privsep.daemon [-] privsep daemon running as pid 24812
2019-03-29 10:02:35.890 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (1,) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:35.891 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (2,) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:35.896 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('cat', '/etc/iscsi/initiatorname.iscsi'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:35.954 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): cat /etc/iscsi/initiatorname.iscsi out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:35.958 18469 DEBUG oslo.privsep.daemon [-] CMD "cat /etc/iscsi/initiatorname.iscsi" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:35.959 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('InitiatorName=iqn.1994-05.com.redhat:9affbb458449\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:35.960 18469 DEBUG os_brick.initiator.linuxfc [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:02:35.961 18469 DEBUG os_brick.initiator.linuxfc [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No Fibre Channel support detected on system. get_fc_hbas /usr/lib/python2.7/site-packages/os_brick/initiator/linuxfc.py:91
2019-03-29 10:02:35.962 18469 DEBUG os_brick.utils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== get_connector_properties: return (710ms) {'initiator': u'iqn.1994-05.com.redhat:9affbb458449', 'ip': u'172.30.126.58', 'platform': u'x86_64', 'host': u'com58', 'do_local_attach': False, 'os_type': u'linux2', 'multipath': False} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:02:35.964 18469 DEBUG cinderclient.v2.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X POST http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}565b95e1b59c00569eacc9f28a9f5472a35f8add" -d '{"os-initialize_connection": {"connector": {"platform": "x86_64", "host": "com58", "do_local_attach": false, "ip": "172.30.126.58", "os_type": "linux2", "multipath": false, "initiator": "iqn.1994-05.com.redhat:9affbb458449"}}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:02:36.040 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 53ddcf22ff9540eb844779371d741aa8 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:36.212 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to neutron for http://172.30.126.56:9696/v2.0/ports.json used request id req-46f5f305-decf-423e-83aa-5ab48784f9e4 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:36.213 18469 DEBUG nova.network.neutronv2.api [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Successfully created port: b3249515-3aab-439f-ba9c-bc498756871a _create_port_minimal /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:407
2019-03-29 10:02:36.227 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/extensions.json used request id req-d43f285a-fa99-4049-97cd-6c5cf7266135 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:37.890 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] PUT call to neutron for http://172.30.126.56:9696/v2.0/ports/b3249515-3aab-439f-ba9c-bc498756871a.json used request id req-16cb3dbc-a9d2-426e-9348-81a3a2d305e1 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:37.891 18469 DEBUG nova.network.neutronv2.api [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Successfully updated port: b3249515-3aab-439f-ba9c-bc498756871a _update_port /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:444
2019-03-29 10:02:37.893 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 40fb2d86e72f4169902e6c3881b5f0fe exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:37.953 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 40fb2d86e72f4169902e6c3881b5f0fe __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:37.954 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:02:37.955 18469 DEBUG nova.network.neutronv2.api [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:02:37.956 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 479ab65b5af949b4bc63931c2569c481 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:38.011 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 479ab65b5af949b4bc63931c2569c481 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:38.104 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-2fec661e-8fd4-4187-82d7-dbf260263c97 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:38.105 18469 DEBUG nova.network.neutronv2.api [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance cache missing network info. _get_preexisting_port_ids /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:2194
2019-03-29 10:02:38.126 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-c79efa16-68e2-4be2-98a3-d72a7612a063 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:38.206 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-2ef13b1e-1744-4491-a8a0-835af08a915b _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:38.292 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-82dce273-bdd8-459a-81e1-f5b61f546510 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:38.293 18469 DEBUG nova.network.base_api [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:02:38.295 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: cc0c103a5a33495aaaf870325ce0c507 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:38.394 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: cc0c103a5a33495aaaf870325ce0c507 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:38.395 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:02:38.396 18469 DEBUG nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance network_info: |[{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}]| _allocate_network_async /usr/lib/python2.7/site-packages/nova/compute/manager.py:1405
2019-03-29 10:02:38.463 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 325883ec2e4945c1a37b03db1650ef7e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:02:38.467 18469 DEBUG nova.compute.manager [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-changed external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:02:38.468 18469 DEBUG oslo_concurrency.lockutils [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:02:38.469 18469 DEBUG nova.network.neutronv2.api [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:02:38.471 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: f1f93d8b93f445af9c130a13cd77dde6 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:38.483 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f1f93d8b93f445af9c130a13cd77dde6 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:38.544 18469 DEBUG neutronclient.v2_0.client [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-c2f0b964-6e2c-43d4-9664-364e851c6635 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:38.652 18469 DEBUG neutronclient.v2_0.client [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-a1854a82-4e2a-4634-b29d-d36122142ba9 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:38.672 18469 DEBUG neutronclient.v2_0.client [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-b1f1aa53-eea4-4725-ac26-dcd51eff4033 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:38.731 18469 DEBUG neutronclient.v2_0.client [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-80cf5ae1-5ee2-46c0-8661-6e6bcd46ee21 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:38.774 18469 DEBUG neutronclient.v2_0.client [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-2739f386-a225-4afe-b545-69cb8147e5e2 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:38.776 18469 DEBUG nova.network.base_api [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:02:38.778 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] CALL msg_id: 140ca916cc1540c69db235c83805abdd exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:38.793 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 140ca916cc1540c69db235c83805abdd __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:38.794 18469 DEBUG oslo_concurrency.lockutils [req-15acf008-c3e3-493b-b802-2351abb1e142 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:02:39.985 18469 DEBUG cinderclient.v2.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [200] X-Compute-Request-Id: req-1e3d4f8f-1cd4-4db4-bde3-1ed12db7051c Content-Type: application/json Content-Length: 447 X-Openstack-Request-Id: req-1e3d4f8f-1cd4-4db4-bde3-1ed12db7051c Date: Fri, 29 Mar 2019 02:02:40 GMT Connection: keep-alive 
RESP BODY: {"connection_info": {"driver_volume_type": "iscsi", "data": {"auth_password": "TPnqk7LML2MKpPv4", "target_discovered": false, "encrypted": false, "qos_specs": null, "target_iqn": "iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e", "target_portal": "172.30.126.56:3260", "volume_id": "78a56ddc-ee21-4278-991e-17b30d68fa6e", "target_lun": 0, "access_mode": "rw", "auth_username": "PutS9jPtTsLadXTr42qr", "auth_method": "CHAP"}}}
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:02:39.986 18469 DEBUG cinderclient.v2.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action used request id req-1e3d4f8f-1cd4-4db4-bde3-1ed12db7051c request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:02:39.987 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 787485d9856c4a0a9182ed773698ffaf exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:40.024 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 787485d9856c4a0a9182ed773698ffaf __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:40.026 18469 DEBUG cinderclient.v2.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] REQ: curl -g -i -X POST http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}565b95e1b59c00569eacc9f28a9f5472a35f8add" -d '{"os-attach": {"instance_uuid": "f5a19c94-1a45-4ea0-9386-77c10705c825", "mountpoint": "/dev/vda", "mode": "rw"}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:347
2019-03-29 10:02:40.386 18469 DEBUG cinderclient.v2.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 X-Openstack-Request-Id: req-358c2b75-b077-42ae-bbc7-1b091abb4b5e Date: Fri, 29 Mar 2019 02:02:40 GMT Connection: keep-alive 
RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
 _http_log_response /usr/lib/python2.7/site-packages/keystoneauth1/session.py:395
2019-03-29 10:02:40.386 18469 DEBUG cinderclient.v2.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] POST call to cinderv2 for http://172.30.126.56:8776/v2/d4bbd972ca1b463ba028ccd1df983917/volumes/78a56ddc-ee21-4278-991e-17b30d68fa6e/action used request id req-358c2b75-b077-42ae-bbc7-1b091abb4b5e request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:640
2019-03-29 10:02:40.388 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: a6a69d76c0de4cb092b7f911be595141 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:40.418 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: a6a69d76c0de4cb092b7f911be595141 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:40.421 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: fdd5256c6ec84fbeae62ecd4fedda2ef exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:40.532 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: fdd5256c6ec84fbeae62ecd4fedda2ef __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:40.536 18469 DEBUG nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Start spawning the instance on the hypervisor. _build_and_run_instance /usr/lib/python2.7/site-packages/nova/compute/manager.py:1933
2019-03-29 10:02:40.538 18469 INFO nova.virt.libvirt.driver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Creating image
2019-03-29 10:02:40.539 18469 DEBUG nova.virt.libvirt.driver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Ensure instance console log exists: /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/console.log _ensure_console_log_for_instance /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:3019
2019-03-29 10:02:40.543 18469 DEBUG nova.virt.libvirt.driver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Start _get_guest_xml network_info=[{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] disk_info={'disk_bus': 'virtio', 'cdrom_bus': 'ide', 'mapping': {u'/dev/vda': {'bus': u'virtio', 'boot_index': '1', 'type': u'disk', 'dev': u'vda'}, 'root': {'bus': u'virtio', 'boot_index': '1', 'type': u'disk', 'dev': u'vda'}, 'disk.config': {'bus': 'ide', 'type': 'cdrom', 'dev': 'hda'}}} image_meta=ImageMeta(checksum=<?>,container_format=<?>,created_at=<?>,direct_url=<?>,disk_format=<?>,id=<?>,min_disk=0,min_ram=0,name=<?>,owner=<?>,properties=ImageMetaProps,protected=<?>,size=1073741824,status='active',tags=<?>,updated_at=<?>,virtual_size=<?>,visibility=<?>) rescue=None block_device_info={'swap': None, 'root_device_name': u'/dev/vda', 'ephemerals': [], 'block_device_mapping': [{'guest_format': None, 'boot_index': 0, 'mount_device': u'/dev/vda', 'connection_info': {u'driver_volume_type': u'iscsi', 'connector': {'platform': 'x86_64', 'host': 'com58', 'do_local_attach': False, 'ip': '172.30.126.58', 'os_type': 'linux2', 'multipath': False, 'initiator': u'iqn.1994-05.com.redhat:9affbb458449'}, 'serial': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'data': {u'access_mode': u'rw', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_portal': u'172.30.126.56:3260', u'volume_id': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_lun': 0, u'auth_password': u'***', u'auth_username': u'PutS9jPtTsLadXTr42qr', u'auth_method': u'CHAP'}}, 'disk_bus': u'virtio', 'device_type': u'disk', 'delete_on_termination': False}]} _get_guest_xml /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:4971
2019-03-29 10:02:40.555 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Getting desirable topologies for flavor Flavor(created_at=2019-03-25T11:43:43Z,deleted=False,deleted_at=None,disabled=False,ephemeral_gb=0,extra_specs={},flavorid='1',id=1,is_public=True,memory_mb=512,name='m1.tiny',projects=<?>,root_gb=1,rxtx_factor=1.0,swap=0,updated_at=None,vcpu_weight=0,vcpus=1) and image_meta ImageMeta(checksum=<?>,container_format=<?>,created_at=<?>,direct_url=<?>,disk_format=<?>,id=<?>,min_disk=0,min_ram=0,name=<?>,owner=<?>,properties=ImageMetaProps,protected=<?>,size=1073741824,status='active',tags=<?>,updated_at=<?>,virtual_size=<?>,visibility=<?>), allow threads: True _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:560
2019-03-29 10:02:40.556 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flavor limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:306
2019-03-29 10:02:40.556 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Image limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:317
2019-03-29 10:02:40.557 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Flavor pref -1:-1:-1 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:340
2019-03-29 10:02:40.557 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Image pref -1:-1:-1 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:359
2019-03-29 10:02:40.557 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Chosen -1:-1:-1 limits 65536:65536:65536 _get_cpu_topology_constraints /usr/lib/python2.7/site-packages/nova/virt/hardware.py:388
2019-03-29 10:02:40.558 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Topology preferred VirtCPUTopology(cores=-1,sockets=-1,threads=-1), maximum VirtCPUTopology(cores=65536,sockets=65536,threads=65536) _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:564
2019-03-29 10:02:40.558 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Build topologies for 1 vcpu(s) 1:1:1 _get_possible_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:427
2019-03-29 10:02:40.558 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Got 1 possible topologies _get_possible_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:454
2019-03-29 10:02:40.559 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Possible topologies [VirtCPUTopology(cores=1,sockets=1,threads=1)] _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:569
2019-03-29 10:02:40.559 18469 DEBUG nova.virt.hardware [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Sorted desired topologies [VirtCPUTopology(cores=1,sockets=1,threads=1)] _get_desirable_cpu_topologies /usr/lib/python2.7/site-packages/nova/virt/hardware.py:594
2019-03-29 10:02:40.562 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Calling os-brick to attach iSCSI Volume connect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:63
2019-03-29 10:02:40.563 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ==> connect_volume: call u"{'args': (<os_brick.initiator.connectors.iscsi.ISCSIConnector object at 0x5ae9b50>, {u'access_mode': u'rw', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_portal': u'172.30.126.56:3260', u'volume_id': u'78a56ddc-ee21-4278-991e-17b30d68fa6e', u'target_lun': 0, u'auth_password': u'***', u'auth_username': u'PutS9jPtTsLadXTr42qr', u'auth_method': u'CHAP'}), 'kwargs': {}}" trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:146
2019-03-29 10:02:40.564 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" acquired by "os_brick.initiator.connectors.iscsi.connect_volume" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:02:40.564 18469 INFO os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Multipath discovery for iSCSI not enabled.
2019-03-29 10:02:40.564 18469 INFO os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Trying to connect to iSCSI portal 172.30.126.56:3260
2019-03-29 10:02:40.566 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.566 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.573 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260" returned: 21 in 0.007s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.573 18469 DEBUG oslo.privsep.daemon [-] u'iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260' failed. Not Retrying. out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.573 18469 DEBUG oslo.privsep.daemon [-] privsep: Exception during request[97285136]: Unexpected error while running command.
Command: iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260
Exit code: 21
Stdout: u''
Stderr: u'iscsiadm: No records found\n' out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.573 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (5, 'oslo_concurrency.processutils.ProcessExecutionError', (u'', u'iscsiadm: No records found\n', 21, u'iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260', None)) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.575 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--interface', 'default', '--op', 'new'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.575 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --interface default --op new out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.580 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --interface default --op new" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.580 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 172.30.126.56,3260,-1 iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e] added\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.580 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--interface', 'default', '--op', 'new'): stdout=New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 172.30.126.56,3260,-1 iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e] added
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:02:40.581 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.session.auth.authmethod', '-v', u'CHAP'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.581 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.authmethod -v CHAP out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.585 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.authmethod -v CHAP" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.585 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.586 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.session.auth.authmethod', '-v', u'CHAP'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:02:40.586 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.session.auth.username', '-v', u'PutS9jPtTsLadXTr42qr'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.586 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.username -v PutS9jPtTsLadXTr42qr out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.596 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.username -v PutS9jPtTsLadXTr42qr" returned: 0 in 0.010s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.596 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.597 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.session.auth.username', '-v', u'PutS9jPtTsLadXTr42qr'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:02:40.597 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.session.auth.password', '-v', u'TPnqk7LML2MKpPv4'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.598 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.password -v *** out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.602 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.session.auth.password -v ***" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.602 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.602 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.session.auth.password', '-v', u'***'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:02:40.603 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'session'), {'check_exit_code': (0, 1, 21)}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.603 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m session out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.606 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m session" returned: 21 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.607 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('', 'iscsiadm: No active sessions.\n')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.607 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ['-m', 'session']: stdout= stderr=iscsiadm: No active sessions.
 _run_iscsiadm_bare /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:824
2019-03-29 10:02:40.608 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--login'), {'attempts': 1, 'check_exit_code': (0, 255), 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.608 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --login out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.651 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --login" returned: 0 in 0.043s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.651 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('Logging in to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] (multiple)\nLogin to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.651 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--login',): stdout=Logging in to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] (multiple)
Login to [iface: default, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260] successful.
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:02:40.653 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--op', 'update', '-n', 'node.startup', '-v', 'automatic'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.653 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v automatic out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.657 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --op update -n node.startup -v automatic" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.657 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.657 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--op', 'update', '-n', 'node.startup', '-v', 'automatic'): stdout= stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:02:40.658 18469 INFO os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] ISCSI volume not yet found at: [u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0']. Will rescan & retry.  Try number: 0.
2019-03-29 10:02:40.660 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e', '-p', u'172.30.126.56:3260', '--rescan'), {'attempts': 1, 'check_exit_code': 0, 'delay_on_retry': True}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.661 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --rescan out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.709 18469 DEBUG oslo.privsep.daemon [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e -p 172.30.126.56:3260 --rescan" returned: 0 in 0.049s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.710 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('Rescanning session [sid: 8, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:40.710 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] iscsiadm ('--rescan',): stdout=Rescanning session [sid: 8, target: iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e, portal: 172.30.126.56,3260]
 stderr= _run_iscsiadm /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:598
2019-03-29 10:02:40.720 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._reclaim_queued_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:40.721 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CONF.reclaim_instance_interval <= 0, skipping... _reclaim_queued_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6556
2019-03-29 10:02:41.711 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Found iSCSI node [u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0'] (after 1 rescans) connect_volume /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:437
2019-03-29 10:02:41.715 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'os_brick.privileged.rootwrap.execute_root', ('/lib/udev/scsi_id', '--page', '0x83', '--whitelisted', u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.715 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): /lib/udev/scsi_id --page 0x83 --whitelisted /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.722 18469 DEBUG oslo.privsep.daemon [-] CMD "/lib/udev/scsi_id --page 0x83 --whitelisted /dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0" returned: 0 in 0.009s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.723 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, ('36001405fb81b00707464d729f24ff6c3\n', '')) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.723 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Device WWN = '36001405fb81b00707464d729f24ff6c3' connect_volume /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:444
2019-03-29 10:02:41.723 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] connect_volume returning {'path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', 'scsi_wwn': u'36001405fb81b00707464d729f24ff6c3', 'type': 'block'} connect_volume /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/iscsi.py:456
2019-03-29 10:02:41.724 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "connect_volume" released by "os_brick.initiator.connectors.iscsi.connect_volume" :: held 1.160s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:02:41.724 18469 DEBUG os_brick.initiator.connectors.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] <== connect_volume: return (1161ms) {'path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', 'scsi_wwn': u'36001405fb81b00707464d729f24ff6c3', 'type': u'block'} trace_logging_wrapper /usr/lib/python2.7/site-packages/os_brick/utils.py:170
2019-03-29 10:02:41.725 18469 DEBUG nova.virt.libvirt.volume.iscsi [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Attached iSCSI volume {'path': u'/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0', 'scsi_wwn': u'36001405fb81b00707464d729f24ff6c3', 'type': 'block'} connect_volume /usr/lib/python2.7/site-packages/nova/virt/libvirt/volume/iscsi.py:65
2019-03-29 10:02:41.731 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 519c87421235479d9cbed41d955ea80e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:41.767 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 519c87421235479d9cbed41d955ea80e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:41.770 18469 DEBUG nova.virt.libvirt.vif [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=False,config_drive='True',created_at=2019-03-29T02:02:33Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=None,disable_terminate=False,display_description='vm001',display_name='vm001',ec2_ids=EC2Ids,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm001',id=24,image_ref='',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=KeyPairList,launch_index=0,launched_at=None,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=None,old_flavor=None,os_type=None,pci_devices=<?>,pci_requests=InstancePCIRequests,power_state=0,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-x56iqcqr',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',image_architecture='x86_64',image_base_image_ref='',image_min_disk='1',image_min_ram='0',network_allocated='True'},tags=<?>,task_state='spawning',terminated_at=None,updated_at=2019-03-29T02:02:35Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,vcpu_model=VirtCPUModel,vcpus=1,vm_mode=None,vm_state='building') vif={"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} virt_type=qemu get_config /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:529
2019-03-29 10:02:41.771 18469 DEBUG nova.network.os_vif_util [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:02:41.772 18469 DEBUG nova.network.os_vif_util [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:02:41.779 18469 DEBUG nova.objects.instance [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lazy-loading 'pci_devices' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:02:41.780 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 10956e71cfb64b43897683b7ac8aac98 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:41.794 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 10956e71cfb64b43897683b7ac8aac98 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:41.797 18469 DEBUG nova.virt.libvirt.driver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] End _get_guest_xml xml=<domain type="qemu">
  <uuid>f5a19c94-1a45-4ea0-9386-77c10705c825</uuid>
  <name>instance-00000018</name>
  <memory>524288</memory>
  <vcpu>1</vcpu>
  <metadata>
    <nova:instance xmlns:nova="http://openstack.org/xmlns/libvirt/nova/1.0">
      <nova:package version="0.0.0-1.el7.ceos"/>
      <nova:name>vm001</nova:name>
      <nova:creationTime>2019-03-29 02:02:40</nova:creationTime>
      <nova:flavor name="m1.tiny">
        <nova:memory>512</nova:memory>
        <nova:disk>1</nova:disk>
        <nova:swap>0</nova:swap>
        <nova:ephemeral>0</nova:ephemeral>
        <nova:vcpus>1</nova:vcpus>
      </nova:flavor>
      <nova:owner>
        <nova:user uuid="9e9e53917dda421083fa6af425c6bfbf">admin</nova:user>
        <nova:project uuid="d4bbd972ca1b463ba028ccd1df983917">admin</nova:project>
      </nova:owner>
    </nova:instance>
  </metadata>
  <sysinfo type="smbios">
    <system>
      <entry name="manufacturer">RDO</entry>
      <entry name="product">OpenStack Compute</entry>
      <entry name="version">0.0.0-1.el7.ceos</entry>
      <entry name="serial">b72f0c91-de47-47b5-9c10-43dfb0050cac</entry>
      <entry name="uuid">f5a19c94-1a45-4ea0-9386-77c10705c825</entry>
      <entry name="family">Virtual Machine</entry>
    </system>
  </sysinfo>
  <os>
    <type>hvm</type>
    <boot dev="hd"/>
    <smbios mode="sysinfo"/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cputune>
    <shares>1024</shares>
  </cputune>
  <clock offset="utc"/>
  <cpu match="exact">
    <topology sockets="1" cores="1" threads="1"/>
  </cpu>
  <devices>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw" cache="none"/>
      <source file="/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config"/>
      <target bus="ide" dev="hda"/>
    </disk>
    <disk type="block" device="disk">
      <driver name="qemu" type="raw" cache="none" io="native"/>
      <source dev="/dev/disk/by-path/ip-172.30.126.56:3260-iscsi-iqn.2010-10.org.openstack:volume-78a56ddc-ee21-4278-991e-17b30d68fa6e-lun-0"/>
      <target bus="virtio" dev="vda"/>
      <serial>78a56ddc-ee21-4278-991e-17b30d68fa6e</serial>
    </disk>
    <interface type="bridge">
      <mac address="fa:16:3e:29:72:d6"/>
      <model type="virtio"/>
      <driver name="qemu"/>
      <source bridge="qbrb3249515-3a"/>
      <target dev="tapb3249515-3a"/>
    </interface>
    <serial type="pty">
      <log file="/var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/console.log" append="off"/>
    </serial>
    <input type="tablet" bus="usb"/>
    <graphics type="vnc" autoport="yes" keymap="en-us" listen="0.0.0.0"/>
    <video>
      <model type="cirrus"/>
    </video>
    <memballoon model="virtio">
      <stats period="10"/>
    </memballoon>
  </devices>
</domain>
 _get_guest_xml /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:4978
2019-03-29 10:02:41.798 18469 DEBUG nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Preparing to wait for external event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a prepare_for_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:328
2019-03-29 10:02:41.798 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._create_or_get_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:02:41.799 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._create_or_get_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:02:41.801 18469 DEBUG nova.virt.libvirt.vif [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] vif_type=ovs instance=Instance(access_ip_v4=None,access_ip_v6=None,architecture='x86_64',auto_disk_config=True,availability_zone='nova',cell_name=None,cleaned=False,config_drive='True',created_at=2019-03-29T02:02:33Z,default_ephemeral_device=None,default_swap_device=None,deleted=False,deleted_at=None,device_metadata=None,disable_terminate=False,display_description='vm001',display_name='vm001',ec2_ids=EC2Ids,ephemeral_gb=0,ephemeral_key_uuid=None,fault=<?>,flavor=Flavor(1),host='com58',hostname='vm001',id=24,image_ref='',info_cache=InstanceInfoCache,instance_type_id=1,kernel_id='',key_data=None,key_name=None,keypairs=KeyPairList,launch_index=0,launched_at=None,launched_on='com58',locked=False,locked_by=None,memory_mb=512,metadata={},migration_context=<?>,new_flavor=None,node='com58',numa_topology=None,old_flavor=None,os_type=None,pci_devices=PciDeviceList,pci_requests=InstancePCIRequests,power_state=0,progress=0,project_id='d4bbd972ca1b463ba028ccd1df983917',ramdisk_id='',reservation_id='r-x56iqcqr',root_device_name='/dev/vda',root_gb=1,security_groups=SecurityGroupList,services=<?>,shutdown_terminate=False,system_metadata={boot_roles='admin',image_architecture='x86_64',image_base_image_ref='',image_min_disk='1',image_min_ram='0',network_allocated='True'},tags=<?>,task_state='spawning',terminated_at=None,updated_at=2019-03-29T02:02:35Z,user_data=None,user_id='9e9e53917dda421083fa6af425c6bfbf',uuid=f5a19c94-1a45-4ea0-9386-77c10705c825,vcpu_model=VirtCPUModel,vcpus=1,vm_mode=None,vm_state='building') vif={"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} plug /usr/lib/python2.7/site-packages/nova/virt/libvirt/vif.py:776
2019-03-29 10:02:41.802 18469 DEBUG nova.network.os_vif_util [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converting VIF {"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": false, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null} nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:413
2019-03-29 10:02:41.803 18469 DEBUG nova.network.os_vif_util [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Converted object VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') nova_to_osvif_vif /usr/lib/python2.7/site-packages/nova/network/os_vif_util.py:425
2019-03-29 10:02:41.804 18469 DEBUG os_vif [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Plugging vif VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a') plug /usr/lib/python2.7/site-packages/os_vif/__init__.py:79
2019-03-29 10:02:41.805 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'vif_plug_ovs.linux_net.ensure_bridge', (u'qbrb3249515-3a',), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.806 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl addbr qbrb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.815 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl addbr qbrb3249515-3a" returned: 0 in 0.007s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.815 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl setfd qbrb3249515-3a 0 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.819 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl setfd qbrb3249515-3a 0" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.819 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl stp qbrb3249515-3a off out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.823 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl stp qbrb3249515-3a off" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.823 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee /sys/class/net/qbrb3249515-3a/bridge/multicast_snooping out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.827 18469 DEBUG oslo.privsep.daemon [-] CMD "tee /sys/class/net/qbrb3249515-3a/bridge/multicast_snooping" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.828 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): tee /proc/sys/net/ipv6/conf/qbrb3249515-3a/disable_ipv6 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.830 18469 DEBUG oslo.privsep.daemon [-] CMD "tee /proc/sys/net/ipv6/conf/qbrb3249515-3a/disable_ipv6" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.830 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.832 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'vif_plug_ovs.linux_net.create_veth_pair', ('qvbb3249515-3a', 'qvob3249515-3a', 1500), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.832 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link add qvbb3249515-3a type veth peer name qvob3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.843 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link add qvbb3249515-3a type veth peer name qvob3249515-3a" returned: 0 in 0.010s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.843 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvbb3249515-3a up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.847 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvbb3249515-3a up" returned: 0 in 0.005s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.848 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvbb3249515-3a promisc on out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.859 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvbb3249515-3a promisc on" returned: 0 in 0.012s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.860 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvbb3249515-3a mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.862 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvbb3249515-3a mtu 1500" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.863 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.866 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a up" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.866 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a promisc on out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.870 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a promisc on" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.870 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.873 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a mtu 1500" returned: 0 in 0.003s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.873 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.874 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'vif_plug_ovs.linux_net.add_bridge_port', (u'qbrb3249515-3a', 'qvbb3249515-3a'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.874 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qbrb3249515-3a up out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.878 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qbrb3249515-3a up" returned: 0 in 0.004s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.878 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): brctl addif qbrb3249515-3a qvbb3249515-3a out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.883 18469 DEBUG oslo.privsep.daemon [-] CMD "brctl addif qbrb3249515-3a qvbb3249515-3a" returned: 0 in 0.006s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.884 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.890 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'vif_plug_ovs.linux_net.ensure_ovs_bridge', (u'br-int', 'system'), {}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.890 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl -- --may-exist add-br br-int -- set Bridge br-int datapath_type=system out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.899 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl -- --may-exist add-br br-int -- set Bridge br-int datapath_type=system" returned: 0 in 0.009s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.899 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.900 18469 DEBUG oslo.privsep.daemon [-] privsep: request[97285136]: (3, 'vif_plug_ovs.linux_net.create_ovs_vif_port', (u'br-int', 'qvob3249515-3a', 'b3249515-3aab-439f-ba9c-bc498756871a', u'fa:16:3e:29:72:d6', 'f5a19c94-1a45-4ea0-9386-77c10705c825', 1500), {'timeout': 120}) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.900 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ovs-vsctl --timeout=120 -- --if-exists del-port qvob3249515-3a -- add-port br-int qvob3249515-3a -- set Interface qvob3249515-3a external-ids:iface-id=b3249515-3aab-439f-ba9c-bc498756871a external-ids:iface-status=active external-ids:attached-mac=fa:16:3e:29:72:d6 external-ids:vm-uuid=f5a19c94-1a45-4ea0-9386-77c10705c825 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.948 18469 DEBUG oslo.privsep.daemon [-] CMD "ovs-vsctl --timeout=120 -- --if-exists del-port qvob3249515-3a -- add-port br-int qvob3249515-3a -- set Interface qvob3249515-3a external-ids:iface-id=b3249515-3aab-439f-ba9c-bc498756871a external-ids:iface-status=active external-ids:attached-mac=fa:16:3e:29:72:d6 external-ids:vm-uuid=f5a19c94-1a45-4ea0-9386-77c10705c825" returned: 0 in 0.043s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.949 18469 DEBUG oslo.privsep.daemon [-] Running cmd (subprocess): ip link set qvob3249515-3a mtu 1500 out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.955 18469 DEBUG oslo.privsep.daemon [-] CMD "ip link set qvob3249515-3a mtu 1500" returned: 0 in 0.011s out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.955 18469 DEBUG oslo.privsep.daemon [-] privsep: reply[97285136]: (4, None) out_of_band /usr/lib/python2.7/site-packages/oslo_privsep/daemon.py:194
2019-03-29 10:02:41.956 18469 INFO os_vif [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Successfully plugged vif VIFBridge(active=False,address=fa:16:3e:29:72:d6,bridge_name='qbrb3249515-3a',has_traffic_filtering=True,id=b3249515-3aab-439f-ba9c-bc498756871a,network=Network(968d1118-8921-4ef9-9cf6-534ff3d8bf7d),plugin='ovs',port_profile=VIFPortProfileBase,preserve_on_delete=False,vif_name='tapb3249515-3a')
2019-03-29 10:02:41.998 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: b66a8a27b7914ce48debaf3f2305d174 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:42.053 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b66a8a27b7914ce48debaf3f2305d174 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:42.055 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 26e20385e1cd4873b1a7f748df772a71 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:42.066 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 26e20385e1cd4873b1a7f748df772a71 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:42.071 18469 INFO nova.virt.libvirt.driver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Using config drive
2019-03-29 10:02:42.076 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 595a9c8976834228a985dea578a328b3 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:42.103 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 595a9c8976834228a985dea578a328b3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:42.168 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-9605c5a1-f8a5-488a-9b56-87e7eb17aaac _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:42.344 18469 DEBUG neutronclient.v2_0.client [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/security-groups.json?id=4ee28088-03e4-414f-88d4-3c593382000b used request id req-68a6063e-c53a-4601-bd47-feb850d95f23 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:42.346 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: b0f91a3dce564ed6b79ffce4ec33feef exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:42.364 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: b0f91a3dce564ed6b79ffce4ec33feef __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:42.367 18469 INFO nova.virt.libvirt.driver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Creating config drive at /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config
2019-03-29 10:02:42.371 18469 DEBUG oslo_concurrency.processutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Running cmd (subprocess): genisoimage -o /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config -ldots -allow-lowercase -allow-multidot -l -publisher OpenStack Compute 0.0.0-1.el7.ceos -quiet -J -r -V config-2 /tmp/tmpn7Rrty execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:355
2019-03-29 10:02:42.390 18469 DEBUG oslo_concurrency.processutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CMD "genisoimage -o /var/lib/nova/instances/f5a19c94-1a45-4ea0-9386-77c10705c825/disk.config -ldots -allow-lowercase -allow-multidot -l -publisher OpenStack Compute 0.0.0-1.el7.ceos -quiet -J -r -V config-2 /tmp/tmpn7Rrty" returned: 0 in 0.020s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:385
2019-03-29 10:02:42.610 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553824962.61, f5a19c94-1a45-4ea0-9386-77c10705c825 => Started> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:02:42.611 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Started (Lifecycle Event)
2019-03-29 10:02:42.612 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 1f5b34a9ef1e4488b15207faa1bb801c exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:42.655 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 1f5b34a9ef1e4488b15207faa1bb801c __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:42.657 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:02:42.659 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553824962.61, f5a19c94-1a45-4ea0-9386-77c10705c825 => Paused> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:02:42.660 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Paused (Lifecycle Event)
2019-03-29 10:02:42.661 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 39a0d2771b4e4eb6a319f9c06029b5a3 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:42.706 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 39a0d2771b4e4eb6a319f9c06029b5a3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:42.707 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:02:42.709 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Synchronizing instance power state after lifecycle event "Paused"; current vm_state: building, current task_state: spawning, current DB power_state: 0, VM power_state: 3 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:02:42.711 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 02bc5f8e07854627855250b26bf585a1 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:42.758 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 02bc5f8e07854627855250b26bf585a1 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:42.758 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] During sync_power_state the instance has a pending task (spawning). Skip.
2019-03-29 10:02:45.209 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received message with unique_id: 1b4e52efc04b46abb8e3fe8e345c9ab3 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:257
2019-03-29 10:02:45.214 18469 DEBUG nova.compute.manager [req-95a1e42b-61ae-4fa7-9641-9e0e6082fe3f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Received event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6861
2019-03-29 10:02:45.214 18469 DEBUG oslo_concurrency.lockutils [req-95a1e42b-61ae-4fa7-9641-9e0e6082fe3f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" acquired by "nova.compute.manager._pop_event" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-03-29 10:02:45.215 18469 DEBUG oslo_concurrency.lockutils [req-95a1e42b-61ae-4fa7-9641-9e0e6082fe3f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825-events" released by "nova.compute.manager._pop_event" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:02:45.215 18469 DEBUG nova.compute.manager [req-95a1e42b-61ae-4fa7-9641-9e0e6082fe3f 92aab8401906424bbc6df9e557586649 a77dc037ca704f3883e8ed733fff997f - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Processing event network-vif-plugged-b3249515-3aab-439f-ba9c-bc498756871a _process_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6816
2019-03-29 10:02:45.223 18469 DEBUG nova.virt.libvirt.driver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance is running spawn /usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py:2757
2019-03-29 10:02:45.224 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553824965.22, f5a19c94-1a45-4ea0-9386-77c10705c825 => Resumed> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:02:45.225 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Resumed (Lifecycle Event)
2019-03-29 10:02:45.226 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 0be318604cfa4c059df9a70ee423385f exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:45.229 18469 INFO nova.virt.libvirt.driver [-] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Instance spawned successfully.
2019-03-29 10:02:45.229 18469 INFO nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Took 4.69 seconds to spawn the instance on the hypervisor.
2019-03-29 10:02:45.230 18469 DEBUG nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:02:45.235 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: bd82f04953484f60b6149a36a83f0330 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:45.287 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0be318604cfa4c059df9a70ee423385f __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:45.288 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:02:45.290 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Synchronizing instance power state after lifecycle event "Resumed"; current vm_state: building, current task_state: spawning, current DB power_state: 0, VM power_state: 1 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:02:45.292 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: f15af32c7b7c4fe59078b3d82bfc6580 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:45.372 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: f15af32c7b7c4fe59078b3d82bfc6580 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:45.373 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] During sync_power_state the instance has a pending task (spawning). Skip.
2019-03-29 10:02:45.374 18469 DEBUG nova.virt.driver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] Emitting event <LifecycleEvent: 1553824965.22, f5a19c94-1a45-4ea0-9386-77c10705c825 => Resumed> emit_event /usr/lib/python2.7/site-packages/nova/virt/driver.py:1438
2019-03-29 10:02:45.374 18469 INFO nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] VM Resumed (Lifecycle Event)
2019-03-29 10:02:45.376 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 4e9462e23ea043d3ba61062577e07cf6 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:45.411 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: bd82f04953484f60b6149a36a83f0330 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:45.418 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CAST unique_id: 04736137abbf4166b8a2295e681b10c0 FANOUT topic 'scheduler' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:539
2019-03-29 10:02:45.424 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 4e9462e23ea043d3ba61062577e07cf6 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:45.425 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Checking state _get_power_state /usr/lib/python2.7/site-packages/nova/compute/manager.py:1176
2019-03-29 10:02:45.426 18469 WARNING nova.image.glance [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] No protocol specified in for api_server 'http://172.30.126.56:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2019-03-29 10:02:45.429 18469 INFO nova.compute.manager [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Took 11.18 seconds to build instance.
2019-03-29 10:02:45.430 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] CALL msg_id: 680a28729c624c03b42ce2f385e95dcc exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:45.434 18469 DEBUG nova.compute.manager [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Synchronizing instance power state after lifecycle event "Resumed"; current vm_state: active, current task_state: None, current DB power_state: 1, VM power_state: 1 handle_lifecycle_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:1088
2019-03-29 10:02:45.436 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-054e3bb9-67aa-419d-9dbf-bf142ec1b6d8 - - - - -] CALL msg_id: 3c09569e33404456b20b0e6e8d9d3814 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:45.482 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 3c09569e33404456b20b0e6e8d9d3814 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:45.488 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 680a28729c624c03b42ce2f385e95dcc __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:45.489 18469 DEBUG oslo_concurrency.lockutils [req-040bfbf2-43e2-40ff-a56c-1fd8a7281f7c 9e9e53917dda421083fa6af425c6bfbf d4bbd972ca1b463ba028ccd1df983917 - - -] Lock "f5a19c94-1a45-4ea0-9386-77c10705c825" released by "nova.compute.manager._locked_do_build_and_run_instance" :: held 11.384s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-03-29 10:02:45.893 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: 5ab07e1129684952b1a75562096b068e exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:45.931 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5ab07e1129684952b1a75562096b068e __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:48.701 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._instance_usage_audit run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:50.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_rebooting_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:50.700 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._heal_instance_info_cache run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:50.701 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Starting heal instance info cache _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5884
2019-03-29 10:02:50.701 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Rebuilding the list of instances to heal _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5888
2019-03-29 10:02:50.702 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 0c182c6789c84135823565f44b429941 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:50.729 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 0c182c6789c84135823565f44b429941 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:50.730 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Acquired semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-03-29 10:02:50.730 18469 DEBUG nova.network.neutronv2.api [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1295
2019-03-29 10:02:50.731 18469 DEBUG nova.objects.instance [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Lazy-loading 'info_cache' on Instance uuid f5a19c94-1a45-4ea0-9386-77c10705c825 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1034
2019-03-29 10:02:50.732 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 5d02bb2e067a485c81be036b888d5a92 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:50.778 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 5d02bb2e067a485c81be036b888d5a92 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:50.779 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 078977dad2bc44bd900cef1d7c450580 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:50.788 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 078977dad2bc44bd900cef1d7c450580 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:50.855 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?tenant_id=d4bbd972ca1b463ba028ccd1df983917&device_id=f5a19c94-1a45-4ea0-9386-77c10705c825 used request id req-fbf8b97e-0d96-4034-8887-e04499121d84 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:50.963 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/networks.json?id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d used request id req-d13d7910-5cd4-4dcc-b689-6a54f37d246c _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:50.983 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/floatingips.json?fixed_ip_address=10.10.10.11&port_id=b3249515-3aab-439f-ba9c-bc498756871a used request id req-64c8b3f6-0eb9-43ee-8030-79676c04b297 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:51.044 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/subnets.json?id=b9f5b815-a0ab-4476-a216-6b824fda2957 used request id req-2572247f-874b-4eed-980a-971220ed820c _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:51.089 18469 DEBUG neutronclient.v2_0.client [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] GET call to neutron for http://172.30.126.56:9696/v2.0/ports.json?network_id=968d1118-8921-4ef9-9cf6-534ff3d8bf7d&device_owner=network%3Adhcp used request id req-7c8ed471-31ad-400f-a6ee-80640017d538 _append_request_id /usr/lib/python2.7/site-packages/neutronclient/v2_0/client.py:128
2019-03-29 10:02:51.090 18469 DEBUG nova.network.base_api [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "b3249515-3aab-439f-ba9c-bc498756871a", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.10.10.11"}], "version": 4, "meta": {}, "dns": [], "routes": [], "cidr": "10.10.10.0/24", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.10.10.1"}}], "meta": {"injected": false, "tenant_id": "d4bbd972ca1b463ba028ccd1df983917", "mtu": 1500}, "id": "968d1118-8921-4ef9-9cf6-534ff3d8bf7d", "label": "net10"}, "devname": "tapb3249515-3a", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:29:72:d6", "active": true, "type": "ovs", "id": "b3249515-3aab-439f-ba9c-bc498756871a", "qbg_params": null}] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
2019-03-29 10:02:51.091 18469 DEBUG oslo_messaging._drivers.amqpdriver [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] CALL msg_id: 58058ef4fcf84c318e07376ef2db7041 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:51.117 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: 58058ef4fcf84c318e07376ef2db7041 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
2019-03-29 10:02:51.118 18469 DEBUG oslo_concurrency.lockutils [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Releasing semaphore "refresh_cache-f5a19c94-1a45-4ea0-9386-77c10705c825" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-03-29 10:02:51.118 18469 DEBUG nova.compute.manager [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] [instance: f5a19c94-1a45-4ea0-9386-77c10705c825] Updated the network info_cache for instance _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5946
2019-03-29 10:02:52.118 18469 DEBUG oslo_service.periodic_task [req-7d4ff131-cff3-4e9f-80c4-65e5cb9752cb - - - - -] Running periodic task ComputeManager._poll_unconfirmed_resizes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2019-03-29 10:02:55.894 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] CALL msg_id: ed65733d2629477ca4af46c73c578b42 exchange 'nova' topic 'conductor' _send /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:550
2019-03-29 10:02:55.925 18469 DEBUG oslo_messaging._drivers.amqpdriver [-] received reply msg_id: ed65733d2629477ca4af46c73c578b42 __call__ /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py:407
