2019-09-11 19:19:57.216 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmpzQU6U4 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:19:57.238 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmpzQU6U4 power status" returned: 0 in 0.021s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:19:57.239 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmpzQU6U4 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:19:57.239 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:19:57.240 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:19:57.240 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:19:57.242 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 55f1e507-7aac-4efa-b702-c782ad86831d (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:02.241 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpbXhga8 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:02.266 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpbXhga8 power status" returned: 0 in 0.025s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:02.268 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpbXhga8 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:02.268 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:02.269 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:02.270 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 55f1e507-7aac-4efa-b702-c782ad86831d (lock was held 5.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:02.272 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:07.270 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpuCy_cZ power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:07.290 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpuCy_cZ power status" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:07.291 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpuCy_cZ power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:07.292 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:07.292 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:07.293 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:13.517 19431 DEBUG ironic.conductor.manager [req-1aa00180-2db8-431b-a6bf-fb88e0fa3f96 - - - - -] RPC update_node called for node caa8cab2-61d5-49cb-a7a2-0179429b77e9. update_node /usr/lib/python2.7/site-packages/ironic/conductor/manager.py:215
2019-09-11 19:20:13.518 19431 DEBUG ironic.conductor.task_manager [req-1aa00180-2db8-431b-a6bf-fb88e0fa3f96 - - - - -] Attempting to get exclusive lock on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (for node update) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:13.531 19431 DEBUG ironic.conductor.task_manager [req-1aa00180-2db8-431b-a6bf-fb88e0fa3f96 - - - - -] Node caa8cab2-61d5-49cb-a7a2-0179429b77e9 successfully reserved for node update (took 0.01 seconds) reserve_node /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:266
2019-09-11 19:20:13.557 19431 DEBUG ironic.conductor.task_manager [req-1aa00180-2db8-431b-a6bf-fb88e0fa3f96 - - - - -] Successfully released exclusive lock for node update on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (lock was held 0.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:13.602 19431 DEBUG ironic.conductor.manager [req-7517106e-163b-4eaa-89b8-6cd693095546 - - - - -] RPC validate_driver_interfaces called for node caa8cab2-61d5-49cb-a7a2-0179429b77e9. validate_driver_interfaces /usr/lib/python2.7/site-packages/ironic/conductor/manager.py:1457
2019-09-11 19:20:13.603 19431 DEBUG ironic.conductor.task_manager [req-7517106e-163b-4eaa-89b8-6cd693095546 - - - - -] Attempting to get shared lock on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (for driver interface validation) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:13.618 19431 DEBUG ironic.common.glance_service.base_image_service [req-7517106e-163b-4eaa-89b8-6cd693095546 - - - - -] Getting image metadata from glance. Image: a92aab99-6fcf-4464-b694-9402059fa858 _show /usr/lib/python2.7/site-packages/ironic/common/glance_service/base_image_service.py:182
2019-09-11 19:20:14.016 19431 DEBUG ironic.drivers.modules.deploy_utils [req-7517106e-163b-4eaa-89b8-6cd693095546 - - - - -] Deploy boot mode is None for caa8cab2-61d5-49cb-a7a2-0179429b77e9. get_boot_mode_for_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:796
2019-09-11 19:20:14.018 19431 DEBUG ironic.common.glance_service.base_image_service [req-7517106e-163b-4eaa-89b8-6cd693095546 - - - - -] Getting image metadata from glance. Image: a92aab99-6fcf-4464-b694-9402059fa858 _show /usr/lib/python2.7/site-packages/ironic/common/glance_service/base_image_service.py:182
2019-09-11 19:20:14.169 19431 DEBUG ironic.drivers.modules.deploy_utils [req-7517106e-163b-4eaa-89b8-6cd693095546 - - - - -] Deploy boot mode is None for caa8cab2-61d5-49cb-a7a2-0179429b77e9. get_boot_mode_for_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:796
2019-09-11 19:20:14.171 19431 DEBUG ironic.common.glance_service.base_image_service [req-7517106e-163b-4eaa-89b8-6cd693095546 - - - - -] Getting image metadata from glance. Image: a92aab99-6fcf-4464-b694-9402059fa858 _show /usr/lib/python2.7/site-packages/ironic/common/glance_service/base_image_service.py:182
2019-09-11 19:20:14.377 19431 DEBUG ironic.conductor.task_manager [req-7517106e-163b-4eaa-89b8-6cd693095546 - - - - -] Successfully released shared lock for driver interface validation on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (lock was held 0.77 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:14.500 19431 DEBUG ironic.conductor.manager [req-a28b8b4f-4f5f-429a-a0b1-ecf0c2519f6d - - - - -] RPC update_port called for port f0e6da7f-4d0e-4c64-8647-71e4761fc2eb. update_port /usr/lib/python2.7/site-packages/ironic/conductor/manager.py:1713
2019-09-11 19:20:14.502 19431 DEBUG ironic.conductor.task_manager [req-a28b8b4f-4f5f-429a-a0b1-ecf0c2519f6d - - - - -] Attempting to get exclusive lock on node 16 (for port update) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:14.520 19431 DEBUG ironic.conductor.task_manager [req-a28b8b4f-4f5f-429a-a0b1-ecf0c2519f6d - - - - -] Node caa8cab2-61d5-49cb-a7a2-0179429b77e9 successfully reserved for port update (took 0.02 seconds) reserve_node /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:266
2019-09-11 19:20:14.545 19431 DEBUG ironic.conductor.task_manager [req-a28b8b4f-4f5f-429a-a0b1-ecf0c2519f6d - - - - -] Successfully released exclusive lock for port update on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (lock was held 0.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:14.763 19431 DEBUG ironic.conductor.manager [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] RPC do_node_deploy called for node caa8cab2-61d5-49cb-a7a2-0179429b77e9. do_node_deploy /usr/lib/python2.7/site-packages/ironic/conductor/manager.py:506
2019-09-11 19:20:14.765 19431 DEBUG ironic.conductor.task_manager [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Attempting to get exclusive lock on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (for node deployment) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:14.779 19431 DEBUG ironic.conductor.task_manager [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Node caa8cab2-61d5-49cb-a7a2-0179429b77e9 successfully reserved for node deployment (took 0.01 seconds) reserve_node /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:266
2019-09-11 19:20:14.790 19431 DEBUG ironic.common.glance_service.base_image_service [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Getting image metadata from glance. Image: a92aab99-6fcf-4464-b694-9402059fa858 _show /usr/lib/python2.7/site-packages/ironic/common/glance_service/base_image_service.py:182
2019-09-11 19:20:14.859 19431 DEBUG ironic.drivers.modules.deploy_utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Deploy boot mode is None for caa8cab2-61d5-49cb-a7a2-0179429b77e9. get_boot_mode_for_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:796
2019-09-11 19:20:14.860 19431 DEBUG ironic.common.glance_service.base_image_service [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Getting image metadata from glance. Image: a92aab99-6fcf-4464-b694-9402059fa858 _show /usr/lib/python2.7/site-packages/ironic/common/glance_service/base_image_service.py:182
2019-09-11 19:20:14.921 19431 DEBUG ironic.conductor.manager [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] do_node_deploy Calling event: deploy for node: caa8cab2-61d5-49cb-a7a2-0179429b77e9 do_node_deploy /usr/lib/python2.7/site-packages/ironic/conductor/manager.py:557
2019-09-11 19:20:14.922 19431 DEBUG ironic.common.states [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Exiting old state 'available' in response to event 'deploy' on_exit /usr/lib/python2.7/site-packages/ironic/common/states.py:203
2019-09-11 19:20:14.923 19431 DEBUG ironic.common.states [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Entering new state 'deploying' in response to event 'deploy' on_enter /usr/lib/python2.7/site-packages/ironic/common/states.py:209
2019-09-11 19:20:14.953 19431 DEBUG ironic.drivers.modules.deploy_utils [-] Deploy boot mode is None for caa8cab2-61d5-49cb-a7a2-0179429b77e9. get_boot_mode_for_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:796
2019-09-11 19:20:14.953 19431 DEBUG ironic.drivers.modules.deploy_utils [-] Deploy boot mode is None for caa8cab2-61d5-49cb-a7a2-0179429b77e9. get_boot_mode_for_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:796
2019-09-11 19:20:15.272 19431 DEBUG ironic.drivers.modules.deploy_utils [-] Deploy boot mode is None for caa8cab2-61d5-49cb-a7a2-0179429b77e9. get_boot_mode_for_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:796
2019-09-11 19:20:15.273 19431 DEBUG ironic.common.pxe_utils [-] Building PXE config for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 create_pxe_config /usr/lib/python2.7/site-packages/ironic/common/pxe_utils.py:215
2019-09-11 19:20:15.274 19431 DEBUG ironic.drivers.modules.deploy_utils [-] Deploy boot mode is None for caa8cab2-61d5-49cb-a7a2-0179429b77e9. get_boot_mode_for_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:796
2019-09-11 19:20:15.287 19431 DEBUG ironic.drivers.modules.ipmitool [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Sending node caa8cab2-61d5-49cb-a7a2-0179429b77e9 raw bytes 0x00 0x08 0x03 0x08 send_raw /usr/lib/python2.7/site-packages/ironic/drivers/modules/ipmitool.py:662
2019-09-11 19:20:15.288 19431 DEBUG oslo_concurrency.processutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmplzl8Fd raw 0x00 0x08 0x03 0x08 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:15.304 19431 DEBUG oslo_concurrency.processutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmplzl8Fd raw 0x00 0x08 0x03 0x08" returned: 0 in 0.016s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:15.305 19431 DEBUG ironic.common.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmplzl8Fd raw 0x00 0x08 0x03 0x08" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:15.306 19431 DEBUG ironic.common.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Command stdout is: "
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:15.306 19431 DEBUG ironic.common.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:15.307 19431 DEBUG ironic.drivers.modules.ipmitool [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] send raw bytes returned stdout: 
, stderr:  send_raw /usr/lib/python2.7/site-packages/ironic/drivers/modules/ipmitool.py:669
2019-09-11 19:20:16.439 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._sync_local_state' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:20:16.710 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_cleanwait_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:20:16.715 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploy_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:20:16.723 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploying_status' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:20:16.737 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_inspect_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:20:16.746 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._sync_power_states' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:20:16.753 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:20.307 19431 DEBUG oslo_concurrency.processutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpmCJQ5l chassis bootdev pxe options=persistent execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:20.317 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpcowj5C power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:20.335 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpcowj5C power status" returned: 0 in 0.018s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:20.336 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpcowj5C power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:20.337 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:20.337 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:20.338 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (lock was held 3.58 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:20.340 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node a8e8ac97-871a-4043-9b62-027b1e72599f (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:20.404 19431 DEBUG oslo_concurrency.processutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpmCJQ5l chassis bootdev pxe options=persistent" returned: 0 in 0.096s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:20.405 19431 DEBUG ironic.common.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpmCJQ5l chassis bootdev pxe options=persistent" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:20.405 19431 DEBUG ironic.common.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Command stdout is: "Set Boot Device to pxe
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:20.406 19431 DEBUG ironic.common.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:20.407 19431 DEBUG ironic.drivers.modules.pxe [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Fetching necessary kernel and ramdisk for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 _cache_ramdisk_kernel /usr/lib/python2.7/site-packages/ironic/drivers/modules/pxe.py:350
2019-09-11 19:20:20.408 19431 DEBUG ironic.common.glance_service.base_image_service [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Getting image metadata from glance. Image: 2655b7dc-d4fe-48d4-9ae1-c868ee124b27 _show /usr/lib/python2.7/site-packages/ironic/common/glance_service/base_image_service.py:182
2019-09-11 19:20:20.571 19431 DEBUG ironic.common.glance_service.base_image_service [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Getting image metadata from glance. Image: 9a398412-0f94-438a-ba77-95d66e127049 _show /usr/lib/python2.7/site-packages/ironic/common/glance_service/base_image_service.py:182
2019-09-11 19:20:20.725 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Acquired semaphore "download-image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-09-11 19:20:20.725 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Acquired semaphore "master_image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-09-11 19:20:20.726 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Releasing semaphore "master_image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-09-11 19:20:20.726 19431 DEBUG ironic.drivers.modules.image_cache [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Master cache hit for image 2655b7dc-d4fe-48d4-9ae1-c868ee124b27 fetch_image /usr/lib/python2.7/site-packages/ironic/drivers/modules/image_cache.py:141
2019-09-11 19:20:20.726 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Releasing semaphore "download-image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-09-11 19:20:20.727 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Acquired semaphore "download-image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-09-11 19:20:20.727 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Acquired semaphore "master_image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-09-11 19:20:20.728 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Releasing semaphore "master_image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-09-11 19:20:20.728 19431 DEBUG ironic.drivers.modules.image_cache [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Master cache hit for image 9a398412-0f94-438a-ba77-95d66e127049 fetch_image /usr/lib/python2.7/site-packages/ironic/drivers/modules/image_cache.py:141
2019-09-11 19:20:20.729 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Releasing semaphore "download-image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-09-11 19:20:20.734 19431 DEBUG ironic.drivers.modules.iscsi_deploy [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Fetching image a92aab99-6fcf-4464-b694-9402059fa858 for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 cache_instance_image /usr/lib/python2.7/site-packages/ironic/drivers/modules/iscsi_deploy.py:162
2019-09-11 19:20:20.735 19431 DEBUG ironic.common.glance_service.base_image_service [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Getting image metadata from glance. Image: a92aab99-6fcf-4464-b694-9402059fa858 _show /usr/lib/python2.7/site-packages/ironic/common/glance_service/base_image_service.py:182
2019-09-11 19:20:20.786 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Acquired semaphore "download-image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-09-11 19:20:20.786 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Acquired semaphore "master_image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
2019-09-11 19:20:20.787 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Releasing semaphore "master_image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-09-11 19:20:20.787 19431 DEBUG ironic.drivers.modules.image_cache [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Master cache hit for image a92aab99-6fcf-4464-b694-9402059fa858 fetch_image /usr/lib/python2.7/site-packages/ironic/drivers/modules/image_cache.py:141
2019-09-11 19:20:20.788 19431 DEBUG oslo_concurrency.lockutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Releasing semaphore "download-image" lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
2019-09-11 19:20:20.788 19431 DEBUG oslo_concurrency.processutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Running cmd (subprocess): env LC_ALL=C LANG=C qemu-img info /var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:20.865 19431 DEBUG oslo_concurrency.processutils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] CMD "env LC_ALL=C LANG=C qemu-img info /var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk" returned: 0 in 0.077s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:20.867 19431 DEBUG ironic_lib.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Execution completed, command line is "env LC_ALL=C LANG=C qemu-img info /var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:74
2019-09-11 19:20:20.867 19431 DEBUG ironic_lib.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Command stdout is: "image: /var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk
file format: raw
virtual size: 20G (21474836480 bytes)
disk size: 1.4G
" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:75
2019-09-11 19:20:20.868 19431 DEBUG ironic_lib.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:76
2019-09-11 19:20:25.339 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpT7dxmm power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:25.358 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpT7dxmm power status" returned: 0 in 0.020s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:25.359 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpT7dxmm power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:25.360 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:25.360 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:25.361 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node a8e8ac97-871a-4043-9b62-027b1e72599f (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:25.363 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:25.407 19431 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpYT5MA8 power off execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:25.426 19431 DEBUG oslo_concurrency.processutils [-] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpYT5MA8 power off" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:25.427 19431 DEBUG ironic.common.utils [-] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpYT5MA8 power off" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:25.427 19431 DEBUG ironic.common.utils [-] Command stdout is: "Chassis Power Control: Down/Off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:25.428 19431 DEBUG ironic.common.utils [-] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:30.361 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmptRf3P4 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:30.385 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmptRf3P4 power status" returned: 0 in 0.023s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:30.386 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmptRf3P4 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:30.387 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:30.388 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:30.389 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (lock was held 5.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:30.391 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:30.429 19431 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmphie9qz power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:30.448 19431 DEBUG oslo_concurrency.processutils [-] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmphie9qz power status" returned: 0 in 0.020s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:30.449 19431 DEBUG ironic.common.utils [-] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmphie9qz power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:30.450 19431 DEBUG ironic.common.utils [-] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:30.451 19431 DEBUG ironic.common.utils [-] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:35.389 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpFsCmTK power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:35.409 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpFsCmTK power status" returned: 0 in 0.020s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:35.410 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpFsCmTK power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:35.410 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:35.411 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:35.412 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:35.422 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:35.452 19431 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpZRWzm8 power on execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:35.915 19431 DEBUG oslo_concurrency.processutils [-] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpZRWzm8 power on" returned: 0 in 0.464s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:35.917 19431 DEBUG ironic.common.utils [-] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpZRWzm8 power on" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:35.917 19431 DEBUG ironic.common.utils [-] Command stdout is: "Chassis Power Control: Up/On
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:35.918 19431 DEBUG ironic.common.utils [-] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:40.412 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmpFDvrCz power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:40.435 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmpFDvrCz power status" returned: 0 in 0.023s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:40.435 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmpFDvrCz power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:40.436 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:40.436 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:40.437 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (lock was held 5.01 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:40.439 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:40.919 19431 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpyVnUT0 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:40.938 19431 DEBUG oslo_concurrency.processutils [-] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpyVnUT0 power status" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:40.939 19431 DEBUG ironic.common.utils [-] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpyVnUT0 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:40.940 19431 DEBUG ironic.common.utils [-] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:40.940 19431 DEBUG ironic.common.utils [-] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:40.941 19431 INFO ironic.conductor.utils [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Successfully set node caa8cab2-61d5-49cb-a7a2-0179429b77e9 power state to power on.
2019-09-11 19:20:40.967 19431 DEBUG ironic.common.states [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Exiting old state 'deploying' in response to event 'wait' on_exit /usr/lib/python2.7/site-packages/ironic/common/states.py:203
2019-09-11 19:20:40.967 19431 DEBUG ironic.common.states [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Entering new state 'wait call-back' in response to event 'wait' on_enter /usr/lib/python2.7/site-packages/ironic/common/states.py:209
2019-09-11 19:20:40.998 19431 DEBUG ironic.conductor.task_manager [req-94cd1cdd-fc17-4a4e-9e2a-c85050bb3e79 - - - - -] Successfully released exclusive lock for node deployment on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (lock was held 26.22 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:45.438 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpT1Xs_L power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:45.454 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpT1Xs_L power status" returned: 0 in 0.016s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:45.454 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpT1Xs_L power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:45.455 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:45.455 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:45.456 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:45.457 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 101c2579-2698-4377-92cf-81f2b84d00a2 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:50.456 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpNNDuPF power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:50.479 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpNNDuPF power status" returned: 0 in 0.023s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:50.480 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpNNDuPF power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:50.481 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:50.481 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:50.482 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 101c2579-2698-4377-92cf-81f2b84d00a2 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:50.483 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:20:55.482 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmp57ZdZo power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:20:55.497 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmp57ZdZo power status" returned: 0 in 0.015s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:20:55.498 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmp57ZdZo power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:20:55.498 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:20:55.498 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:20:55.499 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:20:55.500 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 55f1e507-7aac-4efa-b702-c782ad86831d (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:00.499 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpQtRdj1 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:00.513 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpQtRdj1 power status" returned: 0 in 0.014s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:00.514 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpQtRdj1 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:00.514 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:00.514 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:00.515 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 55f1e507-7aac-4efa-b702-c782ad86831d (lock was held 5.01 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:00.516 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:05.515 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpvDw3Og power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:05.531 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpvDw3Og power status" returned: 0 in 0.016s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:05.531 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpvDw3Og power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:05.532 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:05.532 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:05.533 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:16.357 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._send_sensor_data' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:21:16.711 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_cleanwait_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:21:16.718 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploy_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:21:16.726 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploying_status' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:21:16.738 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_inspect_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:21:16.746 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._sync_power_states' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:21:16.752 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:16.769 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpH43YjN power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:16.790 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpH43YjN power status" returned: 0 in 0.021s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:16.790 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpH43YjN power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:16.791 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:16.791 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:16.792 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (lock was held 0.04 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:16.793 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node a8e8ac97-871a-4043-9b62-027b1e72599f (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:21.792 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpNWuPpB power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:21.810 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpNWuPpB power status" returned: 0 in 0.018s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:21.811 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpNWuPpB power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:21.812 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:21.812 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:21.813 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node a8e8ac97-871a-4043-9b62-027b1e72599f (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:21.814 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:26.813 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmpOvTUYE power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:26.830 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmpOvTUYE power status" returned: 0 in 0.017s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:26.831 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmpOvTUYE power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:26.832 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:26.832 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:26.833 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:26.835 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:26.857 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (lock was held 0.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:26.858 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:28.383 19431 DEBUG ironic.conductor.manager [req-1a86d061-c34e-4529-9b55-b5d1c081eea4 - - - - -] RPC driver_vendor_passthru for driver pxe_ipmitool. driver_vendor_passthru /usr/lib/python2.7/site-packages/ironic/conductor/manager.py:397
2019-09-11 19:21:28.383 19431 DEBUG ironic.drivers.modules.agent_base_vendor [req-1a86d061-c34e-4529-9b55-b5d1c081eea4 - - - - -] Agent lookup using data {u'version': u'2', 'http_method': u'POST', u'inventory': {u'bmc_address': u'', u'interfaces': [{u'name': u'eth0', u'has_carrier': True, u'switch_port_descr': None, u'switch_chassis_descr': None, u'ipv4_address': u'172.25.128.122', u'mac_address': u'52:54:00:6b:84:9e'}], u'disks': [{u'rotational': True, u'vendor': u'0x1af4', u'name': u'/dev/vda', u'wwn_vendor_extension': None, u'wwn_with_extension': None, u'model': u'', u'wwn': None, u'serial': None, u'size': 21474836480}], u'system_vendor': {u'serial_number': u'Not Specified', u'product_name': u'KVM', u'manufacturer': u'Red Hat'}, u'memory': {u'physical_mb': 4096, u'total': 4142325760}, u'cpu': {u'count': 2, u'frequency': u'2199.988', u'model_name': u'Intel Core Processor (Broadwell)', u'architecture': u'x86_64'}}} lookup /usr/lib/python2.7/site-packages/ironic/drivers/modules/agent_base_vendor.py:524
2019-09-11 19:21:28.400 19431 INFO ironic.drivers.modules.agent_base_vendor [req-1a86d061-c34e-4529-9b55-b5d1c081eea4 - - - - -] Initial lookup for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 succeeded, agent is running and waiting for commands
2019-09-11 19:21:28.491 19431 DEBUG ironic.conductor.manager [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] RPC vendor_passthru called for node caa8cab2-61d5-49cb-a7a2-0179429b77e9. vendor_passthru /usr/lib/python2.7/site-packages/ironic/conductor/manager.py:310
2019-09-11 19:21:28.492 19431 DEBUG ironic.conductor.task_manager [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Attempting to get exclusive lock on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (for calling vendor passthru) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:28.511 19431 DEBUG ironic.conductor.task_manager [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Node caa8cab2-61d5-49cb-a7a2-0179429b77e9 successfully reserved for calling vendor passthru (took 0.02 seconds) reserve_node /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:266
2019-09-11 19:21:28.523 19431 DEBUG ironic.drivers.modules.agent_base_vendor [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Heartbeat from caa8cab2-61d5-49cb-a7a2-0179429b77e9, last heartbeat at 1568200096. heartbeat /usr/lib/python2.7/site-packages/ironic/drivers/modules/agent_base_vendor.py:411
2019-09-11 19:21:28.534 19431 DEBUG ironic.common.states [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Exiting old state 'wait call-back' in response to event 'resume' on_exit /usr/lib/python2.7/site-packages/ironic/common/states.py:203
2019-09-11 19:21:28.535 19431 DEBUG ironic.common.states [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Entering new state 'deploying' in response to event 'resume' on_enter /usr/lib/python2.7/site-packages/ironic/common/states.py:209
2019-09-11 19:21:28.544 19431 DEBUG ironic.drivers.modules.iscsi_deploy [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Continuing the deployment on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 continue_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/iscsi_deploy.py:859
2019-09-11 19:21:28.553 19431 DEBUG ironic.drivers.modules.deploy_utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Deploy boot mode is None for caa8cab2-61d5-49cb-a7a2-0179429b77e9. get_boot_mode_for_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:796
2019-09-11 19:21:28.554 19431 DEBUG ironic.drivers.modules.agent_client [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Executing agent command iscsi.start_iscsi_target for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 _command /usr/lib/python2.7/site-packages/ironic/drivers/modules/agent_client.py:69
2019-09-11 19:21:28.710 19431 DEBUG ironic.drivers.modules.agent_client [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Agent command iscsi.start_iscsi_target for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 returned result {u'iscsi_target_iqn': u'iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9'}, error None, HTTP status code 200 _command /usr/lib/python2.7/site-packages/ironic/drivers/modules/agent_client.py:99
2019-09-11 19:21:28.711 19431 DEBUG ironic.drivers.modules.iscsi_deploy [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Continuing deployment for node caa8cab2-61d5-49cb-a7a2-0179429b77e9, params {'node_uuid': 'caa8cab2-61d5-49cb-a7a2-0179429b77e9', 'image_path': '/var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk', 'iqn': 'iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9', 'address': u'172.25.128.122', 'port': '3260', 'lun': '1'} continue_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/iscsi_deploy.py:278
2019-09-11 19:21:28.712 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m discovery -t st -p 172.25.128.122:3260 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:28.821 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m discovery -t st -p 172.25.128.122:3260" returned: 0 in 0.109s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:28.822 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "iscsiadm -m discovery -t st -p 172.25.128.122:3260" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:28.823 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "172.25.128.122:3260,1 iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:28.823 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:28.824 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -p 172.25.128.122:3260 -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 --login execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:28.955 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -p 172.25.128.122:3260 -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 --login" returned: 0 in 0.131s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:28.956 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "iscsiadm -m node -p 172.25.128.122:3260 -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 --login" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:28.956 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "Logging in to [iface: default, target: iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9, portal: 172.25.128.122,3260] (multiple)
Login to [iface: default, target: iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9, portal: 172.25.128.122,3260] successful.
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:28.957 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:28.958 19431 DEBUG ironic.drivers.modules.deploy_utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Checking for iSCSI target to become active. verify_iscsi_connection /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:164
2019-09-11 19:21:28.959 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -S execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:29.054 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -S" returned: 0 in 0.095s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:29.055 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "iscsiadm -m node -S" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:29.055 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "172.25.128.122:3260,1 iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:29.056 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:29.056 19431 DEBUG ironic.drivers.modules.deploy_utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Re-reading iSCSI luns. force_iscsi_lun_update /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:188
2019-09-11 19:21:29.057 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 -R execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:29.173 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 -R" returned: 0 in 0.117s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:29.174 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "iscsiadm -m node -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 -R" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:29.176 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "Rescanning session [sid: 13, target: iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9, portal: 172.25.128.122,3260]
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:29.177 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:29.177 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): env LC_ALL=C LANG=C qemu-img info /var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:29.242 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "env LC_ALL=C LANG=C qemu-img info /var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk" returned: 0 in 0.064s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:29.243 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "env LC_ALL=C LANG=C qemu-img info /var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:74
2019-09-11 19:21:29.243 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "image: /var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk
file format: raw
virtual size: 20G (21474836480 bytes)
disk size: 1.4G
" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:75
2019-09-11 19:21:29.243 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:76
2019-09-11 19:21:29.244 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Starting dd process. dd /usr/lib/python2.7/site-packages/ironic_lib/utils.py:138
2019-09-11 19:21:29.245 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): sudo ironic-rootwrap /etc/ironic/rootwrap.conf dd if=/var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk of=/dev/disk/by-path/ip-172.25.128.122:3260-iscsi-iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9-lun-1 bs=1M oflag=direct execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:31.833 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpl6c3ea power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:31.852 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpl6c3ea power status" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:31.853 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpl6c3ea power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:31.854 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:31.854 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:31.855 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (lock was held 5.00 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:31.856 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:36.855 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmp2PBBqI power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:36.877 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmp2PBBqI power status" returned: 0 in 0.022s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:36.878 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmp2PBBqI power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:36.878 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:36.879 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:36.879 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:36.881 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:41.880 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpcrOHtO power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:41.897 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpcrOHtO power status" returned: 0 in 0.017s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:41.898 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpcrOHtO power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:41.898 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:41.898 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:41.899 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:41.900 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 101c2579-2698-4377-92cf-81f2b84d00a2 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:46.899 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmp4iA10N power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:46.918 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmp4iA10N power status" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:46.919 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmp4iA10N power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:46.919 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:46.920 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:46.921 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 101c2579-2698-4377-92cf-81f2b84d00a2 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:46.922 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:51.921 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmp5bxbYJ power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:51.941 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmp5bxbYJ power status" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:51.942 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmp5bxbYJ power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:51.943 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:51.943 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:51.944 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:51.946 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 55f1e507-7aac-4efa-b702-c782ad86831d (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:21:56.944 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpChi1L8 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:21:56.970 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpChi1L8 power status" returned: 0 in 0.026s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:21:56.971 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpChi1L8 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:21:56.972 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:21:56.972 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:21:56.973 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 55f1e507-7aac-4efa-b702-c782ad86831d (lock was held 5.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:21:56.974 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:01.973 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpj0g_JF power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:01.993 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpj0g_JF power status" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:01.994 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpj0g_JF power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:01.994 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:01.995 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:01.995 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:16.712 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_cleanwait_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:22:16.719 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploy_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:22:16.727 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploying_status' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:22:16.738 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_inspect_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:22:16.746 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._sync_power_states' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:22:16.753 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:16.766 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmp13s3zv power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:16.781 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmp13s3zv power status" returned: 0 in 0.015s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:16.781 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmp13s3zv power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:16.782 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:16.782 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:16.783 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (lock was held 0.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:16.784 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node a8e8ac97-871a-4043-9b62-027b1e72599f (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:21.784 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpcKDPeZ power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:21.801 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpcKDPeZ power status" returned: 0 in 0.018s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:21.802 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpcKDPeZ power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:21.803 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:21.803 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:21.804 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node a8e8ac97-871a-4043-9b62-027b1e72599f (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:21.805 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:26.804 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmpcPvIEe power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:26.823 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmpcPvIEe power status" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:26.825 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmpcPvIEe power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:26.825 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:26.826 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:26.827 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:26.829 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:31.827 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpP7JK3d power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:31.851 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpP7JK3d power status" returned: 0 in 0.024s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:31.852 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpP7JK3d power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:31.852 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:31.853 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:31.853 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:31.855 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:36.854 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmpCVvJxf power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:36.873 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmpCVvJxf power status" returned: 0 in 0.020s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:36.874 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmpCVvJxf power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:36.875 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:36.875 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:36.876 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:36.877 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:41.876 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmp103TEp power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:41.894 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmp103TEp power status" returned: 0 in 0.018s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:41.895 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmp103TEp power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:41.896 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:41.896 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:41.897 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:41.899 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 101c2579-2698-4377-92cf-81f2b84d00a2 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:46.897 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpD0GKFQ power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:46.914 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpD0GKFQ power status" returned: 0 in 0.017s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:46.915 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpD0GKFQ power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:46.915 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:46.916 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:46.917 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 101c2579-2698-4377-92cf-81f2b84d00a2 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:46.918 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:51.917 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmpJ9uBcU power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:51.933 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmpJ9uBcU power status" returned: 0 in 0.017s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:51.934 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmpJ9uBcU power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:51.935 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:51.935 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:51.936 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:51.937 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 55f1e507-7aac-4efa-b702-c782ad86831d (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:22:56.936 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpBC1yIi power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:22:56.953 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpBC1yIi power status" returned: 0 in 0.017s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:22:56.954 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpBC1yIi power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:22:56.955 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:22:56.955 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:22:56.956 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 55f1e507-7aac-4efa-b702-c782ad86831d (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:22:56.957 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:01.956 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpf7nU9K power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:01.977 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpf7nU9K power status" returned: 0 in 0.021s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:01.979 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmpf7nU9K power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:01.980 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:01.980 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:01.981 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:03.925 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "sudo ironic-rootwrap /etc/ironic/rootwrap.conf dd if=/var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk of=/dev/disk/by-path/ip-172.25.128.122:3260-iscsi-iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9-lun-1 bs=1M oflag=direct" returned: 0 in 94.682s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:03.926 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "dd if=/var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk of=/dev/disk/by-path/ip-172.25.128.122:3260-iscsi-iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9-lun-1 bs=1M oflag=direct" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:74
2019-09-11 19:23:03.927 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:75
2019-09-11 19:23:03.927 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "20480+0 records in
20480+0 records out
21474836480 bytes (21 GB) copied, 94.5813 s, 227 MB/s
" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:76
2019-09-11 19:23:03.928 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): sudo ironic-rootwrap /etc/ironic/rootwrap.conf hexdump -s 440 -n 4 -e "0x%08x" /dev/disk/by-path/ip-172.25.128.122:3260-iscsi-iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9-lun-1 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:04.051 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "sudo ironic-rootwrap /etc/ironic/rootwrap.conf hexdump -s 440 -n 4 -e "0x%08x" /dev/disk/by-path/ip-172.25.128.122:3260-iscsi-iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9-lun-1" returned: 0 in 0.123s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:04.052 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "hexdump -s 440 -n 4 -e "0x%08x" /dev/disk/by-path/ip-172.25.128.122:3260-iscsi-iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9-lun-1" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:74
2019-09-11 19:23:04.052 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "0x000f0d74" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:75
2019-09-11 19:23:04.053 19431 DEBUG ironic_lib.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic_lib/utils.py:76
2019-09-11 19:23:04.053 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -p 172.25.128.122:3260 -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 --logout execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:04.152 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -p 172.25.128.122:3260 -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 --logout" returned: 0 in 0.098s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:04.153 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "iscsiadm -m node -p 172.25.128.122:3260 -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 --logout" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:04.154 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "Logging out of session [sid: 13, target: iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9, portal: 172.25.128.122,3260]
Logout of [sid: 13, target: iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9, portal: 172.25.128.122,3260] successful.
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:04.155 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:04.155 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -p 172.25.128.122:3260 -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 -o delete execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:04.262 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "sudo ironic-rootwrap /etc/ironic/rootwrap.conf iscsiadm -m node -p 172.25.128.122:3260 -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 -o delete" returned: 0 in 0.107s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:04.264 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "iscsiadm -m node -p 172.25.128.122:3260 -T iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 -o delete" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:04.264 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:04.264 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:04.265 19431 DEBUG oslo_concurrency.lockutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Lock "master_image" acquired by "ironic.drivers.modules.image_cache.clean_up" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2019-09-11 19:23:04.266 19431 DEBUG ironic.drivers.modules.image_cache [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Starting clean up for master image cache /var/lib/ironic/master_images clean_up /usr/lib/python2.7/site-packages/ironic/drivers/modules/image_cache.py:196
2019-09-11 19:23:04.267 19431 DEBUG oslo_concurrency.lockutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Lock "master_image" released by "ironic.drivers.modules.image_cache.clean_up" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2019-09-11 19:23:04.275 19431 DEBUG ironic.drivers.modules.agent_base_vendor [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Configuring local boot for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 configure_local_boot /usr/lib/python2.7/site-packages/ironic/drivers/modules/agent_base_vendor.py:782
2019-09-11 19:23:04.275 19431 DEBUG ironic.drivers.modules.ipmitool [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Sending node caa8cab2-61d5-49cb-a7a2-0179429b77e9 raw bytes 0x00 0x08 0x03 0x08 send_raw /usr/lib/python2.7/site-packages/ironic/drivers/modules/ipmitool.py:662
2019-09-11 19:23:06.981 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp2xT1Ws raw 0x00 0x08 0x03 0x08 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:07.002 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp2xT1Ws raw 0x00 0x08 0x03 0x08" returned: 0 in 0.021s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:07.003 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp2xT1Ws raw 0x00 0x08 0x03 0x08" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:07.004 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:07.005 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:07.005 19431 DEBUG ironic.drivers.modules.ipmitool [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] send raw bytes returned stdout: 
, stderr:  send_raw /usr/lib/python2.7/site-packages/ironic/drivers/modules/ipmitool.py:669
2019-09-11 19:23:12.006 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmprMes57 chassis bootdev disk options=persistent execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:12.102 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmprMes57 chassis bootdev disk options=persistent" returned: 0 in 0.097s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:12.104 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmprMes57 chassis bootdev disk options=persistent" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:12.105 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "Set Boot Device to disk
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:12.105 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:12.106 19431 INFO ironic.drivers.modules.agent_base_vendor [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Local boot successfully configured for node caa8cab2-61d5-49cb-a7a2-0179429b77e9
2019-09-11 19:23:12.107 19431 DEBUG ironic.common.pxe_utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Cleaning up PXE config for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 clean_up_pxe_config /usr/lib/python2.7/site-packages/ironic/common/pxe_utils.py:259
2019-09-11 19:23:12.108 19431 DEBUG ironic.drivers.modules.deploy_utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Deploy boot mode is None for caa8cab2-61d5-49cb-a7a2-0179429b77e9. get_boot_mode_for_deploy /usr/lib/python2.7/site-packages/ironic/drivers/modules/deploy_utils.py:796
2019-09-11 19:23:12.110 19431 DEBUG ironic.drivers.modules.ipmitool [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Sending node caa8cab2-61d5-49cb-a7a2-0179429b77e9 raw bytes 0x00 0x08 0x03 0x08 send_raw /usr/lib/python2.7/site-packages/ironic/drivers/modules/ipmitool.py:662
2019-09-11 19:23:16.439 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._sync_local_state' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:23:16.713 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_cleanwait_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:23:16.720 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploy_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:23:16.727 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploying_status' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:23:16.738 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_inspect_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:23:16.747 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._sync_power_states' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:23:16.752 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:17.107 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpz5LDwl power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:17.116 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpfrqSlr raw 0x00 0x08 0x03 0x08 execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:17.127 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpz5LDwl power status" returned: 0 in 0.021s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:17.128 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpz5LDwl power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:17.128 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:17.129 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:17.129 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (lock was held 0.38 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:17.131 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node a8e8ac97-871a-4043-9b62-027b1e72599f (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:17.134 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpfrqSlr raw 0x00 0x08 0x03 0x08" returned: 0 in 0.017s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:17.134 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpfrqSlr raw 0x00 0x08 0x03 0x08" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:17.135 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:17.135 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:17.136 19431 DEBUG ironic.drivers.modules.ipmitool [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] send raw bytes returned stdout: 
, stderr:  send_raw /usr/lib/python2.7/site-packages/ironic/drivers/modules/ipmitool.py:669
2019-09-11 19:23:22.136 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmp6tfeyb power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:22.146 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp2ER7Me chassis bootdev disk options=persistent execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:22.157 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmp6tfeyb power status" returned: 0 in 0.021s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:22.158 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmp6tfeyb power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:22.158 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:22.159 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:22.159 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node a8e8ac97-871a-4043-9b62-027b1e72599f (lock was held 5.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:22.161 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:22.243 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp2ER7Me chassis bootdev disk options=persistent" returned: 0 in 0.097s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:22.244 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp2ER7Me chassis bootdev disk options=persistent" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:22.244 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "Set Boot Device to disk
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:22.245 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:22.245 19431 DEBUG ironic.drivers.modules.agent_client [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Executing agent command standby.power_off for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 _command /usr/lib/python2.7/site-packages/ironic/drivers/modules/agent_client.py:69
2019-09-11 19:23:22.267 19431 DEBUG ironic.drivers.modules.agent_client [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Agent command standby.power_off for node caa8cab2-61d5-49cb-a7a2-0179429b77e9 returned result None, error None, HTTP status code 200 _command /usr/lib/python2.7/site-packages/ironic/drivers/modules/agent_client.py:99
2019-09-11 19:23:27.160 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmphthwcv power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:27.185 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmphthwcv power status" returned: 0 in 0.026s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:27.186 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmphthwcv power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:27.187 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:27.187 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:27.188 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (lock was held 5.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:27.189 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:27.245 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp6_w2Sl power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:27.265 19431 DEBUG oslo_concurrency.processutils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp6_w2Sl power status" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:27.265 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp6_w2Sl power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:27.266 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:27.266 19431 DEBUG ironic.common.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:32.188 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpkNhaEQ power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:32.213 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpkNhaEQ power status" returned: 0 in 0.025s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:32.215 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpkNhaEQ power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:32.215 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:32.216 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:32.217 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (lock was held 5.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:32.219 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:32.267 19431 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp6j_7CO power off execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:32.291 19431 DEBUG oslo_concurrency.processutils [-] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp6j_7CO power off" returned: 0 in 0.023s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:32.292 19431 DEBUG ironic.common.utils [-] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp6j_7CO power off" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:32.292 19431 DEBUG ironic.common.utils [-] Command stdout is: "Chassis Power Control: Down/Off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:32.293 19431 DEBUG ironic.common.utils [-] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:37.217 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmp665AjC power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:37.252 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmp665AjC power status" returned: 0 in 0.035s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:37.253 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmp665AjC power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:37.254 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:37.254 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:37.255 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (lock was held 5.04 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:37.263 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:37.294 19431 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmph1qBe3 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:37.312 19431 DEBUG oslo_concurrency.processutils [-] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmph1qBe3 power status" returned: 0 in 0.018s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:37.313 19431 DEBUG ironic.common.utils [-] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmph1qBe3 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:37.313 19431 DEBUG ironic.common.utils [-] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:37.313 19431 DEBUG ironic.common.utils [-] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:42.256 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpYOgwoq power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:42.278 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpYOgwoq power status" returned: 0 in 0.022s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:42.279 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpYOgwoq power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:42.280 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:42.281 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:42.282 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:42.283 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 101c2579-2698-4377-92cf-81f2b84d00a2 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:42.314 19431 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpf2yoLJ power on execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:42.805 19431 DEBUG oslo_concurrency.processutils [-] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpf2yoLJ power on" returned: 0 in 0.491s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:42.807 19431 DEBUG ironic.common.utils [-] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpf2yoLJ power on" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:42.808 19431 DEBUG ironic.common.utils [-] Command stdout is: "Chassis Power Control: Up/On
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:42.808 19431 DEBUG ironic.common.utils [-] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:47.282 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpMveo5u power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:47.301 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpMveo5u power status" returned: 0 in 0.020s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:47.302 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpMveo5u power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:47.303 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:47.303 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:47.304 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 101c2579-2698-4377-92cf-81f2b84d00a2 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:47.305 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:47.809 19431 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpsANuc_ power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:47.826 19431 DEBUG oslo_concurrency.processutils [-] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpsANuc_ power status" returned: 0 in 0.016s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:47.826 19431 DEBUG ironic.common.utils [-] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmpsANuc_ power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:47.827 19431 DEBUG ironic.common.utils [-] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:47.827 19431 DEBUG ironic.common.utils [-] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:47.828 19431 INFO ironic.conductor.utils [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Successfully set node caa8cab2-61d5-49cb-a7a2-0179429b77e9 power state to power on.
2019-09-11 19:23:47.838 19431 DEBUG ironic.common.states [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Exiting old state 'deploying' in response to event 'done' on_exit /usr/lib/python2.7/site-packages/ironic/common/states.py:203
2019-09-11 19:23:47.839 19431 DEBUG ironic.common.states [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Entering new state 'active' in response to event 'done' on_enter /usr/lib/python2.7/site-packages/ironic/common/states.py:209
2019-09-11 19:23:47.846 19431 INFO ironic.drivers.modules.agent_base_vendor [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Deployment to node caa8cab2-61d5-49cb-a7a2-0179429b77e9 done
2019-09-11 19:23:47.852 19431 DEBUG ironic.conductor.task_manager [req-6dc1fbdb-21cb-46a1-bf0f-5fb03a350883 - - - - -] Successfully released exclusive lock for calling vendor passthru on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (lock was held 139.34 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:52.304 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmpf0VdQ7 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:52.327 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmpf0VdQ7 power status" returned: 0 in 0.023s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:52.328 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6237 -U admin -R 12 -N 5 -f /tmp/tmpf0VdQ7 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:52.329 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:52.330 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:52.331 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (lock was held 5.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:52.333 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 55f1e507-7aac-4efa-b702-c782ad86831d (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:23:57.331 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpH9O5Y0 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:23:57.355 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpH9O5Y0 power status" returned: 0 in 0.024s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:23:57.356 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6238 -U admin -R 12 -N 5 -f /tmp/tmpH9O5Y0 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:23:57.357 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:23:57.357 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:23:57.358 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 55f1e507-7aac-4efa-b702-c782ad86831d (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:23:57.360 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:24:02.359 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmp7EF7Q1 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:24:02.391 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmp7EF7Q1 power status" returned: 0 in 0.032s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:24:02.392 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6239 -U admin -R 12 -N 5 -f /tmp/tmp7EF7Q1 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:24:02.393 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:24:02.394 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:24:02.394 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 4b8c4324-43bb-4f1d-a311-40506219fa4c (lock was held 5.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:24:16.714 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_cleanwait_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:24:16.721 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploy_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:24:16.728 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_deploying_status' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:24:16.738 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._check_inspect_timeouts' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:24:16.747 19431 DEBUG futurist.periodics [-] Submitting periodic function 'ironic.conductor.manager.ConductorManager._sync_power_states' _process_scheduled /usr/lib/python2.7/site-packages/futurist/periodics.py:611
2019-09-11 19:24:16.752 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:24:16.768 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpHhCnju power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:24:16.791 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpHhCnju power status" returned: 0 in 0.023s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:24:16.791 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6230 -U admin -R 12 -N 5 -f /tmp/tmpHhCnju power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:24:16.792 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:24:16.792 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:24:16.793 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 15cdd503-39a3-49ee-a8fe-90f9c5da2b2e (lock was held 0.04 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:24:16.794 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node a8e8ac97-871a-4043-9b62-027b1e72599f (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:24:21.793 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpk3gXwC power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:24:21.815 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpk3gXwC power status" returned: 0 in 0.021s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:24:21.816 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6231 -U admin -R 12 -N 5 -f /tmp/tmpk3gXwC power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:24:21.816 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:24:21.817 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:24:21.818 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node a8e8ac97-871a-4043-9b62-027b1e72599f (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:24:21.819 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:24:26.818 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmpFm06hO power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:24:26.836 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmpFm06hO power status" returned: 0 in 0.018s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:24:26.837 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6232 -U admin -R 12 -N 5 -f /tmp/tmpFm06hO power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:24:26.838 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:24:26.838 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:24:26.839 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 601b41a7-28e9-43ed-b1b9-0d036ac93d0e (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:24:26.841 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:24:31.839 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp2Csjnc power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:24:31.860 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp2Csjnc power status" returned: 0 in 0.021s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:24:31.861 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6250 -U admin -R 12 -N 5 -f /tmp/tmp2Csjnc power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:24:31.862 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:24:31.862 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:24:31.863 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node caa8cab2-61d5-49cb-a7a2-0179429b77e9 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:24:31.864 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:24:36.863 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpuAxWTZ power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:24:36.882 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpuAxWTZ power status" returned: 0 in 0.019s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:24:36.882 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6233 -U admin -R 12 -N 5 -f /tmp/tmpuAxWTZ power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:24:36.883 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:24:36.883 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:24:36.884 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 10d99da0-75e1-4e9b-bd3c-ef349600e039 (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:24:36.885 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:24:41.884 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmpr2nfQ9 power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:24:41.907 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmpr2nfQ9 power status" returned: 0 in 0.022s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:24:41.908 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6234 -U admin -R 12 -N 5 -f /tmp/tmpr2nfQ9 power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:24:41.909 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:24:41.909 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:24:41.910 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 14e6f32d-cb4d-41c8-a4d7-b32251935fca (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:24:41.912 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:24:46.910 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpA9c34I power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:24:46.933 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpA9c34I power status" returned: 0 in 0.023s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:24:46.935 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6235 -U admin -R 12 -N 5 -f /tmp/tmpA9c34I power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:24:46.935 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is off
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:24:46.936 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:24:46.937 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node d875e0d0-06cc-43d4-a314-4cd8e3eb5c6a (lock was held 5.02 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:24:46.939 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node 101c2579-2698-4377-92cf-81f2b84d00a2 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224
2019-09-11 19:24:51.938 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpBp4Nip power status execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:326
2019-09-11 19:24:51.961 19431 DEBUG oslo_concurrency.processutils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] CMD "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpBp4Nip power status" returned: 0 in 0.023s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:356
2019-09-11 19:24:51.962 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Execution completed, command line is "ipmitool -I lanplus -H 192.168.121.1 -L ADMINISTRATOR -p 6236 -U admin -R 12 -N 5 -f /tmp/tmpBp4Nip power status" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:90
2019-09-11 19:24:51.963 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stdout is: "Chassis Power is on
" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:91
2019-09-11 19:24:51.964 19431 DEBUG ironic.common.utils [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Command stderr is: "" execute /usr/lib/python2.7/site-packages/ironic/common/utils.py:92
2019-09-11 19:24:51.965 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Successfully released shared lock for power state sync on node 101c2579-2698-4377-92cf-81f2b84d00a2 (lock was held 5.03 sec) release_resources /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:338
2019-09-11 19:24:51.967 19431 DEBUG ironic.conductor.task_manager [req-f530e8b5-f0eb-4ccd-bbc8-164c295a7b33 admin - - - -] Attempting to get shared lock on node f7d4c8a0-752e-4225-becd-0d32d10ffc56 (for power state sync) __init__ /usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py:224


[root@barectrl ~]# ps -ef | grep dd
root         2     0  0 14:33 ?        00:00:00 [kthreadd]
root        67     2  0 14:33 ?        00:00:00 [ipv6_addrconf]
dbus       649     1  0 14:33 ?        00:00:00 /bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root       782   686  0 14:33 ?        00:00:00 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-eth0.pid -lf /var/lib/NetworkManager/dhclient-5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03-eth0.lease -cf /var/lib/NetworkManager/dhclient-eth0.conf eth0
root     19217 19431  0 19:21 ?        00:00:00 sudo ironic-rootwrap /etc/ironic/rootwrap.conf dd if=/var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk of=/dev/disk/by-path/ip-172.25.128.122:3260-iscsi-iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9-lun-1 bs=1M oflag=direct
root     19220 19217  0 19:21 ?        00:00:00 /usr/bin/python2 /usr/bin/ironic-rootwrap /etc/ironic/rootwrap.conf dd if=/var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk of=/dev/disk/by-path/ip-172.25.128.122:3260-iscsi-iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9-lun-1 bs=1M oflag=direct
root     19221 19220 17 19:21 ?        00:00:11 /bin/dd if=/var/lib/ironic/images/caa8cab2-61d5-49cb-a7a2-0179429b77e9/disk of=/dev/disk/by-path/ip-172.25.128.122:3260-iscsi-iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9-lun-1 bs=1M oflag=direct
root     19400  5937  0 19:22 pts/9    00:00:00 grep --color=auto dd
nobody   25664     1  0 16:51 ?        00:00:00 dnsmasq --no-hosts --no-resolv --strict-order --except-interface=lo --pid-file=/var/lib/neutron/dhcp/950e9cb1-49ae-4fc7-b3a3-588c32dd8089/pid --dhcp-hostsfile=/var/lib/neutron/dhcp/950e9cb1-49ae-4fc7-b3a3-588c32dd8089/host --addn-hosts=/var/lib/neutron/dhcp/950e9cb1-49ae-4fc7-b3a3-588c32dd8089/addn_hosts --dhcp-optsfile=/var/lib/neutron/dhcp/950e9cb1-49ae-4fc7-b3a3-588c32dd8089/opts --dhcp-leasefile=/var/lib/neutron/dhcp/950e9cb1-49ae-4fc7-b3a3-588c32dd8089/leases --dhcp-match=set:ipxe,175 --bind-interfaces --interface=tap994667d8-ae --dhcp-range=set:tag0,172.25.128.0,static,86400s --dhcp-option-force=option:mtu,1500 --dhcp-lease-max=256 --conf-file=/etc/neutron/dnsmasq-neutron.conf --domain=openstacklocal
[root@barectrl ~]# lsblk 
NAME                     MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                        8:0    0   50G  0 disk 
└─rhel-root              253:0    0 58.5G  0 lvm  /
sdc                        8:32   0   20G  0 disk 
├─sdc1                     8:33   0  512M  0 part 
└─sdc2                     8:34   0 19.5G  0 part 
  ├─rootvg-lv_app        253:2    0    1G  0 lvm  
  ├─rootvg-lv_oracle     253:3    0    1G  0 lvm  
  ├─rootvg-lv_individual 253:4    0    1G  0 lvm  
  ├─rootvg-lv_mon        253:5    0    1G  0 lvm  
  ├─rootvg-lv_wlb        253:6    0    1G  0 lvm  
  ├─rootvg-lv_sec        253:7    0    1G  0 lvm  
  ├─rootvg-lv_spd        253:8    0    1G  0 lvm  
  ├─rootvg-lv_bak        253:9    0    1G  0 lvm  
  ├─rootvg-lv_tmp        253:10   0    1G  0 lvm  
  ├─rootvg-lv_root       253:11   0  4.5G  0 lvm  
  ├─rootvg-lv_var        253:12   0    1G  0 lvm  
  ├─rootvg-lv_home       253:13   0    1G  0 lvm  
  ├─rootvg-lv_usr        253:14   0    1G  0 lvm  
  ├─rootvg-lv_opt        253:15   0    1G  0 lvm  
  └─rootvg-lv_swap       253:16   0    2G  0 lvm  
vda                      252:0    0   10G  0 disk 
├─vda1                   252:1    0  500M  0 part /boot
└─vda2                   252:2    0  9.5G  0 part 
  ├─rhel-root            253:0    0 58.5G  0 lvm  /
  └─rhel-swap            253:1    0    1G  0 lvm  [SWAP]
[root@barectrl ~]# iscsiadm -m session
tcp: [13] 172.25.128.122:3260,1 iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9 (non-flash)
[root@barectrl ~]# iscsiadm -m node
172.25.128.122:3260,1 iqn.2008-10.org.openstack:caa8cab2-61d5-49cb-a7a2-0179429b77e9

